/** Optional area finales. No free-text answer is machine-graded: reasoning is
 * evidenced by selecting relevant arguments and putting them in logical order. */
import {num,choice,multi,errorTask,argument,match,mark} from './practice.js';
export function makeChallenges(base){
 const config=[
 ['village','Die Sternensaat','Liora · Hüterin der Sternensaat','Alle Dorfprojekte sind geschafft. In einer Wurzel liegt eine leuchtende Sternensaat. Entschlüssle ihre Stellenwert-Rätsel: Dann kehren Blumen, Ponys und ein kleiner Regenbogen ins Dorf zurück.',-2,-7,[
  match('Der Sternenspeicher zeigt 4,080. Ziehe die Stellenwertnamen zu allen vier Ziffern – gleiche Ziffern können verschiedene Stellen haben.',['4','0','8','0'],['Einer','Zehntel','Hundertstel','Tausendstel'],[0,1,2,3],'4,080'),
  multi('Welche Lichtetiketten bedeuten genau denselben Anteil wie 0,4?',['40/100','4/100','400/1000','0,040','0,400'],[0,2,4],'Vier Zehntel sind vierzig Hundertstel oder vierhundert Tausendstel. Nullen direkt nach dem Komma ändern dagegen die Stelle der 4.'),
  mark('Drei Viertel des ganzen Sternenbeets sollen blühen. Markiere diesen Anteil auf den 100 gleich großen Feldern.',100,75,'Drei Viertel sind 75/100. Jede Auswahl von 75 gleich großen Feldern bildet denselben Anteil.'),
  errorTask('Ein Lehrling übersetzt ein Bruchschild. Tippe den ersten falschen Schritt an.',['35/1000 sind 35 Tausendstel.','Das schreibe ich als 0,35.','Ich kann dafür auch 0,350 schreiben.'],1,'35 Tausendstel sind 0,035; 0,35 sind bereits 350 Tausendstel.'),
  num('Das Zahlenschloss hat 3 Einer. Die Zehntelstelle ist leer und bekommt eine Null. Es hat 4 Hundertstel und 2 Tausendstel. Welche Zahl öffnet es?','3.042','','Die Stellen sind Einer | Zehntel | Hundertstel | Tausendstel: 3 | 0 | 4 | 2.'),
  argument('Begründe 0,6 = 0,60. Ordne genau drei passende Gedanken. Zwei Karten passen nicht.',['0,6 bedeutet sechs Zehntel.','Jedes Zehntel besteht aus zehn Hundertsteln.','Sechs Zehntel sind deshalb sechzig Hundertstel: 0,60.','Eine zusätzliche Null verzehnfacht immer eine Zahl.','60 ist größer als 6, also ist 0,60 größer.'],[0,1,2],'Die Menge bleibt gleich. Nur die Einheit der Bruchteile wird feiner.')
 ]],
 ['forest','Das Herz des Flüsterwalds','Fenn · Hüter der uralten Eiche','Der Wald ist versorgt. Unter der Eiche erwacht ein seltener Runenkreis. Prüfe Grenzwerte, widerlege falsche Regeln und finde den sicheren Weg für die Rehe.',3,-7,[
  multi('Ein Rehpfad darf höchstens 2,5 m breit sein. Welche Breiten erfüllen die Vorgabe?',['2,500 m','2,501 m','2,49 m','2,050 m','2,51 m'],[0,2,3],'Höchstens schließt 2,5 selbst ein. 2,501 und 2,51 liegen oberhalb der Grenze.'),
  num('Ein Maß wird auf Zehntel zu 3,5 gerundet. Es hat genau zwei Nachkommastellen. Welches ist das größte mögliche Maß?','3.54','m','3,54 liegt noch unter der Mitte zu 3,6. Ab 3,55 wird auf 3,6 gerundet.'),
  {type:'line',text:'Die stille Lichtung liegt bei 1,375 km. Setze die Marke. Die Enden sind beschriftet; alle kleinen Abstände sind gleich groß.',start:1.25,end:1.5,step:.025,answer:'1.375',why:'Zwischen 1,25 und 1,5 liegen zehn Abschnitte zu je 0,025. Der fünfte Abschnitt endet bei 1,375.'},
  errorTask('Wo beginnt der Fehler beim Vergleich?',['Ich vergleiche 4,08 und 4,8.','Die Nachkommazahlen 08 und 8 sind gleich groß.','Daher ist 4,08 = 4,8.'],1,'08 Hundertstel und 8 Zehntel sind nicht gleich viel. 4,8 = 4,80 ist größer als 4,08.'),
  choice('Eine Brücke trägt höchstens 5 kg. Ein Wagen wiegt 5,04 kg. Sein Gewicht gerundet auf Zehntel ist 5,0 kg. Darf er deshalb fahren?',['Nein: Der genaue Wert 5,04 kg liegt über der Grenze.','Ja: 5,0 kg liegt genau auf der Grenze.','Ja: Zwei Nachkommastellen machen die Ladung leichter.'],0,'Sicherheitsgrenzen werden mit dem genauen Wert verglichen, nicht mit einem günstig gerundeten Wert.'),
  argument('Begründe: 0,509 ist größer als 0,49. Ordne drei passende Schritte.',['Schreibe 0,49 als 0,490.','Vergleiche 509 Tausendstel mit 490 Tausendsteln.','509 Tausendstel sind mehr; also ist 0,509 größer.','Drei Nachkommastellen bedeuten grundsätzlich einen größeren Wert.'],[0,1,2],'Gleiche Stellenwerte machen den Vergleich verständlich.')
 ]],
 ['harbor','Die Reise der Wasserpferde','Nela · Hafenmeisterin','Die Ladungen sind versorgt. Nun legt ein leuchtendes Schiff mit Wasserpferden an. Kontrolliere seinen ungewöhnlichen Frachtbrief; danach wird aus dem Hafen eine blühende Uferpromenade.',1,9,[
  num('Ein Vorratstank hat 0,004 m³ Innenvolumen. Wie viele Liter Wasser fasst er?','4','l','1 m³ = 1000 l; 0,004 m³ sind 4 l.'),
  multi('Welche Frachtangaben sind genau gleich 1,05 kg?',['1050 g','1005 g','1 kg und 50 g','1 kg und 5 g'],[0,2],'0,05 kg sind 50 g, nicht 5 g.'),
  errorTask('Die neue Bootsplane hat 0,6 m² Fläche. Wo wird falsch umgerechnet?',['1 m = 100 cm.','Daher gilt 1 m² = 100 cm².','Die Plane hat dann 60 cm².'],1,'Ein Quadratmeter enthält 100 · 100 = 10000 Quadratzentimeter. 0,6 m² sind 6000 cm².'),
  num('Eine Fahrt dauert 1 h und 45 min. Trage die Dauer in Dezimalstunden ein.','1.75','h','45 min sind drei Viertel einer Stunde: 0,75 h.'),
  match('Drei Messschilder wurden vertauscht. Ordne jeder Angabe den genau gleichen Wert zu.',['0,08 m','0,08 m²','0,008 m³'],['8 cm','8 dm²','8 l'],[0,1,2]),
  argument('Begründe 0,25 h = 15 min. Wähle und ordne drei passende Gedanken.',['Eine Stunde hat 60 Minuten.','0,25 h ist ein Viertel einer Stunde.','Ein Viertel von 60 Minuten sind 15 Minuten.','Nach dem Komma werden Stunden immer zu Hundertstelminuten.'],[0,1,2],'Die Unterteilung der Stunde ist nicht dezimal: 1 h = 60 min.')
 ]],
 ['market','Der Markt der tausend Lichter','Ravi · Festkoch','Alle Marktstände sind bereit. Für ein nächtliches Lichterfest müssen ungewöhnliche Bestellungen stimmen. Bestehst du die Herausforderung, kommen Gäste, Wimpel und leuchtende Blumen.',1,8,[
  num('Drei Zutaten wiegen zusammen 4 kg. Die ersten beiden wiegen 1,375 kg und 0,85 kg. Wie schwer ist die dritte?','1.775','kg','1,375 + 0,850 = 2,225; bis 4 fehlen 1,775 kg.'),
  errorTask('Finde den ersten Fehler in der Abrechnung.',['Ich addiere 2,7 + 0,85.','Ich ergänze 2,7 zu 2,70.','70 Hundertstel + 85 Hundertstel sind 155 Hundertstel, also 0,155.'],2,'155 Hundertstel sind 1,55, nicht 0,155. Die Summe ist 3,55.'),
  num('Im Küchentopf sind 875 ml, 0,65 l und 1,025 l Brühe. Wie viele Liter sind es zusammen?','2.55','l','875 ml = 0,875 l. 0,875 + 0,650 + 1,025 = 2,550 l.'),
  multi('Das Budget beträgt genau 5 Taler. Welche Einkäufe passen ohne Überschreitung?',['2,75 + 2,25 Taler','3,99 + 1,02 Taler','1,5 + 1,75 + 1,75 Taler','4,999 + 0,002 Taler'],[0,2],'Genau 5 ist erlaubt. 5,01 und 5,001 überschreiten das Budget.'),
  num('Ein Kassenzettel zeigt □ + 0,09 = 2,03. Welche Zahl wurde verwischt?','1.94','Taler','1,94 + 0,09 = 2,03. Über den nächsten Einer hinweg wird gebündelt.'),
  argument('Erkläre die Summe 0,99 + 0,02. Ordne drei passende Gedanken.',['Das sind zusammen 101 Hundertstel.','100 Hundertstel werden zu einem Ganzen gebündelt.','Ein Ganzes und ein Hundertstel sind 1,01.','101 Hundertstel schreibt man 0,101.'],[0,1,2],'Bündeln verändert die Darstellung, nicht die Gesamtmenge.')
 ]],
 ['cliffs','Der Sternenpfad am Abgrund','Taro · Bergführer','Die Bergstationen sind versorgt. Ein alter Sternenpfad wartet auf präzise Vorratsplanung. Die erfolgreiche Expedition lässt Bergblumen und freundliche Ziegen zurückkehren.',1,8,[
  num('Von einer Rolle mit 10 m bleiben nach dem Abschneiden von 3,875 m noch einige Meter. Davon gehen weitere 2,68 m ab. Wie viel bleibt zuletzt?','3.445','m','10 − 3,875 − 2,680 = 3,445.'),
  num('Nach dem Aufstieg bleiben 1,075 l Wasser. Unterwegs wurden 2,85 l getrunken. Wie viel war anfangs vorhanden?','3.925','l','Rechne rückwärts: 1,075 + 2,850 = 3,925 l.'),
  errorTask('Bei 5,02 − 1,78 muss getauscht werden. Finde den ersten falschen Schritt.',['Ein Einer wird in zehn Zehntel getauscht.','Ein Zehntel wird weiter in zehn Hundertstel getauscht.','Nun sind es 4 Einer, 10 Zehntel und 12 Hundertstel.'],2,'Nach dem zweiten Tausch sind nur 9 Zehntel übrig. 4 E + 9 z + 12 h ist weiterhin 5,02.'),
  num('Ein Kletterseil ist genau 7,5 m lang. Es soll nach dem Kürzen noch 4,875 m lang sein. Wie viel wird abgeschnitten?','2.625','m','7,500 − 4,875 = 2,625.'),
  multi('Eine Vorratsrechnung lautet 6 − 2,48 = 3,52. Welche Proben passen?',['3,52 + 2,48 = 6','6 − 3,52 = 2,48','3,52 − 2,48 = 6','6 + 2,48 = 3,52'],[0,1],'Rest und entnommene Menge ergänzen sich zum Anfang. Auch die andere Subtraktion prüft dieselbe Beziehung.'),
  argument('Warum darf man bei 4 − 0,85 die 4 als 4,00 schreiben? Ordne drei Gedanken.',['Vier Ganze sind zugleich vier Ganze und null Hundertstel.','Die angehängten Nullen ändern den Wert nicht.','Jetzt können gleiche Stellen untereinander stehen.','Die beiden Nullen vergrößern die Zahl auf 400.'],[0,1,2],'Die Endnullen halten Stellen frei, ohne die Menge zu verändern.')
 ]],
 ['mill','Das Fest der Himmelsponys','Alva · Tierpflegerin','Die Mühle läuft, die Tiere sind versorgt. Nun kommen Himmelsponys für ein Flugfest. Löse Futter-, Flächen- und Preisrätsel: Dann wird die Weide zum blühenden Zufluchtsort.',0,9,[
  num('Eine kleine Futterration soll 0,4-mal so groß sein wie die normale. Sie wiegt 0,18 kg. Wie schwer ist die normale Ration?','0.45','kg','Gesucht ist □ · 0,4 = 0,18. 0,45 · 0,4 = 0,18.'),
  num('Eine rechteckige Satteldecke misst 1,25 m × 0,48 m. Wie groß ist ihre Fläche?','0.6','m²','125 · 48 = 6000. Vier Nachkommastellen ergeben 0,6000 m².'),
  errorTask('Finde den ersten Fehler in der Futterrechnung.',['Ich rechne 0,6 · 0,4.','6 · 4 = 24.','Die Faktoren haben zusammen eine Nachkommastelle; das Ergebnis ist 2,4.'],2,'Zusammen sind es zwei Nachkommastellen: 0,24. Ein Faktor unter 1 muss die positive Ausgangsmenge verkleinern.'),
  multi('Für x = 0,8: Welche Aussagen gelten?',['x · 0,75 < x','x · 1 = x','x · 1,01 > x','x · 0 = x'],[0,1,2],'Für ein positives x verkleinert ein positiver Faktor unter 1; 1 lässt unverändert; ein Faktor über 1 vergrößert.'),
  num('Für 0,75 kg Spezialfutter werden 2,40 Taler verlangt. Wie viel kosten 1,5 kg bei gleichem Preis je Kilogramm?','4.8','Taler','1,5 kg sind doppelt so viel wie 0,75 kg. Deshalb verdoppelt sich der Preis.'),
  argument('Begründe 0,2 · 0,3 = 0,06 am Einheitsquadrat. Ordne drei passende Schritte.',['Unterteile jede Seite in zehn gleiche Teile.','Ein Rechteck mit 2 mal 3 kleinen Kästchen bedeckt 6 Kästchen.','Jedes Kästchen ist ein Hundertstel des Ganzen; zusammen sind es 0,06.','Sechs Kästchen bedecken sechs Zehntel des Ganzen.'],[0,1,2],'Zehntel in beiden Richtungen ergeben Hundertstel der Fläche.')
 ]],
 ['cave','Der Kristall der Freundschaft','Miko · Freund der Grottenwesen','Alle Grottenwesen sind versöhnt. Ein großer Kristall reagiert nur auf gerechtes Teilen und gute Begründungen. Erwecke ihn, damit leuchtende Pilze und kleine Drachen die Grotten beleben.',0,8,[
  num('Im Kessel sind 4,1 l. Jeder Becher fasst 0,35 l. Wie viele Becher können vollständig gefüllt werden?','11','volle Becher','11 · 0,35 = 3,85 l. Für den zwölften Becher wären 4,2 l nötig. Es bleiben 0,25 l.'),
  num('Sieben gleiche Portionen enthalten zusammen 1,575 kg. Wie schwer ist eine Portion?','0.225','kg','1,575 : 7 = 0,225; Probe: 7 · 0,225 = 1,575.'),
  errorTask('Prüfe die Umformung und finde den ersten Fehler.',['3,6 : 0,12 soll berechnet werden.','Ich multipliziere beide Zahlen mit 100.','Daraus wird 36 : 12 = 3.'],2,'3,6 · 100 = 360. Deshalb lautet die Rechnung 360 : 12 = 30.'),
  num('Eine Portion fasst 0,125 l. Wie viele solcher Portionen füllen zusammen 1 l?','8','Portionen','8 · 0,125 l = 1 l.'),
  multi('Welche Divisionen haben dasselbe Ergebnis wie 2,4 : 0,6?',['24 : 6','240 : 60','2,4 : 6','0,24 : 0,06'],[0,1,3],'Dividend und Divisor müssen mit demselben von null verschiedenen Faktor verändert werden.'),
  argument('Warum ist 3 : 0,5 = 6 größer als 3? Ordne drei passende Gedanken.',['Die Frage lautet: Wie viele halbe Liter passen in drei Liter?','In jeden Liter passen zwei halbe Liter.','Drei Liter enthalten daher sechs halbe Liter.','Division verkleinert grundsätzlich jede positive Zahl.'],[0,1,2],'Beim Portionieren zählt das Ergebnis Portionen, nicht Liter.')
 ]],
 ['castle','Die Krone von Kommaland','Yumi · Sternendrache','Das Sternenfest ist gelungen. Nun erscheint die höchste Herausforderung: ein Festplan mit Rückwärtsrechnungen, Grenzen und Beweisen. Die Krone lässt die ganze Burg im Regenbogenlicht erstrahlen.',0,6,[
  num('Nach einmalig 1,50 Taler Rabatt kostet der Einkauf 8,10 Taler. Jede gleiche Lampe kostet 1,20 Taler. Wie viele Lampen wurden gekauft?','8','Lampen','Vor dem Rabatt waren es 9,60 Taler. 9,60 : 1,20 = 8.'),
  num('Zwölf Gäste trinken je 0,35 l. Es stehen 2,75 l bereit. Wie viele zusätzliche Flaschen zu je 0,5 l müssen mindestens geöffnet werden?','3','Flaschen','Es fehlen 4,2 − 2,75 = 1,45 l. Zwei Flaschen reichen nicht; drei liefern 1,5 l.'),
  errorTask('Finde den ersten Fehler: Vier Tiere bekommen je 0,45 kg. Insgesamt liegen 2,5 kg bereit.',['Gesamtbedarf: 4 · 0,45 = 1,8 kg.','Rest: 2,5 − 1,8 = 0,7 kg.','Zwei Tiere teilen den Rest: 0,7 : 2 = 0,35 Tiere.'],2,'Die Division ergibt 0,35 kg pro Tier, nicht eine Anzahl von Tieren.'),
  num('Die rechteckige Festplane ist 2,4 m × 1,25 m groß. Farbe reicht für genau 3 m². Wie viele Quadratmeter bleiben ungestrichen?','0','m²','2,4 · 1,25 = 3 m². Die Farbe reicht genau; es bleibt keine Fläche ungestrichen.'),
  multi('Sechs Gäste zahlen gleich viel. Die Gesamtrechnung lautet 6 · 2,5 − 3. Der Rabatt von 3 Talern gilt einmalig für alles. Welche Aussagen stimmen?',['Der Gesamtpreis ist 12 Taler.','Jede Person zahlt 2 Taler.','Jede Person erhält 3 Taler Rabatt.','Der Gesamtrabatt beträgt 18 Taler.'],[0,1],'6 · 2,5 = 15, abzüglich 3 ergibt 12. Geteilt durch 6 bleiben 2 Taler pro Person.'),
  argument('Plane mit 5 m Band: Vier Bögen brauchen je 0,85 m. Der Rest wird in Schleifen zu je 0,4 m geteilt. Ordne die vier passenden Schritte.',['Berechne den Bedarf der Bögen: 4 · 0,85 = 3,4 m.','Ziehe ihn vom Vorrat ab: 5 − 3,4 = 1,6 m.','Teile den Rest: 1,6 : 0,4 = 4 Schleifen.','Prüfe: 3,4 m + 4 · 0,4 m = 5 m.','Teile zuerst den ganzen Vorrat durch 0,85.'],[0,1,2,3],'Erst Bedarf, dann Rest, dann Portionierung; am Schluss prüft die Rückrechnung den vollständigen Plan.')
 ]]
 ];
 const lessonFor={village:['places-hundred','equal-zeros','fraction-threequarters','fraction-thousand','write-thousand','equal-zeros'],forest:['limits','round-near','line-fives','compare-hundred','estimate','order-thousand'],harbor:['cube-litre','kg-grams','square-units','time-quarter','cube-units','time-quarter'],market:['add-thousand','add-carry','add-units','add-group','add-carry','add-carry'],cliffs:['two-subtractions','subtract-proof','subtract-whole','subtract-thousand','subtract-proof','subtract-whole'],mill:['multiply-decimal','rectangle-decimal','multiply-decimal','multiply-smaller','unit-price','rectangle-decimal'],cave:['portion-hundred','divide-equal','divide-scale','portion-hundred','divide-scale','divide-small'],castle:['operations','plan-leftover','divide-equal','rectangle-decimal','one-discount','plan-leftover']};
 return config.map(([region,title,npc,story,x,z,tasks])=>({id:'master-'+region,region,title,npc,story,x,z,kind:'masterstone',advanced:true,challenge:true,requires:base.filter(q=>q.region===region).map(q=>q.id),reward:'Der ganze Ort blüht auf: Blumen, Tiere, Bewohner und ein leuchtender Himmelsbogen bleiben in der Landschaft.',tasks:tasks.map((t,i)=>({...t,lesson:lessonFor[region][i],skill:'Meisterherausforderung · '+title,stage:'challenge',hint:'Diese Herausforderung verbindet mehrere Gedanken. Lies bei Bedarf das passende Wissen; suche eine Probe oder eine andere Darstellung.',key:`master-${region}:${i}`}))}));
}
