import {LEARNING_GOALS,PRACTICE_SKILLS,OPEN_WORK} from '../teacher-dashboard/shared/learning7-content.js';
import {PRACTICE_RULES,CONFIDENCE_LABELS,WORK_STATUSES,learning7Projection,practiceRecommendation,skillsForEvent} from '../teacher-dashboard/shared/learning7.js';
import {uid} from '../teacher-dashboard/shared/save-schema.js';
import {PRACTICE_BANK,practiceTask} from './adaptive-bank.js';
import {esc} from './ui.js';
/** Finite adaptive selection. Core answers, marks, buildings and prerequisites are never written here. */
export function selectPractice(bank,skillId,events=[],requestedCount=null){
 const view=learning7Projection(events),history=view.rounds.filter(r=>r.skillId===skillId),recent=history.slice(-3).flatMap(r=>r.tasks),errors=recent.reduce((n,t)=>n+t.attempts.filter(a=>!a.correct).length,0);
 const confident=recent.length>=2&&recent.slice(-2).every(t=>t.correct&&t.attempts.length===1&&!t.helpCount);
 const count=requestedCount??(confident?2:errors>=3?4:3);
 const limit=Math.max(PRACTICE_RULES.minimum,Math.min(PRACTICE_RULES.maximum,Number.isInteger(count)?count:3));
 const pool=bank.filter(t=>t.practiceSkill===skillId),seen=new Map();for(const r of history)for(const t of r.tasks)seen.set(t.taskKey,r.startedAt);
 const sorted=pool.slice().sort((a,b)=>Number(seen.has(a.key))-Number(seen.has(b.key))||(seen.get(a.key)||'').localeCompare(seen.get(b.key)||'')||(a.difficulty-b.difficulty)||a.key.localeCompare(b.key));
 return sorted.slice(0,limit).sort((a,b)=>a.difficulty-b.difficulty);
}
export class Enrichment {
 constructor(log,a){this.log=log;this.a=a;this.back=null;this.workDraft=null;this.cached=null;this.revision=-1;}
 view(){if(this.revision!==this.log.revision||this.cachedStudent!==this.log.studentId){this.cached=learning7Projection(this.log.events);this.revision=this.log.revision;this.cachedStudent=this.log.studentId;}return this.cached;}
 emit(type,data,context={}){this.log.ensure();return this.log.emit('v7_'+type,data,context);}
 button(text,id,primary=false){return `<button type="button" id="${id}" class="${primary?'primary':'secondary'}-button">${esc(text)}</button>`;}
 beforePanel(mode){this.saveWorkDraft();if(!mode.startsWith('v7-'))this.back=null;}
 open(mode,config,back=()=>this.a.closeWorld()){this.a.open('v7-'+mode,{tag:'DEIN LERNWEG · FREIWILLIG',symbol:'book',className:'v7-panel',...config});this.back=back;}
 handleClose(){if(!this.back)return false;this.saveWorkDraft();const fn=this.back;this.back=null;fn();return true;}
 goalHTML(q,after=false){const g=LEARNING_GOALS[q.id];if(!g)return '';const value=this.view().goals.filter(x=>x.goalId===g.goalId&&x.type==='v7_goal_reflection').at(-1)?.value;
  return `<section class="v7-goal" aria-label="Dein Lernziel"><p class="goal-line"><strong>Ziel:</strong> ${esc(g.text)}</p><details class="goal-criteria"><summary>Woran erkenne ich das?</summary><ul>${g.criteria.map(c=>`<li>${esc(c)}</li>`).join('')}</ul></details>${after?`<fieldset class="v7-confidence"><legend>Wie sicher bist du jetzt? <small>freiwillig</small></legend>${CONFIDENCE_LABELS.map((label,i)=>`<button type="button" data-goal-confidence="${i+1}" aria-pressed="${value===i+1}">${esc(label)}</button>`).join('')}</fieldset><p id="v7GoalFeedback" class="sr-only" aria-live="polite"></p>`:''}</section>`;
 }
 mountQuest(q,{after=false}={}){
  if(q.challenge)return;const body=document.querySelector('.panel-body');if(!body)return;body.insertAdjacentHTML('afterbegin',this.goalHTML(q,after));
  const goal=LEARNING_GOALS[q.id];if(!goal)return;
  body.insertAdjacentHTML('beforeend',`<details class="v7-quest-tools"><summary>Zusatzübung &amp; Partnerauftrag</summary><div class="learning-actions">${this.button('Gezielt kurz üben','v7QuestPractice')}${this.button('Partnerauftrag','v7QuestOpen')}</div></details>`);
  document.getElementById('v7QuestPractice').onclick=()=>this.hub(q.region,()=>this.a.showQuest(q));document.getElementById('v7QuestOpen').onclick=()=>this.showWork(OPEN_WORK.find(w=>w.region===q.region).id,()=>this.a.showQuest(q));
  body.querySelectorAll('[data-goal-confidence]').forEach(b=>b.onclick=()=>{this.emit('goal_reflection',{goalId:goal.goalId,value:+b.dataset.goalConfidence});body.querySelectorAll('[data-goal-confidence]').forEach(x=>x.setAttribute('aria-pressed',x===b?'true':'false'));document.getElementById('v7GoalFeedback').textContent='Einschätzung übernommen.';});
 }
 recommendation(q,t){if(q.challenge)return null;const skills=skillsForEvent({taskId:q.id+':'+t.key,skillId:t.lesson});for(const s of skills){const r=practiceRecommendation(this.log.events,s,{questId:q.id,sessionId:this.log.current?.sessionId});if(r)return r;}return null;}
 mountTask(s){if(s.practice)return;const r=this.recommendation(s.q,s.q.tasks[s.index]);
  const actions=document.querySelector('.learning-actions');if(actions){const b=document.createElement('button');b.type='button';b.className='secondary-button';b.id='v7PracticeManual';b.textContent='Kurz üben';b.onclick=()=>this.offer(skillsForEvent({taskId:s.q.id+':'+s.q.tasks[s.index].key,skillId:s.q.tasks[s.index].lesson})[0]||LEARNING_GOALS[s.q.id]?.skills[0]||'place','manual',()=>this.a.showTask());actions.append(b);}
  if(!r)return;const body=document.querySelector('.panel-body');body.insertAdjacentHTML('beforeend',`<aside class="v7-practice-offer"><strong>Eine kurze Zusatzrunde?</strong><details><summary>Warum?</summary><p>${esc(r.text)}</p></details><div class="v7-inline">${this.button('Jetzt üben','v7Try')}${this.button('Später üben','v7Later')}${this.button('Ohne Zusatzübung weiter','v7No')}</div></aside>`);
  document.getElementById('v7Try').onclick=()=>this.start(r.skillId,r.reason);for(const [id,choice]of [['v7Later','later'],['v7No','declined']])document.getElementById(id).onclick=()=>{this.decide(r.skillId,choice,r.reason);this.a.showTask();};
 }
 decide(skillId,choice,reason='manual'){this.emit('practice_decision',{skillId,choice,reason});}
 offer(skillId,reason='manual',back=()=>this.a.closeWorld()){
  if(!PRACTICE_SKILLS[skillId])skillId='place';const selected=selectPractice(PRACTICE_BANK,skillId,this.log.events);
  this.open('offer',{title:PRACTICE_SKILLS[skillId].title,body:`<section class="v7-offer-intro"><span class="mini-tag">FREIWILLIGE ZUSATZÜBUNG</span><h3>${selected.length} Aufgaben – danach entscheidest du neu.</h3><p>${reason==='exam'?'In der letzten Wegprobe war dieser Gedanke noch offen.':reason==='errors'?'Einige letzte Versuche zu diesem Gedanken passten noch nicht.':'Du kannst diesen Gedanken unabhängig vom Kernlernweg festigen.'}</p><p>Die Runde gibt keine Note, baut kein Questobjekt und schaltet keine Herausforderung frei. Du kannst einzelne Aufgaben oder die ganze Runde für später lassen.</p></section>`,foot:this.button('Später üben','v7OfferLater')+this.button('Ohne Zusatzübung weiter','v7OfferNo')+this.button('Jetzt üben','v7OfferNow',true)},back);
  document.getElementById('v7OfferNow').onclick=()=>this.start(skillId,reason);for(const [id,choice]of [['v7OfferLater','later'],['v7OfferNo','declined']])document.getElementById(id).onclick=()=>{this.decide(skillId,choice,reason);this.back=null;back();};
 }
 hub(region=this.a.region(),back=()=>this.a.closeWorld()){
  const view=this.view(),active=view.rounds.filter(r=>!r.finishedAt),qs=this.a.quests.filter(q=>q.region===region&&!q.challenge),skills=[...new Set(qs.flatMap(q=>LEARNING_GOALS[q.id]?.skills||[]))],w=OPEN_WORK.find(w=>w.region===region);
  this.open('hub',{title:'Deine Lernwerkstatt',tag:'KURZ ÜBEN · ERKLÄREN · MITEINANDER DENKEN',body:`<p>Alles hier ist freiwillig. Dein Kernlernweg bleibt unverändert.</p>${active.length?`<section class="v7-resume"><h3>Begonnene Zusatzrunden</h3>${active.slice(-4).map(r=>`<button type="button" class="secondary-button" data-resume-practice="${esc(r.roundId)}">${esc(PRACTICE_SKILLS[r.skillId].title)} · ${r.tasks.filter(t=>t.correct||t.skipped).length}/${r.tasks.length} bearbeitet</button>`).join('')}</section>`:''}<h3>Passend zu diesem Gebiet</h3><div class="v7-skill-grid">${skills.map(k=>this.skillButton(k,view)).join('')}</div><details class="v7-all-skills"><summary>Andere Gedanken üben</summary><div class="v7-skill-grid">${Object.keys(PRACTICE_SKILLS).filter(k=>!skills.includes(k)).map(k=>this.skillButton(k,view)).join('')}</div></details>${w?`<section class="v7-partner-card"><span class="mini-tag">PARTNERAUFTRAG</span><h3>${esc(w.title)}</h3><p>Eigene Ideen entwickeln und erklären. Allein beginnen oder später besprechen.</p>${this.button('Auftrag öffnen','v7OpenWork')}</section>`:''}`,foot:this.button('Zurück','v7HubBack',true)},back);
  document.getElementById('v7HubBack').onclick=()=>{this.back=null;back();};document.querySelectorAll('[data-practice-skill]').forEach(b=>b.onclick=()=>this.offer(b.dataset.practiceSkill,'manual',()=>this.hub(region,back)));document.querySelectorAll('[data-resume-practice]').forEach(b=>b.onclick=()=>this.resume(b.dataset.resumePractice));if(w)document.getElementById('v7OpenWork').onclick=()=>this.showWork(w.id,()=>this.hub(region,back));
 }
 skillButton(key,view){return `<button type="button" data-practice-skill="${key}" class="v7-skill"><strong>${esc(PRACTICE_SKILLS[key].title)}</strong><small>${view.deferred.includes(key)?'Für später gemerkt · ':''}2–5 Aufgaben · auf Wunsch</small></button>`;}
 start(skillId,reason='manual'){
  const tasks=selectPractice(PRACTICE_BANK,skillId,this.log.events);if(tasks.length<2){this.a.toast('Diese Übungsrunde ist nicht verfügbar.');return;}
  const roundId=uid();this.decide(skillId,'now',reason);this.emit('practice_started',{roundId,skillId,taskKeys:tasks.map(t=>t.key)});this.back=null;this.a.startPractice(this.makeQuest(roundId,skillId,tasks),0);
 }
 makeQuest(roundId,skillId,tasks){const q=this.a.quests.find(q=>q.id===PRACTICE_SKILLS[skillId].questId);return {id:'practice:'+roundId,roundId,practiceSkill:skillId,region:q.region,title:'Kurz üben: '+PRACTICE_SKILLS[skillId].title,npc:'Deine freiwillige Lernwerkstatt',kind:'book',tasks,practice:true};}
 resume(roundId){const r=this.view().rounds.find(r=>r.roundId===roundId);if(!r||r.finishedAt)return;const tasks=r.tasks.map(t=>practiceTask(t.taskKey));if(tasks.some(t=>!t)){this.a.toast('Eine alte Zusatzaufgabe ist nicht verfügbar; der Kernfortschritt bleibt erhalten.');return;}const index=r.tasks.findIndex(t=>!t.correct&&!t.skipped);this.back=null;if(index<0){this.finishRound(r.roundId);return;}this.a.startPractice(this.makeQuest(r.roundId,r.skillId,tasks),index);}
 task(s){const t=s.q.tasks[s.index],roundId=s.q.roundId,skillId=s.q.practiceSkill;if(this.log.ctx?.taskRunId!==roundId+':'+s.index){this.log.tick();this.log.closeHelps();}this.log.ctx={kind:'practice',topicId:s.q.region,runId:roundId,taskRunId:roundId+':'+s.index,skillId};s.logTaskRunId=roundId+':'+s.index;
  if(!this.log.events.some(e=>e.type==='v7_practice_task'&&e.data.roundId===roundId&&e.data.taskKey===t.key))this.emit('practice_task',{roundId,skillId,taskKey:t.key,index:s.index},this.log.ctx);
 }
 attempt(s,correct){const roundId=s.q.roundId,taskKey=s.q.tasks[s.index].key,attemptNumber=this.log.events.filter(e=>e.type==='v7_practice_attempt'&&e.data.roundId===roundId&&e.data.taskKey===taskKey).length+1;this.log.tick();this.emit('practice_attempt',{roundId,skillId:s.q.practiceSkill,taskKey,attemptNumber,correct},this.log.ctx);}
 skip(s){this.emit('practice_skipped',{roundId:s.q.roundId,taskKey:s.q.tasks[s.index].key},this.log.ctx);this.a.advancePractice();}
 pause(s){if(!s?.practice)return;this.log.tick();this.log.closeHelps();this.emit('practice_paused',{roundId:s.q.roundId});this.log.ctx={};}
 finishRound(roundId){this.log.tick();this.log.closeHelps();this.log.ctx={};let r=this.view().rounds.find(r=>r.roundId===roundId);if(!r)return;if(!r.finishedAt)this.emit('practice_finished',{roundId});r=this.view().rounds.find(r=>r.roundId===roundId);const correct=r.tasks.filter(t=>t.correct).length,skipped=r.tasks.filter(t=>t.skipped).length;
  this.open('practice-done',{title:'Wie möchtest du weitermachen?',tag:'DEINE KURZE ÜBUNGSRUNDE',body:`<section class="v7-round-result"><h3>${esc(PRACTICE_SKILLS[r.skillId].title)}</h3><p>${correct} von ${r.tasks.length} Aufgaben in dieser Runde gelöst${skipped?`, ${skipped} für später gelassen`:''}.</p><p>Das ist eine Momentaufnahme, keine Note. Dein Kernqueststand ist unverändert.</p></section>`,foot:this.button('Ich bin jetzt sicherer','v7Safer')+this.button('Noch etwas üben','v7More')+this.button('Zurück zum Lernweg','v7Return',true)},()=>this.a.returnPractice());
  for(const [id,choice]of [['v7Safer','safer'],['v7More','more'],['v7Return','return']])document.getElementById(id).onclick=()=>{this.emit('practice_reflection',{roundId,choice});this.back=null;if(choice==='more')this.start(r.skillId);else this.a.returnPractice();};
 }
 showWork(workId,back=()=>this.a.closeWorld()){
  this.saveWorkDraft();const w=OPEN_WORK.find(w=>w.id===workId);if(!w)return;const current=this.view().works.find(x=>x.workId===workId);if(!current)this.emit('work_started',{workId});
  const value=current||{status:'started',note:'',checks:[false,false,false]};
  this.open('work',{title:w.title,tag:'PARTNERAUFTRAG · EIGENE MATHEMATISCHE IDEEN',body:`<p class="question">${esc(w.prompt)}</p><ol class="v7-partner-steps">${w.partnerSteps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p class="calm-note">${esc(w.solo)}</p><label class="v7-note-label">Deine Erklärung oder Rechenidee <small>freiwillig; auch auf Papier möglich</small><textarea id="v7WorkNote" rows="4" maxlength="1200" placeholder="Notiere deinen eigenen Gedanken …">${esc(value.note)}</textarea></label><p class="small-note">Die App bewertet deinen Text nicht. Eine gespeicherte Notiz wird lokal und im Lernstand für die Lehrkraft gespeichert. Keine Namen anderer Personen oder privaten Angaben eintragen.</p><fieldset class="v7-self-check"><legend>Selbstkontrolle: Was hast du gezeigt?</legend>${w.criteria.map((c,i)=>`<label><input type="checkbox" data-work-check="${i}" ${value.checks[i]?'checked':''}>${esc(c)}</label>`).join('')}</fieldset><details id="v7Model"><summary>Eine mögliche Lösung zum Vergleichen</summary><p>${esc(w.model)}</p><p class="small-note">Vergleiche deinen eigenen Weg. Andere begründete Lösungen können ebenfalls passen.</p></details><label class="srl-field">Deinen Stand festhalten <select id="v7WorkStatus">${Object.entries(WORK_STATUSES).map(([key,text])=>`<option value="${key}" ${value.status===key?'selected':''}>${esc(text)}</option>`).join('')}</select></label><p id="v7WorkSaved" class="small-note" role="status">Auch „bearbeitet“ ist deine Rückmeldung, kein automatisch bestätigtes Richtig.</p>`,foot:this.button('Später bearbeiten','v7WorkLater')+this.button('Speichern · zurück','v7WorkDone',true)},back);
  this.workDraft={workId,original:JSON.stringify({status:value.status,note:value.note,checks:value.checks})};
  document.getElementById('v7WorkNote').onchange=()=>this.saveWorkDraft(false);document.getElementById('v7Model').ontoggle=e=>{if(e.target.open)this.emit('work_model',{workId});};
  document.getElementById('v7WorkDone').onclick=()=>{this.saveWorkDraft();this.back=null;back();};document.getElementById('v7WorkLater').onclick=()=>{document.getElementById('v7WorkStatus').value='deferred';this.saveWorkDraft();this.back=null;back();};
 }
 saveWorkDraft(release=true){if(!this.workDraft)return;const note=document.getElementById('v7WorkNote'),status=document.getElementById('v7WorkStatus');if(note&&status){const record={status:status.value,note:note.value.slice(0,1200),checks:[...document.querySelectorAll('[data-work-check]')].map(c=>c.checked)};if(JSON.stringify(record)!==this.workDraft.original){this.emit('work_changed',{workId:this.workDraft.workId,...record});this.workDraft.original=JSON.stringify(record);const feedback=document.getElementById('v7WorkSaved');if(feedback)feedback.textContent='';}}if(release)this.workDraft=null;}
}
