/** Deliberately varied, finite decimal tasks. No runtime AI or remote requests.
 * Integers represent tenths/hundredths throughout; displayed results are finite.
 * Each concept has a close practice and a transfer/error/backwards variant.
 */
export const dec=(n,d=1)=>Number((n/d).toFixed(6)).toString();
const de=(n,d=1)=>dec(n,d).replace('.',',');
export function seedOf(value){let h=2166136261;for(const c of String(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
export function shuffleIndices(length,seed=1){const a=Array.from({length},(_,i)=>i);let s=seed>>>0;for(let i=a.length-1;i>0;i--){s=(Math.imul(s,1664525)+1013904223)>>>0;const j=s%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
export const num=(text,answer,unit='',why='')=>({type:'number',text,answer:String(answer),unit,why});
export const choice=(text,options,answer,why='')=>({type:'choice',text,options,answer,why});
export const multi=(text,options,answer,why='')=>({type:'multi',text,options,answer,why});
export const errorTask=(text,steps,answer,why)=>({type:'error',text,steps,answer,why});
export const argument=(text,items,answer,why)=>({type:'argument',text,items,answer,why});
export const match=(text,items,categories,answer,number=null)=>({type:'match',text,items,categories,answer,number,unique:new Set(answer).size===answer.length,why:number?'Die Stellen werden vom Komma aus bestimmt, nicht nach der Größe der Ziffern.':'Jede Angabe wird ihrer passenden Bedeutung oder ihrem gleichwertigen Ausdruck zugeordnet.'});
export const mark=(text,parts,answer,why)=>({type:'mark',text,parts,answer,why});
const order=(text,values,why)=>{const original=[...values];const ids=shuffleIndices(values.length,seedOf(text));return {type:'order',text,items:ids.map(i=>original[i]),answer:original.map((_,i)=>ids.indexOf(i)),why};};
const line=(text,start,end,step,answer)=>({type:'line',text,start,end,step,answer:dec(answer),why:`Die Abstände sind gleich groß. Die gesuchte Stelle hat den Wert ${de(answer)}.`});

export function makeVariant(id,mode='near',seed=0,context='Werkstatt'){
 const s=seedOf(id+':'+seed),exam=mode==='exam',n=exam?8+s%2:2+s%6,k=exam?((s>>>4)%2?9:1):2+(s>>>4)%7,w=exam?((s>>>8)%2?8:1):2+(s>>>8)%6;
 const far=mode!=='near';let t;
 switch(id){
 // No decimal notation is required before the separate naming concept.
 case 'between': t=far?choice(`Am Stall hängt ein Seil zwischen ${n} m und ${n+1} m, genau in der Mitte. Welche Beschreibung ist richtig?`,[`${n} ganze Meter und ein halber Meter`,`${n} halbe Meter`,`${n+1} ganze Meter und ein halber Meter`],0,`Zur Mitte kommen zu ${n} ganzen Metern noch ein halber Meter hinzu.`):choice(`Zwei Wegpfosten zeigen ${n} m und ${n+1} m. Welches Maß liegt genau dazwischen?`,[`${n} ganze Meter`,`${n} ganze Meter und ein halber Meter`,`${n+1} ganze Meter`],1,`Die Mitte liegt einen halben Meter hinter ${n} m.`);break;
 case 'half-name':t=far?choice(`Ein Wasserbehälter trägt das Schild ${n},5 l. Welche beiden ganzen Literzahlen liegen direkt darunter und darüber?`,[`${n} und ${n+1}`,`${n-1} und ${n}`,`${n+1} und ${n+2}`],0,`${n},5 l liegt genau zwischen ${n} l und ${n+1} l.`):num(`Eine Decke ist ${n} ganze Meter und einen halben Meter lang. Schreibe das Maß mit Komma.`,dec(n+.5),'m',`${n} und ein halb schreiben wir ${n},5.`);break;
 case 'tenths':t=far?choice('Zwei Futterbänder sind jeweils in zehn Stücke geteilt. Bei welchem Band ist jedes Stück ein Zehntel des ganzen Bandes?',['Nur wenn alle zehn Stücke gleich lang sind.','Auch wenn ein Stück viel länger als die anderen ist.','Nur wenn das ganze Band zehn Meter lang ist.'],0,'Zehntel beziehen sich auf zehn gleich große Teile desselben Ganzen.'):num(`Ein ganzes Futterband ist in zehn gleich lange Abschnitte geteilt. ${n} Abschnitte sind rot. Wie viele Zehntel des Bandes sind rot?`,n,'Zehntel',`${n} der zehn gleich großen Teile sind ${n} Zehntel.`);break;
 case 'half-tenths':t=far?choice('Eine Tierpflegerin nimmt fünf Stücke aus einem in zehn Teile geschnittenen Apfel. Wann ist das sicher ein halber Apfel?',['Wenn alle zehn Teile gleich groß sind.','Wenn nur die fünf genommenen Teile gleich groß sind.','Immer: Fünf Stücke sind stets die Hälfte.'],0,'Nur zehn gleich große Teile sichern, dass fünf davon genau die Hälfte ergeben.'):mark('Markiere einen halben Futterriegel. Alle zehn Felder sind gleich große Teile eines ganzen Riegels.',10,5,'Fünf Zehntel sind die Hälfte des ganzen Riegels.');break;
 case 'write-tenths':t=far?num(`Am Tränkebecher steht 0,${n} l. Wie viele Zehntel Liter enthält er?`,n,'Zehntel Liter',`Die ${n} direkt nach dem Komma zählt die Zehntel.`):num(`Ein Napf enthält ${n} Zehntel Liter. Schreibe die Füllmenge als Dezimalzahl.`,dec(n,10),'l',`${n} Zehntel Liter sind 0,${n} l.`);break;
 case 'places-tenths':t=far?num(`Die Zahl auf einer Messlatte hat ${n} Einer und ${k} Zehntel. Welche Zahl ist es?`,dec(n*10+k,10),'',`${n} Einer und ${k} Zehntel ergeben ${n},${k}.`):match(`Ziehe die Namen an die Ziffern des Messschilds ${n},${k}.`,[`${n}`,`${k}`],['Einer','Zehntel'],[0,1],`${n},${k}`);break;
 case 'hundred-grid':t=far?mark(`Das ganze Saatbeet besteht aus 100 gleich großen Feldern. Markiere ${n} Hundertstel für Kräuter.`,100,n,`${n} Hundertstel sind ${n} von 100 gleich großen Feldern.`):num(`Ein Beet hat 10 Reihen mit je 10 Feldern. ${n*10+k} Felder sind bepflanzt. Wie viele Hundertstel des ganzen Beets sind das?`,n*10+k,'Hundertstel',`Jedes der 100 Felder ist ein Hundertstel; es sind ${n*10+k} Hundertstel.`);break;
 case 'write-hundred':t=far?mark(`Markiere den Anteil 0,${n}${k} eines ganzen Beetes. Das ganze Feld hat 100 gleich große Kästchen.`,100,n*10+k,`0,${n}${k} sind ${n*10+k} Hundertstel.`):num(`${n*10+k} Hundertstel Liter passen in einen Probierbecher. Welche Dezimalzahl ist das?`,dec(n*10+k,100),'l',`${n*10+k} Hundertstel sind ${n} Zehntel und ${k} Hundertstel.`);break;
 case 'zero-hundred':t=far?errorTask(`Ein Kind schreibt das Maß „${n} Ganze und ${k} Hundertstel“ auf. Tippe den ersten falschen Schritt an.`,[`${n} Ganze gehören vor das Komma.`,`${k} Hundertstel kommen direkt an die erste Stelle nach dem Komma.`,`Das Schild zeigt ${n},${k}.`],1,'Die erste Stelle nach dem Komma sind Zehntel. Ohne Zehntel bleibt dort eine Null.'):num(`Der Tropfer gibt ${k} Hundertstel Liter ab. Schreibe die Menge mit Komma.`,dec(k,100),'l',`Es sind keine ganzen Liter und keine Zehntel: 0,0${k} l.`);break;
 case 'places-hundred':t=far?num(`Ein Holzschild hat ${n} Einer, ${k} Zehntel und ${w} Hundertstel. Welche Zahl entsteht?`,dec(100*n+10*k+w,100),'',`Die Ziffern stehen als ${n},${k}${w}.`):match(`Benenne jede Ziffer an ihrem Platz: ${n},${k}${w}.`,[`${n}`,`${k}`,`${w}`],['Einer','Zehntel','Hundertstel'],[0,1,2],`${n},${k}${w}`);break;
 case 'equal-zeros':t=far?multi(`Welche Schilder zeigen genau dieselbe Länge wie 0,${n} m?`,[`0,${n}0 m`,`0,0${n} m`,`0,${n}00 m`,`${n},0 m`],[0,2],`${n} Zehntel sind ${n*10} Hundertstel und ${n*100} Tausendstel; angehängte Nullen ändern den Wert nicht.`):choice(`Welche Etiketten nennen dieselbe Füllmenge?`,[`0,${n} l und 0,${n}0 l`,`0,${n} l und 0,0${n} l`,`0,${n} l und ${n},0 l`],0,'Nur die zusätzliche Null am Ende des Nachkommateils lässt den Wert unverändert.');break;
 case 'thousand':t=far?choice('Ein Hundertstelstück wird erneut in zehn gleich große Teile zerlegt. Wovon ist ein neues Teil ein Tausendstel?',['Vom ursprünglichen Ganzen.','Nur von dem Hundertstelstück.','Von zehn ursprünglichen Ganzen.'],0,'Ein neues Teil ist ein Zehntel eines Hundertstels, also ein Tausendstel des ursprünglichen Ganzen.'):num(`Eine ganze Messstrecke besteht aus 1000 gleich langen Teilen. ${n} Teile sind markiert. Wie viele Tausendstel sind markiert?`,n,'Tausendstel',`Jedes der 1000 Teile ist ein Tausendstel.`);break;
 case 'write-thousand':t=far?match(`Ordne am Schild ${n},0${k}${w} alle Stellen zu – auch die Null hat einen Platz.`,[`${n}`,'0',`${k}`,`${w}`],['Einer','Zehntel','Hundertstel','Tausendstel'],[0,1,2,3],`${n},0${k}${w}`):num(`Ein Faden misst ${n} ganze Meter und ${k} Tausendstel Meter. Schreibe das Maß.`,dec(n*1000+k,1000),'m',`${n} Ganze und ${k} Tausendstel sind ${n},00${k} m.`);break;
 case 'fraction-meaning':t=far?choice(`Beim Anteil ${n}/10: Was würde sich ändern, wenn die zehn Teile nicht gleich groß wären?`,[`Die Angabe „${n} von zehn Stücken“ wäre nicht automatisch derselbe Flächenanteil.`,'Die Bedeutung bliebe immer gleich.','Der Nenner müsste dann immer 100 sein.'],0,'Bruchteile eines Ganzen werden über gleich große Teile beschrieben.'):match(`Was bedeuten die beiden Zahlen im Bruch ${n}/10 eines ganzen Beets?`,[`${n} (oben)`,'10 (unten)'],['So viele Teile sind gemeint','So viele gleich große Teile bilden das Ganze'],[0,1]);break;
 case 'fraction-tenths':t=far?num(`Eine Futterportion ist 0,${n} kg schwer. Ihr Bruchschild lautet □/10 kg. Welche Zahl fehlt oben?`,n,'',`0,${n} kg sind ${n}/10 kg.`):num(`Auf einem Beerenkorb steht ${n}/10 kg. Schreibe dieselbe Menge als Dezimalzahl.`,dec(n,10),'kg',`${n}/10 bedeutet ${n} Zehntel.`);break;
 case 'fraction-hundred':t=far?num(`Ein Etikett zeigt 0,${n}${k} kg. Auf dem zweiten steht □/100 kg. Welche Zahl fehlt?`,n*10+k,'',`0,${n}${k} kg sind ${n*10+k} Hundertstel Kilogramm.`):num(`Eine Farbprobe wiegt ${n*10+k}/100 kg. Schreibe die Dezimalzahl.`,dec(n*10+k,100),'kg',`${n*10+k}/100 = 0,${n}${k}.`);break;
 case 'fraction-quarter':t=far?mark('Ein ganzer Garten hat 100 gleich große Felder. Markiere ein Viertel für duftende Blumen.',100,25,'Ein Viertel von 100 Feldern sind 25 Felder; der Anteil ist 0,25.'):choice('Welche Dezimalzahl beschreibt ein Viertel eines ganzen Futterkuchens?',['0,25','0,14','0,4','0,04'],0,'Ein Viertel ist 25/100, also 0,25.');break;
 case 'fraction-threequarters':t=far?num('Der Futtervorrat füllt 0,75 eines Behälters. In wie viele ganze Viertel lässt sich dieser Anteil zerlegen?',3,'Viertel','0,75 = 75/100 = 3/4.'):num('Drei von vier gleich großen Beetabschnitten sind bepflanzt. Schreibe den Anteil als Dezimalzahl.','0.75','','Drei Viertel sind 75 Hundertstel.');break;
 case 'fraction-thousand':t=far?num(`Das Bruchschild einer Probe zeigt ${n*100+k*10+w}/1000 l. Welche Dezimalzahl passt?`,dec(n*100+k*10+w,1000),'l',`Jede der drei Nachkommastellen hat ihren Platz: 0,${n}${k}${w} l.`):num(`Auf einem Schälchen steht 0,${n}${k}${w} kg. Im Bruch □/1000 fehlt die obere Zahl. Welche ist es?`,n*100+k*10+w,'',`0,${n}${k}${w} = ${n*100+k*10+w}/1000.`);break;
 // Comparing, boundaries and sparse number lines.
 case 'compare-tenths':t=far?num(`Eine Pferdebox ist ${n},${k} m lang. Eine zweite ist ${n},9 m lang. Welche Länge ist größer? Trage die größere Maßzahl ein.`,dec(n*10+9,10),'m','Bei gleichen Einern entscheidet die Zehntelstelle.'):choice(`Welcher Wasserstand ist höher?`,[`${n},${k} m`,`${n},${k-1} m`,`${n-1},9 m`],0,'Vergleiche zuerst die Einer, dann die Zehntel.');break;
 case 'compare-hundred':t=far?errorTask(`Beim Sortieren zweier Vorräte entsteht diese Begründung. Wo ist der erste Fehler?`,[`Die Vorräte wiegen 0,${n} kg und 0,${n-1}9 kg.`,`${(n-1)*10+9} ist größer als ${n}; deshalb ist 0,${n-1}9 kg schwerer.`,'Die längere Nachkommazahl ist also größer.'],1,`0,${n} = 0,${n}0; ${n*10} Hundertstel sind mehr als ${(n-1)*10+9} Hundertstel.`):choice(`Welche Futterration ist größer?`,[`0,${n-1}9 kg`,`0,${n} kg`,'Beide sind gleich groß.'],1,`0,${n} sind ${n*10} Hundertstel, nicht ${n} Hundertstel.`);break;
 case 'order-thousand':t=order('Ordne die Höhen der Kristalle aufsteigend.',[`${n},005`,`${n},05`,`${n},15`,`${n},5`],`Ergänze auf Tausendstel: 005 < 050 < 150 < 500.`);break;
 case 'limits':t=far?multi(`Ein Wagen darf höchstens ${n},50 kg tragen. Welche Ladungen sind erlaubt?`,[`${n},500 kg`,`${n},501 kg`,`${n},49 kg`,`${n+1},05 kg`],[0,2],'„Höchstens“ schließt die Grenze ein. Eine noch so kleine Überschreitung ist nicht erlaubt.'):choice(`Ein Pony trägt höchstens ${n},5 kg. Welche Ladung liegt genau auf dieser Grenze?`,[`${n},05 kg`,`${n},50 kg`,`${n},51 kg`],1,`${n},50 = ${n},5; die Null am Ende verändert nichts.`);break;
 case 'line-tenths':t=line(`Setze die Wegmarke bei ${n},${k} m. Zähle die gleich großen Abschnitte zwischen den beschrifteten Enden.`,n,n+1,.1,n+k/10);break;
 case 'line-fives':t=line(`Markiere ${de(n+(k*5)/100)} m auf der Messstrecke. Nicht jeder Strich ist beschriftet.`,n,n+.5,.05,n+(k*5)/100);break;
 case 'midpoint':t=far?num(`Ein Wegstück beginnt bei ${n},2 m und endet bei ${n},8 m. Welche Maßzahl liegt genau in seiner Mitte?`,dec(n+.5),'m',`Die Mitte ist ${n},5 m; nach links und rechts sind es je 0,3 m.`):line(`Setze den Mittelpunkt zwischen ${n} und ${n+1}.`,n,n+1,.1,n+.5);break;
 case 'round-near':t=far?choice(`Die Länge ${n},65 m soll auf Zehntel gerundet werden. Was gilt genau an der Mitte?`,[`${n},6 m`,`${n},7 m`,'Beide Ergebnisse sind beim üblichen Runden erlaubt.'],1,'Beim üblichen Runden wird ab der Mitte aufgerundet.'):num(`Runde ${n},${k}3 m auf Zehntel.`,dec(n*10+k,10),'m','Die Hundertstelziffer 3 liegt unter 5; die Zehntelstelle bleibt.');break;
 case 'round-digit':t=far?num(`Ein Maß beträgt ${n},${k}48 m. Runde direkt auf Hundertstel – ohne zuerst auf Tausendstel zu verändern.`,dec(n*100+k*10+5,100),'m','Die Tausendstelziffer 8 führt zum Aufrunden der Hundertstelstelle.'):num(`Runde ${n},${k}27 kg auf Hundertstel.`,dec(n*100+k*10+3,100),'kg','Die Tausendstelziffer 7 erhöht die Hundertstelziffer um eins.');break;
 case 'round-carry':t=far?errorTask(`Beim Runden von ${n},996 auf Hundertstel wurden diese Schritte notiert. Markiere den ersten Fehler.`,['Die Tausendstelziffer ist 6; ich runde auf.',`Aus ${n},99 wird ${n},100.`,'Der Übertrag wurde berücksichtigt.'],1,`99 Hundertstel plus ein Hundertstel ergeben einen weiteren Einer: ${n+1},00.`):num(`Runde ${n},98 m auf Zehntel.`,n+1,'m',`Die Zehntelziffer 9 erhält einen Übertrag: ${n+1},0 m.`);break;
 case 'estimate':t=far?choice(`Für eine Ladung ist ein Grenzwert von ${n+3} kg vorgeschrieben. Der Überschlag ergibt ungefähr ${n+3} kg. Darfst du ohne genaue Rechnung sagen: „Die Ladung ist sicher erlaubt“?`,['Nein. Die tatsächliche Last kann knapp oberhalb der Grenze liegen.','Ja. Ungefähr reicht bei einer Höchstgrenze immer.','Ja. Runden macht jede Last kleiner.'],0,'Ein Überschlag schätzt ab. Bei einer Grenze ist eine genaue Prüfung nötig.'):num(`Schätze ${n},2 kg + ${k},1 kg, indem du beide Summanden zuerst auf ganze Kilogramm rundest.`,n+k,'kg',`${n},2 ≈ ${n} und ${k},1 ≈ ${k}; zusammen ungefähr ${n+k} kg.`);break;
 // Units. Unit transformations are taught separately from numerical calculation.
 case 'metres-cm':t=far?num(`Ein Zaunpfosten misst ${n},0${k} m. Wie viele Zentimeter sind das?`,100*n+k,'cm',`Ein Meter sind 100 cm: ${n*100} cm + ${k} cm.`):num(`Ein Stallbrett ist ${n},${k} m lang. Gib die Länge in Zentimetern an.`,100*n+10*k,'cm','Die Maßzahl wird beim Wechsel von m zu cm mit 100 multipliziert.');break;
 case 'cm-metres':t=num(`Die ${far?'kurze Stalltür':'Messlatte'} misst ${far?n*100+k:n*100+10*k} cm. Wie viele Meter sind das?`,dec(far?n*100+k:n*100+10*k,100),'m','Hundert Zentimeter bilden einen Meter.');break;
 case 'kilometres':t=far?num(`Zum Waldlager sind es ${n*1000+k*10} m. Schreibe die Strecke in Kilometern.`,dec(n*1000+k*10,1000),'km','1000 m = 1 km. Behalte die Null als Platzhalter.'):num(`Die Postkutsche fährt ${n},${k} km. Wie viele Meter sind das?`,n*1000+k*100,'m','1 km = 1000 m.');break;
 case 'kg-grams':t=num(`Das ${far?'Päckchen Heusamen':'Futterpaket'} wiegt ${far?`0,0${k}`:`${n},${k}`} kg. Wie viele Gramm sind das?`,far?k*10:n*1000+k*100,'g','1 kg = 1000 g; auch kleine Kilogrammwerte brauchen alle Stellen.');break;
 case 'grams-kg':t=num(`${far?n*1000+k:k*100} g Körner werden abgefüllt. Gib die Masse in Kilogramm an.`,dec(far?n*1000+k:k*100,1000),'kg','Gramm werden für Kilogramm durch 1000 geteilt.');break;
 case 'litres-ml':t=num(`Der Messbecher enthält ${far?`0,0${k}`:`${n},${k}`} l. Gib dieselbe Füllmenge in Millilitern an.`,far?k*10:n*1000+k*100,'ml','1 l = 1000 ml.');break;
 case 'ml-litres':t=num(`${far?n*1000+k:k*100} ml Wasser kommen in die Tränke. Wie viele Liter sind das?`,dec(far?n*1000+k:k*100,1000),'l','1000 ml ergeben einen Liter.');break;
 case 'time-half':t=far?errorTask('Ein Pferd wurde 1,5 Stunden versorgt. Wo liegt der erste Fehler in dieser Umrechnung?',['1,5 h sind 1 h und 0,5 h.','0,5 h sind 50 Minuten.','Insgesamt waren es 110 Minuten.'],1,'Eine Stunde hat 60 Minuten. Eine halbe Stunde hat 30 Minuten, nicht 50.'):num(`Die Tierpflege dauert ${n},5 h. Wie viele Minuten sind das?`,n*60+30,'min',`${n} Stunden sind ${n*60} Minuten; die halbe Stunde ergänzt 30 Minuten.`);break;
 case 'time-quarter':t=far?num(`Der Hufschmied arbeitet ${n} h und 45 min. Schreibe die Dauer in Dezimalstunden.`,dec(n+.75),'h','45 min sind drei Viertel einer Stunde, also 0,75 h.'):num(`Die Fütterung und Pflege dauern ${n},25 h. Wie viele Minuten sind das?`,n*60+15,'min','0,25 h sind 15 Minuten; eine Stunde hat 60 Minuten.');break;
 case 'money':t=far?num(`Die Marktwaage zeigt einen Preis von ${n*100+k} Cent. Schreibe ihn in Euro.`,dec(n*100+k,100),'€','100 Cent = 1 Euro. Die Centzahl unter 10 braucht eine Null davor.'):num(`Ein Heubündel kostet ${n},0${k} €. Wie viele Cent sind das?`,n*100+k,'Cent','Euro und Cent werden im Verhältnis 1 : 100 umgerechnet.');break;
 case 'square-units':t=far?errorTask('Ein Schild rechnet eine Beetfläche um. Welcher Schritt ist zuerst falsch?',['1 m = 10 dm.','Darum gilt 1 m² = 10 dm².','Also gilt 0,5 m² = 5 dm².'],1,'Bei Flächen werden beide Richtungen umgerechnet: 10 · 10 = 100.'):num(`Das Stallfenster hat eine Fläche von ${n},${k} m². Wie viele dm² sind das?`,n*100+k*10,'dm²','1 m² = 100 dm², weil ein Meterquadrat 10 · 10 Dezimeterquadrate enthält.');break;
 case 'cube-units':t=far?num(`Ein Futterkasten hat ein Volumen von ${n*1000+k*10} dm³. Wie viele m³ sind das?`,dec(n*1000+k*10,1000),'m³','In einen Kubikmeter passen 10 · 10 · 10 = 1000 Kubikdezimeter.'):num(`Ein Speicher fasst ${n},${k} m³. Wie viele dm³ sind das?`,n*1000+k*100,'dm³','1 m³ = 1000 dm³.');break;
 case 'cube-litre':t=far?num(`Die Tränke enthält ${n*1000+k*100} l. Gib das Volumen in Kubikmetern an.`,dec(n*10+k,10),'m³','1 m³ = 1000 dm³ = 1000 l.'):num(`Ein Wassertank fasst ${n},${k} dm³. Wie viele Liter sind das?`,dec(n*10+k,10),'l','1 dm³ ist genau 1 l; die Maßzahl bleibt gleich.');break;
 // Addition: missing addends, carries, units and structurally useful grouping.
 case 'add-tenths':t=far?num(`Im Futterkorb liegen ${n},2 kg. Mit einem weiteren Beutel sollen es ${n+1},8 kg sein. Wie schwer muss der Beutel sein?`,'1.6','kg',`${n},2 + 1,6 = ${n+1},8. Suche die Ergänzung.`):num(`Zwei Körbe enthalten ${n},2 kg und ${k},3 kg Äpfel. Wie viel ist es zusammen?`,dec(n+k+.5),'kg','Addiere Einer zu Einern und Zehntel zu Zehnteln.');break;
 case 'add-align':t=far?errorTask(`Die Holzhelferin addiert ${n},4 m und 0,26 m. Wo entsteht der erste Fehler?`,[`${n},4 wird zu ${n},40 ergänzt.`,'Die Einerstelle von 0,26 wird unter die Zehntelstelle geschrieben.','Danach werden die Ziffern spaltenweise addiert.'],1,'Gleiche Stellen müssen untereinander stehen: Komma unter Komma.'):num(`Ein Seilstück misst ${n},4 m, ein zweites 0,26 m. Wie lang sind sie zusammen?`,dec(n*100+66,100),'m',`${n},40 + 0,26 = ${n},66.`);break;
 case 'add-carry':t=far?num(`Ein Napf und ein Zusatzbeutel wiegen zusammen ${n+1},05 kg. Im Napf sind ${n},68 kg. Wie schwer ist der Beutel?`,'0.37','kg',`${n},68 + 0,37 = ${n+1},05; Zehntel und Hundertstel werden gebündelt.`):num(`Für die Tiere kommen ${n},68 kg und ${k},57 kg Futter zusammen. Wie viel ist das?`,dec((n+k)*100+125,100),'kg','15 Hundertstel werden zu 1 Zehntel und 5 Hundertsteln. Auch bei den Zehnteln entsteht ein Übertrag.');break;
 case 'add-thousand':t=far?num(`Zwei Farbreste ergeben ${n},105 l. Der erste enthält ${n},078 l. Wie viel enthält der zweite?`,'0.027','l','0,078 + 0,027 = 0,105.'):num(`Die Werkstatt mischt ${n},078 l und 0,046 l Farbe. Wie viel ergibt das?`,dec(n*1000+124,1000),'l','78 Tausendstel plus 46 Tausendstel sind 124 Tausendstel.');break;
 case 'add-group':t=far?argument('Ordne nur die drei passenden Denkschritte für 1,75 + 0,6 + 0,25. Eine Karte passt nicht.',['1,75 und 0,25 zusammennehmen.','Diese beiden Summanden ergeben 2.','Zu 2 noch 0,6 addieren: 2,6.','Beim Addieren darf ich jeden Summanden verdoppeln.'],[0,1,2],'Man darf Summanden umordnen und zusammenfassen; ihren Wert darf man nicht verändern.'):num(`Addiere für die Futterküche geschickt: ${n},75 kg + 0,6 kg + 0,25 kg.`,dec(n+1.6),'kg','0,75 und 0,25 ergänzen sich zu 1.');break;
 case 'add-units':t=far?num(`Ein Heuvorrat soll ${n+1} kg wiegen. Schon da sind ${n} kg und ${k*100} g. Wie viele Gramm fehlen?`,1000-k*100,'g','Rechne den fehlenden Teil eines Kilogramms in Gramm.'):num(`Ein Sack enthält ${n},2 kg, ein zweiter ${k*100} g. Wie viele Kilogramm sind es zusammen?`,dec(n*10+2+k,10),'kg','Zuerst g in kg umrechnen, dann gleiche Größen addieren.');break;
 // Subtraction with inverse problems and explicit error analysis.
 case 'subtract-basic':t=far?num(`Nach dem Holzhacken sind noch ${n},3 m Stamm übrig. Abgesägt wurden ${k},2 m. Wie lang war der Stamm vorher?`,dec(n+k+.5),'m','Vorheriger Vorrat = Rest + verbrauchte Menge.'):num(`Ein Stamm ist ${n+k},8 m lang. ${k},3 m werden abgesägt. Wie viel bleibt?`,dec(n+.5),'m','Ziehe Einer und Zehntel stellenweise voneinander ab.');break;
 case 'subtract-exchange':t=far?errorTask(`Wo liegt bei ${n},42 − 0,18 der erste falsche Schritt?`,['Bei den Hundertsteln reichen 2 nicht für 8.','Ich tausche ein Zehntel in 10 Hundertstel.',`Jetzt stehen unverändert 4 Zehntel und 12 Hundertstel da.`],2,'Nach dem Tausch bleiben nur 3 Zehntel übrig. Die Gesamtmenge darf sich nicht ändern.'):num(`Vom Seil mit ${n},42 m werden 0,18 m abgeschnitten. Wie viel bleibt?`,dec(n*100+24,100),'m','Ein Zehntel wird zu zehn Hundertsteln getauscht: 12 − 8 = 4.');break;
 case 'subtract-whole':t=far?num(`Von einer Rolle wurden 0,76 m abgeschnitten. Es bleiben ${n},24 m. Wie lang war die Rolle anfangs?`,n+1,'m','Rest plus abgeschnittene Länge ergibt den Anfangsvorrat.'):num(`Ein ganzzahliges Seilmaß von ${n} m wird um 0,76 m gekürzt. Wie viel bleibt?`,dec(n*100-76,100),'m',`Schreibe ${n},00 und entbündele über die Nullstellen.`);break;
 case 'subtract-thousand':t=far?num(`In der Schmiede wurde ein Draht um 0,086 m gekürzt. Danach ist er ${n},014 m lang. Wie lang war er vorher?`,dec(n*1000+100,1000),'m','Die Umkehrung der Subtraktion ist die Addition.'):num(`Ein Draht von ${n},103 m wird um 0,087 m gekürzt. Wie viel bleibt?`,dec(n*1000+16,1000),'m','103 Tausendstel minus 87 Tausendstel sind 16 Tausendstel.');break;
 case 'missing':t=far?num(`In einem Fass waren einige Liter. ${n},65 l werden entnommen; ${k},35 l bleiben. Wie viele Liter waren anfangs darin?`,n+k+1,'l','Der Anfang ist entnommene Menge plus Rest.'):num(`Das Fass soll ${n+2},5 l enthalten. Schon da sind ${n},75 l. Wie viel fehlt?`,'1.75','l','Gesuchte Ergänzung = Zielmenge − vorhandene Menge.');break;
 case 'subtract-proof':t=far?argument('Wähle und ordne die drei Schritte, die 6,2 − 2,85 = 3,35 prüfen. Eine Karte ist ungeeignet.',['Die Probe zur Subtraktion ist eine Addition.','Addiere 3,35 und 2,85.','Die Summe ist 6,20; das ist die Anfangsmenge.','Teile 6,2 durch 3,35.'],[0,1,2],'Rest plus entnommene Menge muss wieder den Anfang ergeben.'):choice(`Welche Probe prüft ${n+3},6 − ${n},25 = 3,35?`,[`3,35 + ${n},25 = ${n+3},6`,`3,35 − ${n},25 = ${n+3},6`,`${n+3},6 + ${n},25 = 3,35`],0,'Die Subtraktion wird durch die Addition rückgängig gemacht.');break;
 case 'two-subtractions':t=far?num(`Nach zwei Entnahmen von 0,65 l und 0,85 l bleiben ${n},5 l. Wie viel war vorher im Fass?`,n+2,'l','Addiere die beiden Entnahmen zum Rest zurück.'):num(`Von ${n+3} m Seil gehen ${n},65 m und 0,85 m ab. Wie viel bleibt?`,'1.5','m','Erst beide Entnahmen zusammenfassen oder nacheinander abziehen.');break;
 // Multiplication, scalar effect and area meaning.
 case 'multiply-repeat':t=far?num(`Ein Stall braucht je Box 0,3 kg Streu. ${n} gleiche Boxen bekommen Streu. Wie viel ist das zusammen?`,dec(n*3,10),'kg',`${n} gleiche Mengen von 0,3 kg werden addiert.`):num(`${n} Tiere erhalten jeweils 0,2 kg Futter. Wie viel Futter ist das?`,dec(n*2,10),'kg','Anzahl mal gleiche Portionsgröße ergibt die Gesamtmenge.');break;
 case 'multiply-integer':t=far?num(`Für ${n} gleiche Futterkörbe stehen zusammen ${de(n*45,100)} kg bereit. Welche Portionsmasse passt in die Lücke: ${n} · □ = ${de(n*45,100)}?`,'0.45','kg',`Prüfe: ${n} · 0,45 = ${de(n*45,100)}.`):num(`${n} Pferde bekommen je 0,65 kg Hafer. Wie viel Hafer brauchst du?`,dec(n*65,100),'kg','Berechne die Anzahl gleicher Portionen.');break;
 case 'multiply-half':t=far?num(`Nach dem Halbieren beträgt eine Portion ${n},35 kg. Wie schwer war die ganze Portion?`,dec(2*n+.7),'kg','Die ganze Portion ist das Doppelte der halben.'):num(`Ein Futtersack wiegt ${n*2},8 kg. Die Hälfte ist für die Ponys bestimmt. Wie viel ist das?`,dec(n+.4),'kg','Mit 0,5 multiplizieren bedeutet halbieren.');break;
 case 'multiply-decimal':t=far?errorTask(`Bei ${n},2 · 0,3 entsteht diese Rechnung. Finde den ersten Fehler.`,[`${n*10+2} · 3 = ${(n*10+2)*3}.`,`Die Faktoren haben zusammen nur eine Nachkommastelle.`,`Das Ergebnis ist ${de((n*10+2)*3,10)}.`],1,'Jeder Faktor hat eine Nachkommastelle. Das Produkt erhält zusammen zwei.'):num(`Ein kleiner Futterplan nimmt das 0,3-Fache von ${n},2 kg. Welche Masse ergibt sich?`,dec((n*10+2)*3,100),'kg','Zehntel mal Zehntel ergeben Hundertstel.');break;
 case 'rectangle':t=far?num(`Ein rechteckiger Pferdeauslauf ist ${n} m breit und ${n+1} m lang. Wie groß ist seine Fläche?`,n*(n+1),'m²','Fläche = Länge · Breite. Das Ergebnis wird in Quadratmetern angegeben.'):num(`Ein Saatfeld ist ${n} m lang und ${k} m breit. Berechne die Fläche.`,n*k,'m²','Zähle Reihen und Spalten von Quadratmetern.');break;
 case 'rectangle-decimal':t=far?mark('Das ganze Quadrat ist 1 m × 1 m und hat 100 gleich große Kästchen. Markiere die Fläche eines Rechtecks von 0,4 m × 0,6 m. Es genügt, die richtige Anzahl von Kästchen zu markieren.',100,24,'4 · 6 = 24 Kästchen, jedes 0,01 m²: zusammen 0,24 m².'):num(`Ein rechteckiges Beet ist ${n},2 m lang und 0,4 m breit. Wie groß ist seine Fläche?`,dec((n*10+2)*4,100),'m²','Multipliziere die Seitenlängen; die Einheit ist m².');break;
 case 'multiply-smaller':t=far?multi('Für eine positive Futtermenge x: Welche Aussagen stimmen?',['x · 0,8 ist kleiner als x.','x · 1 ist gleich x.','x · 1,2 ist kleiner als x.','Multiplizieren macht immer größer.'],[0,1],'Ein positiver Faktor unter 1 verkleinert, der Faktor 1 lässt unverändert.'):choice(`Eine Portion wiegt ${n},6 kg. Was gilt für das 0,4-Fache?`,[`Es ist weniger als ${n},6 kg.`,`Es ist genau ${n},6 kg.`,`Es ist mehr als ${n},6 kg.`],0,'0,4 ist ein positiver Faktor unter 1.');break;
 case 'unit-price':t=far?num(`0,5 kg Spezialfutter kosten ${n},20 Taler. Was kostet 1 kg?`,dec(2*n+.4),'Taler','Ein Kilogramm ist doppelt so viel wie ein halbes Kilogramm.'):num(`Ein Meter Stallband kostet ${n},40 Taler. Du kaufst ${k} m. Was kostet das?`,dec((n*100+40)*k,100),'Taler','Preis je Meter mal Länge ergibt den Gesamtpreis.');break;
 case 'times-ten':t=far?num(`Nach dem Multiplizieren mit 10 zeigt eine Waage ${n},6. Welche Zahl stand vorher in der Rechnung?`,dec(n*10+6,100),'','Gesucht ist die Zahl, deren Ziffern durch · 10 einen zehnfachen Stellenwert bekommen.'):num(`Zehn Beutel enthalten je 0,${n}${k} kg. Wie viel ist das zusammen?`,dec(n*10+k,10),'kg','Beim Multiplizieren mit 10 wird jede Ziffer eine Stelle mehr wert.');break;
 case 'times-hundred':t=far?errorTask('Wo liegt der erste Fehler beim Hundertfachen von 0,07?',['Mit 100 wird jede Stelle hundertmal so viel wert.','0,07 · 100 = 0,0700.','Das Ergebnis ist gleich geblieben.'],1,'Angehängte Nullen ändern den Wert nicht. 0,07 · 100 = 7.'):num(`100 Samenpäckchen wiegen je 0,0${k} kg. Wie schwer sind sie zusammen?`,k,'kg','Hundert mal ein Hundertstel ergibt einen Einer.');break;
 case 'multiply-quarter':t=far?num(`Ein Viertel eines Vorrats beträgt ${n},25 kg. Wie groß ist der ganze Vorrat?`,n*4+1,'kg','Vier gleiche Viertel ergeben den ganzen Vorrat.'):num(`Ein Futtersack enthält ${n*4+2} kg. Ein Viertel davon geht an die Ponys. Wie viel ist das?`,dec(n+.5),'kg','Mit 0,25 multiplizieren bedeutet ein Viertel nehmen.');break;
 case 'distribute':t=far?errorTask(`Eine Rechnung zur Mühle wird zerlegt. Wo ist der erste Fehler?`,[`${n} · (1 + 0,4) soll berechnet werden.`,`Das ist ${n} · 1 + 0,4.`,`Das Ergebnis sei ${n},4.`],1,'Beide Summanden in der Klammer müssen mit der Anzahl multipliziert werden.'):num(`Die Mühle benötigt ${n} Pakete mit jeweils 1,4 kg Inhalt. Rechne über ${n} · (1 + 0,4).`,dec(n*14,10),'kg','Verteile den Faktor auf beide Summanden: n · 1 + n · 0,4.');break;
 case 'product-then-double':t=far?num(`Zwei gleiche Futterautomaten geben zusammen ${de(n*12,10)} kg ab. Jeder läuft ${n} Mal mit derselben Portion. Wie viel gibt ein Automat insgesamt ab?`,dec(n*6,10),'kg','Zwei gleiche Geräte haben gleiche Gesamtmengen. Halbiere die Gesamtmenge beider Geräte.'):num(`Ein Futterautomat gibt ${n} Portionen zu je 0,6 kg ab. Ein zweiter arbeitet genau gleich. Wie viel geben beide zusammen ab?`,dec(n*12,10),'kg','Erst n · 0,6 berechnen, dann das Ergebnis verdoppeln.');break;
 // Division: distinguish amount per share from number of shares.
 case 'divide-equal':t=far?num(`${n} Ponys erhalten jeweils 0,35 kg Futter. Wie viel wurde insgesamt gerecht verteilt?`,dec(n*35,100),'kg','Die Rückrechnung zur Division ist Anzahl · Portionsgröße.'):num(`${de(n*65,100)} kg Futter werden auf ${n} Tiere gleich verteilt. Wie viel bekommt jedes Tier?`,'0.65','kg',`${n} · 0,65 kg ergibt die Gesamtmenge.`);break;
 case 'divide-leftover':t=far?num(`Ein Krug enthält ${n} l. Er wird auf ${n*4} gleich große Portionen verteilt. Wie viel enthält jede?`,'0.25','l','Jeder ganze Liter wird in vier Viertelliter zerlegt.'):num(`${n*2+1} l Saft werden auf 2 Tiere gleich verteilt. Wie viel erhält jedes?`,dec(n+.5),'l','Ein übrig gebliebener ganzer Liter wird in zwei halbe Liter geteilt.');break;
 case 'divide-proof':t=far?argument('Prüfe 5,4 : 6 = 0,9. Ordne nur die drei passenden Schritte.',['Die Probe nutzt die Multiplikation.','Rechne 6 · 0,9.','Es ergibt 5,4; das ist die verteilte Menge.','Rechne 6 + 0,9.'],[0,1,2],'Anzahl mal Portionsgröße muss die Gesamtmenge ergeben.'):choice(`Welche Rechnung prüft ${de(n*7,10)} : ${n} = 0,7?`,[`${n} · 0,7 = ${de(n*7,10)}`,`${n} + 0,7 = ${de(n*7,10)}`,`${n} : 0,7 = ${de(n*7,10)}`],0,'Multiplikation und Division sind Umkehroperationen.');break;
 case 'portion-tenths':t=far?num(`${n} Flaschen mit je 0,4 l sind voll. Welche Gesamtmenge wurde abgefüllt?`,dec(n*4,10),'l','Portionsanzahl mal Füllmenge ergibt den Inhalt des Kessels.'):num(`Im Kessel sind ${de(n*4,10)} l. Jede Flasche fasst 0,4 l. Wie viele Flaschen werden voll?`,n,'Flaschen','Rechne beide Mengen in Zehntellitern; dann bestimme die Anzahl.');break;
 case 'portion-hundred':t=far?num(`Ein Kessel enthält ${de(n*75+25,100)} l. Ein Becher fasst 0,75 l. Wie viele Becher kannst du vollständig füllen?`,n,'volle Becher','Nur vollständig gefüllte Becher zählen. Ein Rest von 0,25 l reicht nicht für einen weiteren.'):num(`${de(n*75,100)} l Trank werden in Portionen von je 0,75 l abgefüllt. Wie viele Portionen sind das?`,n,'Portionen','Beide Maßzahlen können in Hundertsteln angegeben werden.');break;
 case 'divide-small':t=far?multi('Eine positive Menge x wird durch eine Zahl geteilt. Welche Aussagen sind richtig?',['x : 0,5 ist größer als x.','x : 1 ist gleich x.','x : 2 ist größer als x.','Teilen macht immer kleiner.'],[0,1],'Halb so große Portionen ergeben doppelt so viele Portionen.'):num(`Wie viele Portionen zu je 0,5 l passen in ${n} l Wasser?`,n*2,'Portionen','In jeden ganzen Liter passen zwei halbe Liter.');break;
 case 'divide-ten':t=far?num(`Ein Zehntel des Vorrats wiegt 0,${n}${k} kg. Wie viel wiegt der ganze Vorrat?`,dec(n*10+k,10),'kg','Zehn gleich große Zehntel ergeben das Ganze.'):num(`${n},${k} kg Streu werden in 10 gleiche Beutel geteilt. Wie viel wiegt jeder?`,dec(n*10+k,100),'kg','Jede Ziffer wird beim Teilen durch 10 eine Stelle weniger wert.');break;
 case 'divide-hundred':t=far?num(`Ein Hundertstel des Tranks sind 0,00${k} l. Wie groß ist die Gesamtmenge?`,dec(k,10),'l','Hundert mal die kleine Portion ist die Gesamtmenge.'):num(`${n},${k} l werden auf 100 Fläschchen gleich verteilt. Wie viel kommt in jedes?`,dec(n*10+k,1000),'l','Teilen durch 100 entspricht zweimaligem Teilen durch 10.');break;
 case 'divide-scale':t=far?errorTask(`Eine Trankrechnung wird umgeformt. Wo liegt der erste Fehler?`,[`${n},2 : 0,2 soll vereinfacht werden.`,`Nur der Divisor wird mit 10 multipliziert: ${n},2 : 2.`,'Der Quotient bleibt dadurch gleich.'],1,'Damit der Quotient gleich bleibt, müssen beide Zahlen mit derselben von null verschiedenen Zahl multipliziert werden.'):choice(`Welche Rechnung hat denselben Wert wie ${n},2 : 0,02?`,[`${n*100+20} : 2`,`${n*10+2} : 2`,`${n},2 : 2`],0,'Dividend und Divisor wurden beide mit 100 multipliziert.');break;
 case 'need-minus-stock':t=far?num(`${n} Tiere bekommen je 0,4 l. Es müssen noch 0,3 l nachgefüllt werden. Wie viel war bereits in der Tränke?`,dec(n*4-3,10),'l','Vorhanden = Gesamtbedarf − fehlende Menge.'):num(`${n} Becher brauchen je 0,4 l. Im Krug sind ${de(n*4-5,10)} l. Wie viel fehlt?`,'0.5','l','Erst Anzahl · Portionsgröße, dann den vorhandenen Vorrat abziehen.');break;
 case 'model':t=far?choice(`Für ${n} Pferde stehen Futterrationen von je 0,65 kg auf dem Plan. Gesucht ist die Gesamtmasse. Welche Rechnung beschreibt das?`,[`${n} · 0,65`,`${n} : 0,65`,`${n} + 0,65`],0,'Gleiche Rationen werden entsprechend der Tieranzahl vervielfacht.'):num(`${n} Festgäste trinken je 0,35 l. Wie viel Getränk muss bereitstehen?`,dec(n*35,100),'l','Anzahl der Gäste mal Getränkemenge je Gast.');break;
 case 'one-discount':t=far?errorTask(`Für ${n} Futterkisten zu je 2,40 Talern gibt es einmalig 0,80 Taler Rabatt. Wo liegt der erste Fehler?`,[`${n} Kisten kosten ohne Rabatt ${n} · 2,40 Taler.`,`Ich ziehe von jeder Kiste 0,80 Taler ab.`,`Ich rechne ${n} · (2,40 − 0,80).`],1,'Ein einmaliger Rabatt wird nur einmal vom Gesamtpreis abgezogen.'):choice(`Für ${n} gleiche Lampen zu je 2,40 Talern gilt ein Rabatt von 0,80 Talern auf den ganzen Einkauf. Welche Rechnung passt?`,[`${n} · 2,40 − 0,80`,`${n} · (2,40 − 0,80)`,`${n} + 2,40 − 0,80`],0,'Zuerst der Gesamtpreis, dann der einmalige Rabatt.');break;
 case 'operations':t=far?num(`Eine Bestellung kostet nach einmalig 0,70 Taler Rabatt genau ${de(n*125-70,100)} Taler. Jede Lampe kostet 1,25 Taler. Wie viele Lampen wurden gekauft?`,n,'Lampen','Rechne rückwärts: Rabatt wieder addieren, dann durch den Stückpreis teilen.'):num(`Du kaufst ${n} Lampen zu je 1,25 Talern und eine Rolle Band für 0,70 Taler. Was kostet alles zusammen?`,dec(n*125+70,100),'Taler','Erst die Multiplikation, dann die Addition.');break;
 case 'plan-leftover':t=far?num(`Nach dem Fest werden aus dem Restband ${n} Schleifen mit je 0,45 m hergestellt. Beim Fest wurden 1,2 m verbraucht. Wie lang war die Rolle anfangs?`,dec(n*45+120,100),'m','Anfang = verwendetes Band + Band für alle Schleifen.'):num(`Nach dem Schmücken bleiben ${de(n*45,100)} m Band. Jede Schleife braucht 0,45 m. Wie viele Schleifen entstehen?`,n,'Schleifen','Teile die Restlänge durch die Länge einer Schleife.');break;
 default:throw new Error('Kein Aufgabenmodell für '+id);
 }

 // Assessment-only representations, not copies of fixed practice cards.
 if(exam){
  switch(id){
   case 'tenths':t=mark(`Ein ganzes Windband ist in zehn gleich große Felder geteilt. Färbe ${n} Zehntel.`,10,n,`${n} von zehn gleich großen Teilen entsprechen ${n} Zehnteln.`);break;
   case 'half-tenths':t=choice('Der Wegwächter hat zehn gleich große Stücke eines ganzen Brots. Er legt die Hälfte zur Seite. Wie viele Zehntel des ganzen Brots sind das?',['5 Zehntel','2 Zehntel','10 Zehntel'],0,'Fünf der zehn gleich großen Teile bilden die Hälfte.');break;
   case 'thousand':t=num('Ein ganzer Wegplan wird in 100 gleich große Felder geteilt. Jedes Feld erhält zehn gleich große Unterfelder. Wie viele Unterfelder gehören zum ursprünglichen Ganzen?',1000,'Unterfelder','100 · 10 = 1000 gleich große Teile des ursprünglichen Ganzen.');break;
   case 'fraction-meaning':t=choice('Ein Wegplan zeigt den Anteil 3/8 einer ganzen Fläche. Wofür steht die 8 unten?',['Acht gleich große Teile bilden das Ganze.','Acht Teile sind markiert.','Die ganze Fläche ist immer acht Meter lang.'],0,'Der Nenner nennt, in wie viele gleich große Teile das Ganze zerlegt wird.');break;
   case 'fraction-quarter':t=errorTask('Auf dem Frachtplan steht 1/4 eines ganzen Feldes. Welche Zeile ist zuerst falsch?',['Das Ganze kann in vier gleich große Teile zerlegt werden.','Ein solcher Teil ist gemeint.','Die 4 steht unten; deshalb schreibe ich 0,4.'],2,'Ein Viertel entspricht 25/100, also 0,25.');break;
   case 'fraction-threequarters':t=choice('Bei einer ganzen Fläche sind 0,75 markiert. Welches Bruchschild beschreibt genau den markierten Anteil?',['3/4','7/5','3/5','1/4'],0,'75 Hundertstel bilden drei gleich große Viertel.');break;
   case 'time-half':t=choice(`Die Wachzeit beträgt ${n},5 h. Welcher Eintrag in Stunden und Minuten stimmt?`,[`${n} h 30 min`,`${n} h 50 min`,`${n+1} h 5 min`],0,'Die halbe Stunde entspricht 30 Minuten.');break;
   case 'square-units':t=num(`Die quadratische Sichtfläche einer Wegtafel hat ${n},0${k} dm² Fläche. Wie viele cm² sind das?`,n*100+k,'cm²','1 dm² = 100 cm². Die Maßzahl wird mit 100 multipliziert.');break;
   case 'add-group':t=argument(`Begründe die geschickte Addition ${n},85 + 0,7 + 0,15. Ordne drei passende Gedanken.`,[`${n},85 und 0,15 können zuerst zusammengefasst werden.`,`Diese beiden Summanden ergeben ${n+1}.`,`Mit 0,7 entsteht ${n+1},7.`,'Die Kommata dürfen vor dem Rechnen entfernt werden.'],[0,1,2],'Vertauschen und Zusammenfassen verändern eine Summe nicht.');break;
   case 'subtract-proof':t=argument(`Prüfe ${n},1 − 0,85 = ${n-1},25 mit drei passenden Schritten.`,['Die Umkehrung der Subtraktion ist die Addition.',`Addiere ${n-1},25 und 0,85.`,`Das ergibt wieder die Anfangsmenge ${n},10.`,'Die Probe multipliziert Rest und Verbrauch.'],[0,1,2],'Der Rest und die entnommene Menge ergänzen sich zur Anfangsmenge.');break;
   case 'multiply-smaller':t=choice(`Eine positive Vorratsmenge von ${n},8 kg wird mit 0,9 multipliziert. Was kann ohne Ausrechnen sicher gesagt werden?`,['Das Ergebnis liegt zwischen 0 kg und der Ausgangsmenge.','Das Ergebnis ist größer als die Ausgangsmenge.','Das Ergebnis ist genauso groß wie die Ausgangsmenge.'],0,'Der Faktor ist positiv und kleiner als 1.');break;
   case 'rectangle-decimal':t=num(`Eine rechteckige Wegtafel misst 0,${n} m mal 0,${k} m. Wie groß ist die Fläche?`,dec(n*k,100),'m²','Zehntel mal Zehntel ergeben Hundertstel des Meterquadrats.');break;
   case 'times-hundred':t=num(`Nach dem Vervielfachen mit 100 lautet eine Maßzahl ${n},${k}. Welche Maßzahl stand zuvor auf dem Plan?`,dec(n*10+k,1000),'','Gesucht ist die Zahl, deren Hundertfaches den angezeigten Wert hat.');break;
   case 'divide-proof':t=multi(`Welche Rechnungen sind passende Multiplikationsproben für ${de(n*4,10)} : ${n} = 0,4?`,[`${n} · 0,4 = ${de(n*4,10)}`,`0,4 · ${n} = ${de(n*4,10)}`,`${n} + 0,4 = ${de(n*4,10)}`,`${de(n*4,10)} · ${n} = 0,4`],[0,1],'Beide Faktoren dürfen vertauscht werden; ihr Produkt muss der ursprünglichen Menge entsprechen.');break;
   case 'divide-small':t=choice(`Wie verändert sich die Anzahl der Portionen aus ${n} l, wenn jede Portion statt 1 l nur 0,5 l enthält?`,['Die Anzahl verdoppelt sich.','Die Anzahl halbiert sich.','Die Anzahl bleibt gleich.'],0,'In jeden ganzen Liter passen zwei halbe Liter.');break;
  }
 }
 if(id==='fraction-meaning')t.why='Die untere Zahl nennt die gleich großen Teile des Ganzen; die obere Zahl zählt die gemeinten Teile.';
 t.lesson=id;t.skill=id;t.stage=mode;t.variantSeed=seed;t.strategy=(t.type==='error'?'Fehler finden':t.type==='argument'?'Begründen':far?'Übertragen':'Festigen');
 t.hint=t.hint||'Überlege, was gegeben und was gesucht ist. Nutze bei Bedarf das Wissen und ein anderes Beispiel zu diesem Gedanken.';
 return t;
}
