/** Exact, pure models for voluntary written examples (not new quest tasks).
 * Decimal strings → integers + scale; no binary floating point arithmetic.
 * All displayed intermediate values are generated by the same explicit algorithm.
 */
const ten=p=>10n**BigInt(p);
export function decimalParts(value){
 const s=String(value).replace('.',',');
 if(!/^\d{1,9}(,\d{1,6})?$/.test(s))throw new Error('Ungültige Beispielzahl: '+s);
 const [whole,fraction='']=s.split(',');return {n:BigInt(whole+fraction),scale:fraction.length,text:s};
}
export function decimalText(n,scale=0,trim=false){
 let str=String(n).padStart(scale+1,'0');
 if(scale)str=str.slice(0,-scale)+','+str.slice(-scale);
 return trim&&scale?str.replace(/0+$/,'').replace(/,$/,''):str;
}
const clone=x=>JSON.parse(JSON.stringify(x));
const placeNames=['Einer','Zehner','Hunderter','Tausender','Zehntausender','Hunderttausender','Millionen'];
const fractionNames=['Zehntel','Hundertstel','Tausendstel','Zehntausendstel','Hunderttausendstel','Millionstel'];
const place=p=>p>=0?(placeNames[p]||`10 hoch ${p}`):(fractionNames[-p-1]||`1/10 hoch ${-p}`);
const shortPlace=p=>p===0?'E':p===1?'Z':p===2?'H':p===3?'T':p>3?'10^'+p:p===-1?'z':p===-2?'h':p===-3?'t':p===-4?'zt':'10^'+p;
const slots=(length,scale)=>Array.from({length},(_,i)=>({label:shortPlace(length-i-1-scale),title:place(length-i-1-scale)}));
const digits=(n,length)=>String(n).padStart(length,'0').split('').map(Number);
const shownNumber=(p,scale,length)=>{
 const raw=String(p.n*ten(scale-p.scale)).padStart(scale+1,'0'),out=Array(length).fill('');
 for(let i=0;i<raw.length;i++){const index=length-raw.length+i;out[index]={text:raw[i],added:scale>p.scale&&i>=raw.length-(scale-p.scale)};}
 return out;
};
const line=(label,cells,kind='',extra={})=>({label,cells,kind,...extra});
const opSymbol={add:'+',sub:'−',mul:'·',div:':'};
export const calculationLabel=c=>`${c.a} ${opSymbol[c.op]} ${c.b}`;
function base(c){return {op:c.op,title:c.title||calculationLabel(c),expression:calculationLabel(c),context:c.context||'',steps:[]};}
function addModel(c){
 const a=decimalParts(c.a),b=decimalParts(c.b),scale=Math.max(a.scale,b.scale),an=a.n*ten(scale-a.scale),bn=b.n*ten(scale-b.scale),total=an+bn;
 const length=Math.max(String(total).length,scale+1),aa=digits(an,length),bb=digits(bn,length),carry=Array(length).fill(''),result=Array(length).fill('');
 const m={...base(c),scale,columns:slots(length,scale),result:decimalText(total,scale),exact:true};
 const snapshot=(heading,text,col=null,phase='column')=>m.steps.push({heading,text,phase,focus:col===null?[]:[col],rows:[line('Übertrag',carry,'carry'),line('',shownNumber(a,scale,length)),line('+',shownNumber(b,scale,length)),line('=',result,'result')].map(clone)});
 snapshot('Stellen richtig ausrichten',`Schreibe ${decimalText(an,scale)} und ${decimalText(bn,scale)} mit Komma unter Komma. Ergänzte Endnullen verändern den Wert nicht. Rechne von rechts nach links.`,null,'align');
 for(let i=length-1;i>=0;i--){
  const incoming=Number(carry[i]||0),sum=aa[i]+bb[i]+incoming;result[i]=String(sum%10);
  const next=Math.floor(sum/10);if(next&&i>0)carry[i-1]=String(next);
  const text=`${m.columns[i].title}: ${aa[i]} + ${bb[i]}${incoming?' + '+incoming+' (Übertrag)':''} = ${sum}. Schreibe ${result[i]}${next?`; übertrage ${next} zur ${m.columns[i-1].title.toLowerCase()}-Spalte.`:'.'}${i===0?' Ergebnis: '+m.result+'.':''}`;
  snapshot(i===0?'Ergebnis ablesen':next?'Bündeln und übertragen':'Diese Spalte berechnen',text,i);
 }
 return m;
}
function subtractModel(c){
 const a=decimalParts(c.a),b=decimalParts(c.b),scale=Math.max(a.scale,b.scale),an=a.n*ten(scale-a.scale),bn=b.n*ten(scale-b.scale);
 if(an<bn)throw new Error('Dieses Entbündelungsmodell benötigt eine nichtnegative Differenz.');
 const length=Math.max(String(an).length,scale+1),work=digits(an,length),bb=digits(bn,length),result=Array(length).fill(''),history=work.map(d=>[d]);
 const m={...base(c),scale,columns:slots(length,scale),result:decimalText(an-bn,scale),exact:true};
 const snapshot=(heading,text,focus=[],phase='column')=>{
  const first=shownNumber(a,scale,length).map((v,i)=>history[i].length>1?{text:String(work[i]),previous:history[i].slice(0,-1).map(String)}:v);
  m.steps.push({heading,text,phase,focus,values:[...work],rows:[line('Oben',first,'minuend'),line('−',shownNumber(b,scale,length)),line('=',result,'result')].map(clone)});
 };
 snapshot('Komma unter Komma',`Schreibe ${decimalText(an,scale)} − ${decimalText(bn,scale)}. Falls eine Stelle oben nicht reicht, entbündelst du links. Durchgestrichene Werte werden ersetzt, nicht zusätzlich addiert.`,[],'align');
 for(let i=length-1;i>=0;i--){
  if(work[i]<bb[i]){
   let donor=i-1;while(donor>=0&&work[donor]===0)donor--;
   if(donor<0)throw new Error('Kein Entbündeln möglich.');
   for(let j=donor;j<i;j++){
    const before=work[j];work[j]--;work[j+1]+=10;history[j].push(work[j]);history[j+1].push(work[j+1]);
    snapshot('Ein Bündel tauschen',`1 ${m.columns[j].title} entspricht 10 ${m.columns[j+1].title}. Oben werden ${before} zu ${work[j]}; rechts daneben stehen jetzt ${work[j+1]}. Die gesamte Menge bleibt gleich.`,[j,j+1],'exchange');
   }
  }
  result[i]=String(work[i]-bb[i]);snapshot(i===0?'Differenz ablesen':'Jetzt abziehen',`${m.columns[i].title}: ${work[i]} − ${bb[i]} = ${result[i]}.${i===0?' Ergebnis: '+m.result+'.':''}`,[i]);
 }
 return m;
}
function multiplyModel(c){
 const a=decimalParts(c.a),b=decimalParts(c.b),product=a.n*b.n,scale=a.scale+b.scale;
 const ad=String(a.n).split('').map(Number),bd=String(b.n).split('').map(Number),length=Math.max(String(product).length,ad.length+1,bd.length);
 const columns=slots(length,0),partials=[],carriers=[],sumCarry=Array(length).fill(''),sumDigits=Array(length).fill('');
 const m={...base(c),scale:0,columns,result:decimalText(product,scale),exact:true,decimalPlaces:scale};
 const pad=value=>Array(length-String(value).length).fill('').concat(String(value).split(''));
 const snapshot=(heading,text,focus=[],phase='multiply',showResult=false)=>{
  const rows=[];
  for(const cr of carriers)rows.push(line('Ü ·'+cr.digit,cr.cells,'carry',{title:'Multiplikationsüberträge für die Ziffer '+cr.digit}));
  rows.push(line('',pad(a.n)),line('·',pad(b.n)));
  for(const part of partials)rows.push(line('·'+part.factor,part.cells,'partial',{title:'Teilprodukt: '+a.n+' · '+part.factor}));
  if(partials.length>1)rows.push(line('+ Ü',sumCarry,'carry',{title:'Überträge beim Addieren der Teilprodukte'}));
  rows.push(line('=',sumDigits,'result'));
  m.steps.push({heading,text,focus,phase,showResult,rows:clone(rows)});
 };
 snapshot('Natürliche Hilfsrechnung',`${a.text} wird zu ${a.n}${a.scale?' (mal '+ten(a.scale)+')':''}; ${b.text} wird zu ${b.n}${b.scale?' (mal '+ten(b.scale)+')':''}. Rechne ${a.n} · ${b.n}. ${scale?'Das Hilfsergebnis ist insgesamt '+ten(scale)+'-mal so groß. Am Ende wird es durch '+ten(scale)+' geteilt.':'Beide Faktoren sind ganzzahlig.'}`,[],'align');
 for(let j=0;j<bd.length;j++){
  const digit=bd[bd.length-1-j],factor=BigInt(digit)*ten(j),cells=Array(length).fill(''),carries=Array(length).fill('');
  for(let z=0;z<j;z++)cells[length-1-z]={text:'0',added:true};
  const p={cells,factor:String(factor),value:a.n*factor};partials.push(p);carriers.push({digit,cells:carries});
  if(digit===0){cells[length-1-j]='0';snapshot('Null als Faktor',`Die ${place(j)}-Ziffer ist 0. Dieses Teilprodukt ist 0; sein Stellenwert wird nicht übersprungen.`,[length-1-j]);continue;}
  let carry=0;
  for(let i=ad.length-1;i>=0;i--){
   const index=length-ad.length+i,sum=ad[i]*digit+carry,incoming=carry;carry=Math.floor(sum/10);cells[index-j]=String(sum%10);
   if(carry)carries[index-1]=String(carry);
   snapshot(`Teilprodukt mit ${factor}`,`${digit} · ${ad[i]}${incoming?' + '+incoming+' (Übertrag)':''} = ${sum}. Schreibe ${sum%10}${carry?'; merke '+carry+' für die nächste Stelle':'.'}${j?` Die ${j} Endnull${j>1?'en':''} ${j>1?'stehen':'steht'} für den Stellenwert ${ten(j)}.`:''}`,[index,index-j]);
  }
  if(carry){cells[length-ad.length-1-j]=String(carry);snapshot('Letzten Übertrag notieren',`Vorne bleibt ${carry} als letzte Ziffer dieses Teilprodukts.`,[length-ad.length-1-j]);}
 }
 if(partials.length>1){
  for(let i=length-1;i>=0;i--){
   const values=partials.map(p=>Number((p.value/ten(length-1-i))%10n)),incoming=Number(sumCarry[i]||0),total=values.reduce((a,b)=>a+b,0)+incoming;
   sumDigits[i]=String(total%10);if(total>=10&&i>0)sumCarry[i-1]=String(Math.floor(total/10));
   snapshot('Teilprodukte stellenrichtig addieren',`${columns[i].title}: ${values.join(' + ')}${incoming?' + '+incoming+' (Übertrag)':''} = ${total}. Schreibe ${total%10}${total>=10?'; übertrage '+Math.floor(total/10):'.'}`,[i],'sum');
  }
 }else{const n=pad(product);n.forEach((v,i)=>sumDigits[i]=v);snapshot('Das natürliche Produkt',`${a.n} · ${b.n} = ${product}.`,[],'sum');}
 snapshot(scale?'Das Dezimalkomma setzen':'Ergebnis ablesen',scale?`Die Faktoren haben zusammen ${scale} Nachkommastellen. ${product} : ${ten(scale)} = ${m.result}. ${a.text} · ${b.text} = ${m.result}.`:`${a.text} · ${b.text} = ${m.result}.`,[],'decimal',true);
 return m;
}
function divideModel(c){
 const a=decimalParts(c.a),b=decimalParts(c.b);if(b.n===0n)throw new Error('Durch null darf nicht geteilt werden.');
 // Scaling BOTH operands leaves the quotient unchanged; it is NOT rounding.
 const shiftedN=a.n*ten(Math.max(0,b.scale-a.scale)),shiftedScale=Math.max(0,a.scale-b.scale),divisor=b.n;
 const shifted=decimalText(shiftedN,shiftedScale),[integer,fraction='']=shifted.split(','),source=(integer+fraction).split('').map(Number),intLen=integer.length;
 let end=0,current=BigInt(source[0]);while(current<divisor&&end<intLen-1){end++;current=current*10n+BigInt(source[end]);}
 const ops=[],seen=new Map();let qInteger='',qFraction='',periodic=null,extra=0,truncated=false;
 for(let guard=0;guard<70;guard++){
  const digit=current/divisor,remainder=current%divisor,isFraction=end>=intLen;
  if(isFraction)qFraction+=String(digit);else qInteger+=String(digit);
  ops.push({end,current:String(current),digit:String(digit),subtract:String(digit*divisor),rest:String(remainder),q:qInteger+(qFraction?',':'')+qFraction,appended:end>=intLen+fraction.length});
  if(end>=intLen+fraction.length-1){
   if(remainder===0n)break;
   if(seen.has(String(remainder))&&!periodic)periodic={start:seen.get(String(remainder)),digits:qFraction.slice(seen.get(String(remainder)))};
   if(!seen.has(String(remainder)))seen.set(String(remainder),qFraction.length);
   if(periodic&&qFraction.length>=periodic.start+Math.max(3,periodic.digits.length*2))break;
   if(extra++>=24){truncated=true;break;}
  }
  end++;if(source[end]===undefined)source.push(0);current=remainder*10n+BigInt(source[end]);
 }
 const length=source.length,scale=length-intLen,columns=slots(length,scale),rows=[];
 const dividend=integer+(scale?','+source.slice(intLen).join(''):'');
 const m={...base(c),columns,scale,divisor:String(divisor),dividend,result:periodic?qInteger+','+qFraction.slice(0,periodic.start)+'('+periodic.digits+')':qInteger+(qFraction?','+qFraction:''),periodic,exact:!truncated,normalized:shifted+' : '+divisor};
 const aligned=(value,end)=>{const a=Array(length).fill(''),str=String(value);for(let j=0;j<str.length;j++)a[end-str.length+1+j]=str[j];return a;};
 const snapshot=(heading,text,q='',focus=[],phase='divide',showResult=false)=>m.steps.push({heading,text,quotient:q,focus,phase,showResult,rows:clone(rows)});
 snapshot(b.scale?'Zuerst einen ganzzahligen Teiler herstellen':'Division vorbereiten',b.scale?`Beide Zahlen mal ${ten(b.scale)}: ${a.text} : ${b.text} = ${shifted} : ${divisor}. Der Quotient bleibt gleich. Danach rechnest du von links nach rechts.`:`Der Teiler ${divisor} ist ganzzahlig. Rechne von links nach rechts. Beim Übergang zu den Zehnteln setzt du im Ergebnis das Komma.`, '',[],'align');
 for(let k=0;k<ops.length;k++){
  const o=ops[k],col=o.end,unit=columns[col].title;
  rows.push(line(k?'↓':'',aligned(o.current,col),'div-current',{title:k?'Nächste Ziffer herunterholen':'Erster Teildividend'}));
  snapshot(k?'Ziffer herunterholen':'Erste passende Zahl nehmen',k?`${o.appended?'Der Dividend darf mit einer Endnull ergänzt werden. ':''}Hole ${source[col]} herunter: ${ops[k-1].rest} · 10 + ${source[col]} = ${o.current}. ${col===intLen?'Jetzt beginnt der Nachkommateil: Setze ein Komma im Quotienten.':''}`:`Beginne mit ${o.current}. Die erste Ergebnisziffer steht bei den ${unit.toLowerCase()}.`,k?ops[k-1].q:'',[col],'bring');
  snapshot('Nächste Quotientenziffer',`${o.current} : ${divisor} ergibt ${o.digit} mit Rest ${o.rest}. Schreibe ${o.digit} an die ${unit.toLowerCase()}-Stelle des Ergebnisses.`,o.q,[col],'quotient');
  rows.push(line('−',aligned(o.subtract,col),'div-sub',{title:o.digit+' · '+divisor}));
  rows.push(line('Rest',aligned(o.rest,col),'div-rest'));
  snapshot('Vielfaches abziehen',`${o.digit} · ${divisor} = ${o.subtract}. ${o.current} − ${o.subtract} = ${o.rest}. ${k===ops.length-1&&o.rest==='0'?'Rest 0: Die Rechnung geht auf.':'Mit diesem Rest geht es weiter.'}`,o.q,[col],'subtract');
 }
 let final=periodic?`Der Rest wiederholt sich. Deshalb wiederholt sich die Ziffernfolge ${periodic.digits} unbegrenzt. Die überstrichenen Ziffern bilden die Periode; das ist keine gerundete Zahl.`:truncated?'Die Darstellung zeigt nur einen begrenzten Ausschnitt. Das Ergebnis ist noch nicht vollständig.':`Rest 0: ${a.text} : ${b.text} = ${m.result}. Prüfe durch die Umkehrung: ${m.result} · ${b.text} = ${a.text}.`;
 snapshot(periodic?'Die Periode erkennen':'Ergebnis und Probe',final,ops.at(-1).q,[],'complete',true);
 return m;
}
export function buildWritten(c){
 const builders={add:addModel,sub:subtractModel,mul:multiplyModel,div:divideModel};
 if(!builders[c.op])throw new Error('Unbekanntes schriftliches Verfahren.');
 return builders[c.op](c);
}
