import test from 'node:test';
import assert from 'node:assert/strict';
import {SRL_RULES,SUPPORT_DEFAULTS,supportLevels,promptBudget,repeatedErrors,multipleSkips,rapidExits,fadeDecision,performanceEvidence,sessionReview,regulationSummary,calibrationText,latestPlan,previousIntention} from '../teacher-dashboard/shared/regulation.js';
import {Regulation} from '../js/regulation.js';
import {validateSave,SCHEMA_VERSION,uid} from '../teacher-dashboard/shared/save-schema.js';
import {makeDemoSave} from '../teacher-dashboard/js/demo.js';
import {planMerge} from '../teacher-dashboard/js/database.js';
import {filterEvents} from '../teacher-dashboard/js/timeline.js';
import {regulationDetailView,regulationClassView} from '../teacher-dashboard/js/regulation-view.js';
const t=Date.parse('2026-09-10T09:00:00.000Z');
let seq=0;
function event(type,data={},offset=0,context={}){return {type,data,timestamp:new Date(t+offset).toISOString(),eventId:'ev-'+(++seq),studentId:'s1',sessionId:'one',...context};}
function attempts(n,kind='regular',correct=false,run='task1'){return Array.from({length:n},(_,i)=>event('task_attempt',{correct,attemptNumber:i+1},i,{kind,taskRunId:run,questId:'q1',topicId:'village',taskId:'q1-1'}));}
function fakeLog(events=[]){const listeners=[];const log={events,ctx:{},studentId:'s1',current:{sessionId:'one'},subscribe:fn=>{listeners.push(fn);return ()=>{};},contextOf:e=>{const c={};for(const k of ['questId','taskId','topicId','runId','taskRunId','skillId','kind'])if(e[k])c[k]=e[k];return c;},tick:()=>{},emit(type,data={},context={}){const e=event(type,data,seq+1,context);this.events.push(e);listeners.forEach(f=>f(e));return e;}};return log;}
function stableWork(quests=3,perQuest=5,kind='regular'){const es=[];let offset=0;for(let q=0;q<quests;q++){es.push(event('srl_navigation_choice',{source:'map',questId:'q'+q,support:3},offset++));for(let j=0;j<perQuest;j++)es.push(event('task_attempt',{correct:true,attemptNumber:1},offset++,{kind,questId:'q'+q,taskRunId:`q${q}-${j}`,topicId:'village'}));es.push(event(kind==='challenge'?'challenge_completed':'quest_completed',{},offset++,{kind,questId:'q'+q}));}return es;}
test('SRL defaults distinguish five independent support dimensions',()=>{assert.deepEqual(SUPPORT_DEFAULTS,{navigation:3,planning:2,strategy:2,content:0,challenge:1});});
test('Only known support dimensions and 0..3 affect derived settings',()=>{const es=[event('srl_support_changed',{dimension:'navigation',level:1}),event('srl_support_changed',{dimension:'content',level:3}),event('srl_support_changed',{dimension:'navigation',level:99})];assert.equal(supportLevels(es).navigation,1);assert.equal(supportLevels(es).content,3);assert.equal(supportLevels(es).planning,2);});
test('Budget begins available and first error does not count as prompt',()=>{assert.ok(promptBudget(attempts(1),'one',t).allowed);assert.ok(!repeatedErrors(attempts(1),'task1'));});
test('Regular errors require three consecutive unsuccessful attempts',()=>{assert.ok(!repeatedErrors(attempts(2),'task1'));assert.ok(repeatedErrors(attempts(3),'task1'));});
test('A correct attempt resets the current error streak',()=>{const a=attempts(4);a.push(...attempts(1,'regular',true));assert.ok(!repeatedErrors(a,'task1'));});
test('Challenge errors require five, exam and encounter errors never trigger',()=>{assert.ok(!repeatedErrors(attempts(4,'challenge'),'task1','challenge'));assert.ok(repeatedErrors(attempts(5,'challenge'),'task1','challenge'));for(const kind of ['exam','encounter'])assert.ok(!repeatedErrors(attempts(20,kind),'task1',kind));});
test('Five minute cooldown is shared across all unsolicited prompt types',()=>{const es=[event('srl_prompt_shown',{reason:'errors',unsolicited:true})];assert.ok(!promptBudget(es,'one',t+299999).allowed);assert.ok(promptBudget(es,'one',t+300000).allowed);});
test('At most two unplanned prompts per session even if hours pass',()=>{const es=[event('srl_prompt_shown',{unsolicited:true}),event('srl_prompt_shown',{unsolicited:true},300000)];assert.ok(!promptBudget(es,'one',t+3600000).allowed);});
test('Reload/new session cannot reset the rolling 30-minute limit',()=>{const es=[event('srl_prompt_shown',{unsolicited:true}),event('srl_prompt_shown',{unsolicited:true},300000)];assert.ok(!promptBudget(es,'two',t+900000).allowed);assert.ok(promptBudget(es,'two',t+2100001).allowed);});
test('User-requested help never consumes the interruption budget',()=>{const es=Array.from({length:10},(_,i)=>event('srl_prompt_shown',{unsolicited:false},i));assert.ok(promptBudget(es,'one',t+100).allowed);assert.equal(promptBudget(es,'one',t+100).used,0);});
test('Only distinct regular explicitly skipped quests count',()=>{const es=[event('quest_skipped',{},1,{questId:'a',kind:'regular'}),event('quest_skipped',{},2,{questId:'a',kind:'regular'}),event('quest_skipped',{},3,{questId:'b',kind:'challenge'}),event('quest_paused',{},4,{questId:'c',kind:'regular'})];assert.deepEqual(multipleSkips(es,'one',t+10),['a']);});
test('A skip discussion resets the relevant skip cluster, not quest state',()=>{const es=['a','b','c'].map((questId,i)=>event('quest_skipped',{},i+1,{questId,kind:'regular'}));assert.equal(multipleSkips(es,'one',t+10).length,3);es.push(event('srl_prompt_shown',{reason:'skips',unsolicited:true},11));assert.equal(multipleSkips(es,'one',t+20).length,0);});
test('Rapid opening and exiting without work yields a conservative offer',()=>{const es=[];for(let i=0;i<3;i++){es.push(event('quest_started',{},i*50000,{runId:'r'+i,questId:'q'+i,kind:'regular'}));es.push(event('quest_paused',{},i*50000+1000,{runId:'r'+i,questId:'q'+i,kind:'regular'}));}assert.equal(rapidExits(es,'one',t+130000).length,3);});
test('Reading knowledge or attempting answers is not directionless jumping',()=>{const es=[event('quest_started',{},0,{runId:'r',questId:'q',kind:'regular'}),event('knowledge_opened',{},10,{runId:'r',questId:'q',kind:'regular'}),event('quest_paused',{},100,{runId:'r',questId:'q',kind:'regular'})];assert.equal(rapidExits(es,'one',t+1000).length,0);});
test('Stable performance and successful own choices fade exactly one level',()=>{const es=stableWork();const f=fadeDecision(es);assert.equal(f.level,2);assert.equal(f.dimension,'navigation');});
test('Few correct tasks and quest count alone cannot fade support',()=>{assert.equal(fadeDecision(stableWork(1,20)),null);assert.equal(fadeDecision(stableWork(2,2)),null);});
test('Reliable work without own decisions does not fade',()=>{const es=stableWork().filter(e=>e.type!=='srl_navigation_choice');assert.equal(fadeDecision(es),null);});
test('Challenge success alone cannot fade, challenge failure cannot increase support',()=>{assert.equal(fadeDecision(stableWork(4,5,'challenge')),null);const base=stableWork();const f=fadeDecision(base);base.push(...attempts(30,'challenge'));assert.deepEqual(fadeDecision(base),f);});
test('Evidence cannot be reused to cascade through several levels',()=>{const es=stableWork();es.push(event('srl_support_changed',{dimension:'navigation',level:2},10000));assert.equal(fadeDecision(es,supportLevels(es)),null);});
test('Poor regular performance does not silently restore maximum guidance',()=>{const log=fakeLog([event('srl_support_changed',{dimension:'navigation',level:0}),...attempts(8)]),r=new Regulation(log,()=>({}));r.sync();assert.equal(r.fade(),null);assert.equal(r.levels.navigation,0);});
test('All mathematical help settings remain independent when navigation changes',()=>{const log=fakeLog(),r=new Regulation(log,()=>({}));r.changeSupport('content',3);r.changeSupport('navigation',0);assert.equal(r.levels.content,3);assert.equal(r.levels.strategy,2);});
test('Strategy outcomes refer to the latest relevant choice on the same task run',()=>{const log=fakeLog(),r=new Regulation(log,()=>({}));const ctx={taskRunId:'r',taskId:'q:1',questId:'q',topicId:'village',kind:'regular'};r.selectStrategy('hint',{context:ctx});const selection=r.selectStrategy('example',{context:ctx});log.emit('task_completed',{},ctx);const out=log.events.filter(e=>e.type==='srl_strategy_outcome');assert.equal(out.length,1);assert.equal(out[0].data.selectionEventId,selection.eventId);assert.equal(out[0].data.relation,'later_success_not_causation');});
test('Task completion does not fabricate a strategy if none was selected',()=>{const log=fakeLog(),r=new Regulation(log,()=>({}));log.emit('task_completed',{}, {taskRunId:'a'});assert.ok(!log.events.some(e=>e.type==='srl_strategy_outcome'));});
test('A later unrelated task cannot be attributed to an earlier strategy',()=>{const log=fakeLog(),r=new Regulation(log,()=>({}));r.selectStrategy('hint',{context:{taskRunId:'a'}});log.emit('task_completed',{}, {taskRunId:'b'});assert.equal(log.events.filter(e=>e.type==='srl_strategy_outcome').length,0);});
test('Solution viewing is separately marked on a later successful outcome',()=>{const log=fakeLog(),r=new Regulation(log,()=>({}));const ctx={taskRunId:'a'};r.selectStrategy('steps',{context:ctx});log.emit('solutionStep_opened',{},ctx);log.emit('task_completed',{},ctx);assert.equal(log.events.at(-1).data.assisted,true);});
test('Plans can change without overwriting the original plan',()=>{const log=fakeLog(),r=new Regulation(log,()=>({}));r.setPlan({goal:'open'});r.setPlan({goal:'self'});assert.equal(log.events.filter(e=>e.type==='srl_plan_set').length,2);assert.equal(latestPlan(log.events,'one').data.goal,'self');assert.equal(log.events.at(-1).data.amended,true);});
test('Next-session intention comes from an earlier session, not the current one',()=>{const es=[event('srl_reflection',{nextGoal:'challenge',topicId:'forest'},0,{sessionId:'old'}),event('srl_reflection',{nextGoal:'open'},1)];assert.equal(previousIntention(es,'one').data.nextGoal,'challenge');});
test('Closing review without saving does not fabricate a reflection',()=>{const log=fakeLog(),r=new Regulation(log,()=>({}));r.review();assert.equal(log.events.filter(e=>e.type==='srl_reflection').length,0);});
test('Reflection is idempotent per session',()=>{const log=fakeLog(),r=new Regulation(log,()=>({}));r.reflect({confidence:3,nextGoal:'open'});r.reflect({confidence:4,nextGoal:'explore'});assert.equal(log.events.filter(e=>e.type==='srl_reflection').length,1);});
test('Review keeps normal and challenge attempts separate; encounters are not completed quests',()=>{const es=[...attempts(3),...attempts(2,'challenge'),event('quest_completed',{},10,{questId:'enc',kind:'encounter'})];const r=sessionReview(es,'one');assert.equal(r.regular.attempts,3);assert.equal(r.challenge.attempts,2);assert.equal(r.completed,0);});
test('Calibration explicitly avoids judging insufficient data',()=>{const r=sessionReview(attempts(1),'one');assert.match(calibrationText(r,5),/wenige Antworten/);});
test('Calibration can distinguish secure core work from difficult transfer',()=>{const es=stableWork(2,3);es.push(...attempts(2,'challenge',false,'c1'),...attempts(2,'challenge',false,'c2'));assert.match(calibrationText(sessionReview(es,'one'),5),/Herausforderungsaufgaben/);});
test('Returning to a previously deferred but never started quest is recognized',()=>{const es=[event('quest_skipped',{},0,{questId:'q'}),event('quest_started',{},1,{questId:'q'})];assert.equal(regulationSummary(es).returned,1);});
test('Date filter excludes future plans and reflects past navigation support',()=>{const es=[event('srl_support_changed',{dimension:'navigation',level:2}),event('srl_support_changed',{dimension:'navigation',level:0},10000)];const r=regulationSummary(es,{to:new Date(t+5000).toISOString()});assert.equal(r.levels.navigation,2);});
test('New regulation events appear in their own timeline category',()=>{const es=[event('srl_plan_set',{}),event('task_attempt',{})];assert.equal(filterEvents(es,{category:'regulation'}).length,1);});
test('Schema 2 supports new raw events and continues importing schema 1',()=>{const s=makeDemoSave(1);s.schemaVersion=1;assert.equal(validateSave(s).schemaVersion,1);s.schemaVersion=2;const base=s.events[0];s.events.push({...base,eventId:uid(),type:'srl_plan_set',data:{goal:'self',confidence:null,targetCount:null,topicId:null,source:'self'}});assert.equal(validateSave(s).schemaVersion,2);});
test('Malformed confidence, support levels and unknown strategies are rejected',()=>{const s=makeDemoSave(1),base=s.events[0];for(const [type,data] of [['srl_plan_set',{goal:'self',confidence:8,targetCount:null,topicId:null,source:'self'}],['srl_support_changed',{dimension:'navigation',level:-1,reason:'student_choice'}],['srl_strategy_selected',{strategy:'diagnose',source:'manual'}]])assert.throws(()=>validateSave({...s,events:[...s.events,{...base,eventId:uid(),type,data}]}));});
test('Merge treats SRL event IDs as immutable and remains idempotent',()=>{const s=makeDemoSave(1);s.events.push({...s.events[0],eventId:uid(),type:'srl_support_changed',data:{dimension:'navigation',level:1,reason:'student_choice'}});const a=planMerge({events:[],sessions:[],snapshots:[]},validateSave(s));const b=planMerge(a,validateSave(s));assert.equal(b.newEvents.length,0);assert.equal(b.status,'duplicate');});
test('No global self-regulation score is derived by the dashboard',()=>{const r=regulationSummary(stableWork());assert.ok(!('score' in r));assert.ok(!('diagnosis' in r));});
test('A duplicate task completion does not attribute success to an older unused strategy',()=>{const log=fakeLog(),r=new Regulation(log,()=>({}));const ctx={taskRunId:'r'};r.selectStrategy('hint',{context:ctx});r.selectStrategy('example',{context:ctx});log.emit('task_completed',{},ctx);log.emit('task_completed',{},ctx);assert.equal(log.events.filter(e=>e.type==='srl_strategy_outcome').length,1);});
test('Revealing answers before first attempts cannot produce automatic fading',()=>{const es=stableWork();for(const e of [...es].filter(e=>e.type==='task_attempt'))es.push(event('solutionStep_opened',{},Date.parse(e.timestamp)-t-0.5,{taskRunId:e.taskRunId}));es.sort((a,b)=>a.timestamp.localeCompare(b.timestamp));assert.equal(fadeDecision(es),null);});
test('Strategy outcomes are not inferred across session boundaries',()=>{const log=fakeLog(),r=new Regulation(log,()=>({}));r.selectStrategy('hint',{context:{taskRunId:'r'}});log.events[0].sessionId='old';log.emit('task_completed',{}, {taskRunId:'r'});assert.equal(log.events.filter(e=>e.type==='srl_strategy_outcome').length,0);});

test("A later decision to keep the next plan open does not revive an older intention",()=>{const es=[event("srl_reflection",{nextGoal:"challenge"},0,{sessionId:"old"}),event("srl_reflection",{nextGoal:"later"},1,{sessionId:"newer"})];assert.equal(previousIntention(es,"current"),null);});

test("Teacher class view does not label old unobserved regulation histories as zero",()=>{const html=regulationClassView([{student:{studentId:"a",studentName:"Altstand"},regulation:{hasData:false,hasHistory:false,levels:{navigation:3}}}]);assert.match(html,/<td>—<\/td>/);assert.doesNotMatch(html,/<td>0<\/td>/);});
