import {learning7ClassView} from './learning7-view.js';
import {regulationClassView} from './regulation-view.js';
import {TeacherDB,databaseName} from './database.js';
import {importFiles} from './importer.js';
import {report as buildReport} from './report.js';
import {overview,learnerTable,topicsView,attentionView} from './class-overview.js';
import {detailView} from './student-detail.js';
import {dateRange,localDay} from './timeline.js';
import {RULES} from './analytics.js';
import {esc,pct,num,date,dateTime,duration,empty,downloadJSON,downloadCSV} from './view-helpers.js';
import {makeDemoSave} from './demo.js';

const $=id=>document.getElementById(id),content=$('content');
const BASE_NAME=databaseName();let demo=false,db=new TeacherDB(BASE_NAME),page='overview',selectedStudent=null,detailTab='overview',taskPage=0,taskFilter='worked',eventPage=0,eventCategory='all',topic='',className='',range=dateRange('',''),tableState={query:'',signal:'all',sort:'priority',descending:true},report=null,detail=null,history=[],busy=false,refreshToken=0,worker=null,job=0;
const titles={learning7:['FACHLICHE LERNSPUREN','Mathematische Vorstellungen verstehen.','Beobachtungen, eigene Erklärungen und konkrete Gesprächsfragen – keine automatischen Diagnosen.'],regulation:['SELBSTREGULIERTES LERNEN','Lernentscheidungen verstehen.','Pläne, Strategien und Unterstützung – ohne automatische Bewertung.'],overview:['KLASSENÜBERBLICK','Lernen sichtbar machen.','Wo steht die Klasse – und wo lohnt sich ein genauerer Blick?'],students:['DEINE LERNGRUPPE','Jeder Lernweg zählt.','Fortschritt, Versuche und Hilfen im Zusammenhang betrachten.'],topics:['MATHEMATISCHE INHALTE','Themen im Blick.','Gemeinsame Schwierigkeiten und nächste Unterrichtsschritte erkennen.'],attention:['PÄDAGOGISCHE GESPRÄCHSANLÄSSE','Wo sollte ich hinschauen?','Verdichtete Evidenz für deine eigene pädagogische Entscheidung.'],timeline:['ZEITLICHER VERLAUF','Entwicklung statt Momentaufnahme.','Lernstände zu unterschiedlichen Zeitpunkten nachvollziehen.'],imports:['DEIN LOKALER DATENBESTAND','Importe nachvollziehen.','Neue Ereignisse ergänzen. Vorhandene Daten nicht doppelt zählen.'],settings:['LOKALE VERWALTUNG','Deine Daten. Deine Kontrolle.','Speicherung, Sicherungen und transparente Auswertungskriterien.'],detail:['INDIVIDUELLER LERNVERLAUF','Einen Lernweg verstehen.','Aufgaben, Hilfen und zeitliche Entwicklung zusammen betrachten.']};
let toastTimer;function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),5500);}
function failure(error){content.innerHTML=`<section class="error-card"><h2>Die Ansicht konnte nicht geladen werden.</h2><p>${esc(error.message||String(error))}</p><p>Der Datenbestand wurde dadurch nicht gelöscht. Andere Fenster schließen und erneut versuchen. Im privaten Browsermodus kann lokaler Speicher eingeschränkt sein.</p><button id="retryView" class="secondary">Erneut versuchen</button></section>`;$('retryView').onclick=refresh;}
function confirm(title,text,action){$('confirmTitle').textContent=title;$('confirmText').textContent=text;$('confirmDialog').showModal();$('confirmCancel').onclick=()=>$('confirmDialog').close();$('confirmOK').onclick=async()=>{$('confirmDialog').close();try{await action();}catch(e){toast(e.message);}};}
function setTitle(){const [eyebrow,title,sub]=titles[page]||titles.overview;$('pageEyebrow').textContent=eyebrow;$('pageTitle').textContent=title;$('pageSubtitle').textContent=sub;document.querySelectorAll('#nav [data-nav]').forEach(b=>{const active=b.dataset.nav===page||page==='detail'&&b.dataset.nav==='students';b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false');});}
async function query(options){
 // Worker is an optimization; the same tested modules work without it.
 if(typeof Worker==='undefined')return buildReport(db,options);
 if(!worker){try{worker=new Worker(new URL('./analysis-worker.js',import.meta.url),{type:'module'});}catch{return buildReport(db,options);}}
 const id=++job;return new Promise((resolve,reject)=>{
  const receive=e=>{if(e.data.id!==id)return;worker.removeEventListener('message',receive);worker.removeEventListener('error',error);e.data.error?reject(new Error(e.data.error)):resolve(e.data.result);};
  const error=e=>{worker?.removeEventListener('message',receive);worker?.removeEventListener('error',error);worker?.terminate();worker=null;buildReport(db,options).then(resolve,reject);};worker.addEventListener('message',receive);worker.addEventListener('error',error,{once:true});worker.postMessage({id,databaseName:demo?BASE_NAME+':demo':BASE_NAME,options});
 });
}
async function refresh(){
 const token=++refreshToken;setTitle();content.innerHTML='<div class="loading-card">Lokale Lernereignisse werden ausgewertet …</div>';
 try{
  await db.ready;
  const all=await db.all('students');const classes=[...new Set(all.map(s=>s.className).filter(Boolean))].sort();$('classFilter').innerHTML='<option value="">Alle Lernenden</option>'+classes.map(c=>`<option ${c===className?'selected':''} value="${esc(c)}">${esc(c)}</option>`).join('');
  $('dataStatus').textContent=all.length?`${all.length} Lernende · lokal`:'Noch keine Lernstände';
  if(page==='imports'){await renderImports();return;}
  if(page==='settings'){await renderSettings();return;}
  if(page==='detail'){
   const result=await query({kind:'detail',studentId:selectedStudent,range});if(token!==refreshToken)return;
   detail=result;if(!detail){page='students';return refresh();}renderDetail();return;
  }
  const result=await query({range,className});if(token!==refreshToken)return;report=result;
  if(page==='overview')content.innerHTML=overview(report);
  if(page==='students')renderStudents();
  if(page==='topics')content.innerHTML=topicsView(report.topics,report.skills,topic);
  if(page==='learning7')content.innerHTML=learning7ClassView(report.rows);
  if(page==='regulation')content.innerHTML=regulationClassView(report.rows);
  if(page==='attention')content.innerHTML=report.rows.length?attentionView(report.rows):empty('Noch keine Beobachtungen.','Importiere zuerst einen Lernstand.');
  if(page==='timeline'){history=await query({kind:'history',range,className,bucket:$('historyBucket')?.value||'day'});if(token!==refreshToken)return;renderHistory();}
  bind();
 }catch(e){if(token===refreshToken)failure(e);}
}
function navigate(next){page=next;if(next!=='detail')selectedStudent=null;refresh();window.scrollTo({top:0,behavior:'instant'});}
function renderStudents(){
 content.innerHTML=`<section class="card"><div class="table-toolbar"><label><input type="search" id="studentSearch" value="${esc(tableState.query)}" placeholder="Namen suchen …" aria-label="Lernende nach Namen suchen"></label><label>Hinweise <select id="signalFilter">${[['all','Alle Lernenden'],['attention','Priorisierte Hinweise'],['support','Wiederholte Schwierigkeiten'],['help','Unterstützung abstimmen'],['skips','Für später markiert'],['stretch','Zusätzliche Herausforderung'],['persistence','Nach Versuchen erfolgreich'],['limited','Noch wenig Daten']].map(([id,label])=>`<option value="${id}" ${tableState.signal===id?'selected':''}>${label}</option>`).join('')}</select></label><button id="exportCSV" class="secondary export-csv">Tabelle als CSV</button></div><div id="learnerTable">${learnerTable(report.rows,tableState)}</div></section>`;
 $('studentSearch').oninput=e=>{tableState.query=e.target.value;$('learnerTable').innerHTML=learnerTable(report.rows,tableState);bind();};$('signalFilter').onchange=e=>{tableState.signal=e.target.value;$('learnerTable').innerHTML=learnerTable(report.rows,tableState);bind();};
 $('exportCSV').onclick=()=>downloadCSV([['Name','Schüler-ID','Klasse','Fortschritt regulär','Quests abgeschlossen','Quests zurückgestellt (jemals)','Fehlerquote','Ø Versuche','Hilfequote','Aktive Zeit (ms)','Challenges abgeschlossen','Datenstand'],...report.rows.map(r=>[r.student.studentName,r.student.studentId,r.student.className,pct(r.regular.progress),r.regular.completed,r.regular.skipCount,pct(r.regular.errorRate),num(r.regular.avgAttempts),pct(r.regular.helpRate),r.regular.duration,r.challenge.completed,r.student.latestExportAt])],'Kommaland_Klassenuebersicht.csv');
}
function renderDetail(){content.innerHTML=detailView(detail,range,detailTab,taskPage,taskFilter,eventPage,eventCategory);bind();
 if($('taskFilter'))$('taskFilter').onchange=e=>{taskFilter=e.target.value;taskPage=0;renderDetail();};
 if($('eventCategory'))$('eventCategory').onchange=e=>{eventCategory=e.target.value;eventPage=0;renderDetail();};
 $('saveClass').onclick=async()=>{await db.setClass(selectedStudent,$('studentClass').value);toast('Klassenzuordnung lokal gespeichert.');refresh();};
 $('deleteStudent').onclick=()=>confirm('Diese Lerndaten löschen?',`Alle lokal importierten Daten von ${detail.student.studentName} werden aus dieser Lehrkräfte-App gelöscht. Bereits exportierte Dateien bleiben bestehen.`,async()=>{await db.deleteStudent(selectedStudent);navigate('students');toast('Die lokalen Daten dieser Person wurden gelöscht.');});
}
function chartHTML(points){
 points=points.filter(p=>p.progress!==null);
 if(!points.length)return empty('Noch kein zeitlicher Verlauf.','Für diese Auswahl liegen keine beobachteten Ereignisse vor.');
 const W=900,H=265,left=45,right=28,top=25,bottom=40,x=i=>left+i*(W-left-right)/Math.max(1,points.length-1),y=v=>H-bottom-(v||0)*(H-top-bottom),line=points.map((p,i)=>(i?'L':'M')+x(i)+','+y(p.progress)).join(' ');
 return `<svg class="history-chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Klassenfortschritt im zeitlichen Verlauf. Die Werte stehen zusätzlich in der Tabelle.">${[0,.25,.5,.75,1].map(v=>`<line class="gridline" x1="${left}" x2="${W-right}" y1="${y(v)}" y2="${y(v)}"/><text x="2" y="${y(v)+4}">${Math.round(v*100)} %</text>`).join('')}<path class="area" d="${line} L${x(points.length-1)},${y(0)} L${x(0)},${y(0)}Z"/><path class="curve" d="${line}"/>${points.map((p,i)=>`<g><circle class="dot" cx="${x(i)}" cy="${y(p.progress)}" r="5" data-day="${p.day}" tabindex="0" role="button" aria-label="${p.day}: ${pct(p.progress)}; bis zu diesem Tag filtern"><title>${p.day}: ${pct(p.progress)} · ${p.observed}/${p.total} Lernende mit Daten</title></circle>${i===0||i===points.length-1||points.length<12||i%Math.ceil(points.length/8)===0?`<text x="${x(i)}" y="${H-12}" text-anchor="middle">${date(p.day+'T12:00:00').slice(0,5)}</text>`:''}</g>`).join('')}</svg>`;
}
function renderHistory(){
 content.innerHTML=`<section class="card"><div class="card-heading"><div><span class="eyebrow">REGULÄRE QUESTS · KUMULATIVER FORTSCHRITT</span><h2>Wie hat sich die Klasse entwickelt?</h2></div><label>Auflösung <select id="historyBucket"><option value="day">Tag</option><option value="week">Woche</option></select></label></div>${chartHTML(history)}<div class="chart-legend"><span><i></i>Mittlerer Quest-Fortschritt</span><span>Vor dem ersten beobachteten Lernstand: unbekannt, nicht 0 %.</span></div><p class="muted small">Punkt auswählen, um bis zu diesem Tag zu filtern. Die Kurve zeigt die zu diesem Zeitpunkt beobachteten Personen; Änderungen der Gruppengröße können den Mittelwert verändern. Tage ohne Aktivität werden nicht ergänzt.</p></section><section class="card"><h2>Zeitpunkte vergleichen</h2><div class="compare-box"><label>Erster Zeitpunkt <input id="compareA" type="date" value="${history[0]?.day||''}"></label><label>Zweiter Zeitpunkt <input id="compareB" type="date" value="${history.at(-1)?.day||''}"></label><button id="compareDates" class="secondary">Vergleichen</button></div><div id="comparison"></div><div class="table-scroll"><table><thead><tr><th>Stand am</th><th>Klassenfortschritt</th><th>Beobachtete Lernende</th><th>Antwortversuche bis dahin</th><th>Fehlversuche bis dahin</th></tr></thead><tbody>${history.map(p=>`<tr><th>${date(p.day+'T12:00:00')}</th><td>${pct(p.progress)}</td><td>${p.observed} / ${p.total}</td><td>${p.attempts}</td><td>${pct(p.errorRate)}</td></tr>`).join('')}</tbody></table></div></section>`;
 $('historyBucket').onchange=async e=>{const bucket=e.target.value;history=await query({kind:'history',range,className,bucket});renderHistory();$('historyBucket').value=bucket;bind();};
 $('compareDates').onclick=async()=>{const a=$('compareA').value,b=$('compareB').value;if(!a||!b){toast('Bitte beide Vergleichsdaten auswählen.');return;}const [ra,rb]=await Promise.all([query({range:dateRange('',a),className}),query({range:dateRange('',b),className})]);$('comparison').innerHTML=`<p class="calm-note">Regulärer Quest-Fortschritt: <strong>${pct(ra.summary.averageProgress)}</strong> am ${date(a+'T12:00:00')} → <strong>${pct(rb.summary.averageProgress)}</strong> am ${date(b+'T12:00:00')}.</p><div class="table-scroll"><table><thead><tr><th>Thema</th><th>${date(a+'T12:00:00')}</th><th>${date(b+'T12:00:00')}</th><th>Fehlerquote bis ${date(b+'T12:00:00')}</th></tr></thead><tbody>${rb.topics.map(t=>`<tr><th>${esc(t.title)}</th><td>${pct(ra.topics.find(x=>x.topicId===t.topicId)?.progress)}</td><td>${pct(t.progress)}</td><td>${pct(t.errorRate)}</td></tr>`).join('')}</tbody></table></div>`;};
}
async function renderImports(){const imports=(await db.all('imports')).sort((a,b)=>b.timestamp.localeCompare(a.timestamp));content.innerHTML=`<section class="card"><div class="card-heading"><div><h2>Alle Importvorgänge</h2><p class="muted small">Auch wiederholte Importversuche werden dokumentiert. Die Lernereignisse selbst bleiben eindeutig.</p></div><span class="muted small">${imports.length} Protokolleinträge</span></div><div class="table-scroll"><table><thead><tr><th>Zeitpunkt</th><th>Datei</th><th>Ergebnis</th><th>Neue Ereignisse</th><th>Doppelte ignoriert</th></tr></thead><tbody>${imports.slice(0,1000).map(i=>`<tr><td>${dateTime(i.timestamp)}</td><th><span class="technical-id">${esc(i.fileName)}</span>${i.error?`<small class="muted">${esc(i.error)}</small>`:''}</th><td>${esc({imported:'Ergänzt',duplicate:'Vollständig vorhanden',invalid:'Ungültig',ignored:'Ignoriert'}[i.status]||i.status)}</td><td>${i.eventsAdded||0}</td><td>${i.eventsIgnoredAsDuplicates||0}</td></tr>`).join('')}</tbody></table></div>${imports.length>1000?'<p class="muted small">Die neuesten 1000 Einträge werden angezeigt. Die vollständige Historie ist in der Datensicherung enthalten.</p>':''}</section>`;bind();}
async function renderSettings(){let storage='Nicht verfügbar';try{const estimate=await navigator.storage?.estimate();if(estimate)storage=`${num((estimate.usage||0)/1048576,1)} MiB belegt auf dieser Webadresse`;}catch{}
 content.innerHTML=`<div class="settings-grid"><section class="card"><h2>Lokale Daten sichern</h2><p>Importierte Daten liegen in IndexedDB dieses Browsers und dieser Webadresse. Ein Neuladen erhält sie. Gelöschte Websitedaten, Speicherbereinigung oder private Sitzungen können sie entfernen.</p><p class="storage-warning">Eine lokale Datenbank ist kein Backup. Sichere den Klassenbestand regelmäßig auf einem geschützten Speicherort.</p><p class="muted small">${esc(storage)}</p><div class="settings-actions"><button id="backupAll" class="primary">Gesamten Bestand sichern</button><button id="requestPersist" class="secondary">Dauerhaften Speicher anfragen</button></div><p id="persistResult" class="muted small"></p><p class="muted small">Eine Lehrkräfte-Sicherung lässt sich über denselben JSON-Import wieder einlesen. Namen und Ereignisse bleiben enthalten.</p></section><section class="card"><h2>Datenschutz im Betrieb</h2><p>Keine Datei wird von dieser App hochgeladen. Keine Cloud-Datenbank, keine externen Schriftarten, keine Analytics-Dienste. Die Seite lädt nur ihre eigenen lokalen Programmdateien.</p><p>Gespeichert werden Name/Kürzel, Zufalls-ID und relevante Lernereignisse. Keine eingegebenen Antworten, keine freien Texte, keine Tastatureingaben, keine Gerätekennung und keine IP-Adresse im Lernstand.</p><p>Benutze einen geschützten Lehrkräfte-Browser und vereinbarte Namen oder Kürzel. Speicherdateien sind unverschlüsselte personenbezogene Dateien. Diese statische Anwendung stellt keine Benutzeranmeldung oder Zugriffskontrolle bereit.</p><div class="settings-actions"><button id="demoMode" class="secondary">Getrennte Demoklasse öffnen</button><button id="clearAll" class="danger">Alle lokalen Daten löschen</button></div></section></div>
 <section class="card"><h2>So werden die Kennzahlen berechnet</h2><div class="table-scroll"><table class="rules-table"><tbody><tr><th>Quest-Fortschritt</th><td>Abgeschlossene reguläre Quests / vorhandene reguläre Quests. Herausforderungen separat. Stand am Ende des gewählten Zeitraums.</td></tr><tr><th>Fehlerquote</th><td>Falsche Antwortversuche / alle Antwortversuche im Zeitraum. Ohne Versuche: unbekannt (—).</td></tr><tr><th>Ø Versuche</th><td>Antwortversuche / Aufgabenbearbeitungen mit mindestens einem Versuch. Wiederholung einer Quest ist ein neuer Durchlauf.</td></tr><tr><th>Aufgaben gelöst</th><td>Bearbeitungen mit richtiger Antwort / Bearbeitungen mit mindestens einem Versuch.</td></tr><tr><th>Hilfequote</th><td>Bearbeitungen mit selbst geöffneter Hilfe / Bearbeitungen mit mindestens einem Versuch. Automatische Wissenseinführungen zählen nicht.</td></tr><tr><th>Für später markiert</th><td>Quests mit ausdrücklicher Zurückstellung. Nur Vorwissenswarnungen zu übergehen oder Fenster zu schließen ist keine Zurückstellung.</td></tr><tr><th>Aktive Zeit</th><td>Gemessene Vordergrundzeit in kurzen Intervallen; Pause nach 90 Sekunden ohne Interaktion. Nicht gleichbedeutend mit Konzentration oder Denkzeit. Schätzen bei Absturz wird gekennzeichnet.</td></tr><tr><th>Alte Spielstände</th><td>Vorhandener Queststatus bleibt erhalten. Historische Versuche, Hilfen und Zeiten können nicht nachträglich rekonstruiert werden.</td></tr></tbody></table></div></section>
 <section class="card"><h2>Transparente Hinweiskriterien</h2><p class="muted small">Zentral änderbar in <code>js/analytics.js → RULES</code>. Keine pädagogische Diagnose. Zeitwerte allein führen zu keiner Priorisierung.</p><div class="table-scroll"><table><tbody><tr><th>Mindestdaten</th><td>${RULES.minimumAttemptedRuns} beobachtete Aufgabenbearbeitungen mit Antworten für Schwierigkeitshinweise.</td></tr><tr><th>Wiederholte Schwierigkeiten</th><td>Mindestens ${pct(RULES.errorRate)} Fehlversuche UND Ø mindestens ${RULES.averageAttempts} Versuche.</td></tr><tr><th>Unterstützung abstimmen</th><td>Mindestens ${pct(RULES.helpRate)} mit Hilfe, weniger als ${pct(RULES.lowSuccess)} gelöst UND mindestens ${pct(RULES.errorRate)} Fehlversuche.</td></tr><tr><th>Zurückgestellte Inhalte</th><td>Mindestens ${pct(RULES.skipRate)} der regulären Quests ausdrücklich für später markiert; höhere Priorität nur zusammen mit Fehlerdaten.</td></tr><tr><th>Zusätzliche Herausforderung</th><td>Mindestens ${pct(RULES.stretchFirstTry)} beim ersten Versuch richtig, ${pct(RULES.stretchProgress)} regulärer Fortschritt und ${RULES.stretchChallengeCompleted} erfolgreiche Challenge.</td></tr><tr><th>Nach Versuchen erfolgreich</th><td>Mindestens ${RULES.persistenceAttempts} Versuche, selbst gewählte Hilfe und anschließende richtige Antwort.</td></tr></tbody></table></div></section>`;
 $('backupAll').onclick=async()=>{try{downloadJSON(await db.backup(),'Kommaland_Lehrkraefte_Sicherung_'+localDay(new Date().toISOString())+'.json');toast('Die vollständige Sicherung ist zum Speichern bereit.');}catch(e){toast(e.message);}};
 $('requestPersist').onclick=async()=>{try{const ok=await navigator.storage?.persist?.();$('persistResult').textContent=ok?'Dauerhafter Speicher wurde gewährt. Bewusstes Löschen kann Daten weiterhin entfernen.':'Der Browser hat dauerhaften Speicher nicht zugesichert. Regelmäßige Backups bleiben wichtig.';}catch(e){$('persistResult').textContent=e.message;}};
 $('clearAll').onclick=()=>confirm('Den gesamten lokalen Bestand löschen?','Alle importierten Personen, Ereignisse und Importprotokolle werden in dieser Ansicht gelöscht. Sichere den Bestand vorher. Dateien außerhalb dieses Browsers bleiben unverändert.',async()=>{await db.clear();className='';navigate('overview');toast('Der lokale Datenbestand wurde gelöscht.');});$('demoMode').onclick=openDemo;bind();
}
function bind(){
 document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));
 document.querySelectorAll('[data-action="import"]').forEach(b=>b.onclick=openImport);
 document.querySelectorAll('[data-action="demo"]').forEach(b=>b.onclick=openDemo);
 content.querySelectorAll('[data-student]').forEach(b=>b.onclick=()=>{selectedStudent=b.dataset.student;page='detail';detailTab='overview';taskPage=eventPage=0;refresh();window.scrollTo(0,0);});
 content.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{topic=b.dataset.topic;navigate('topics');});
 content.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{const key=b.dataset.sort;tableState.descending=tableState.sort===key?!tableState.descending:key!=='name';tableState.sort=key;$('learnerTable').innerHTML=learnerTable(report.rows,tableState);bind();});
 content.querySelectorAll('[data-detailtab]').forEach(b=>b.onclick=()=>{detailTab=b.dataset.detailtab;renderDetail();});
 content.querySelectorAll('[data-taskpage]').forEach(b=>b.onclick=()=>{taskPage=+b.dataset.taskpage;renderDetail();});
 content.querySelectorAll('[data-eventpage]').forEach(b=>b.onclick=()=>{eventPage=+b.dataset.eventpage;renderDetail();});
 content.querySelectorAll('[data-day]').forEach(b=>{const click=()=>{$('dateTo').value=b.dataset.day;$('rangePreset').value='custom';applyRange();};b.onclick=click;b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();click();}};});
}
function openImport(){if(!$('importDialog').open)$('importDialog').showModal();}
$('closeImport').onclick=()=>{if(!busy)$('importDialog').close();};$('importDialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
$('dropZone').onclick=()=>{if(!busy){$('fileInput').value='';$('fileInput').click();}};$('dropZone').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('dropZone').click();}};
for(const type of ['dragenter','dragover'])$('dropZone').addEventListener(type,e=>{e.preventDefault();$('dropZone').classList.add('dragover');});
for(const type of ['dragleave','drop'])$('dropZone').addEventListener(type,e=>{e.preventDefault();$('dropZone').classList.remove('dragover');});
$('dropZone').addEventListener('drop',e=>processFiles([...e.dataTransfer.files]));$('fileInput').onchange=e=>processFiles([...e.target.files]);
function progressUpdate(p){$('importProgress').textContent=(p.processed!==undefined?`${p.processed} Dateien verarbeitet · ${p.imported||0} ergänzt · ${p.duplicate||0} vorhanden · ${p.invalid||0} ungültig. `:'')+(p.current||'');}
async function processFiles(files){
 if(!files.length||busy)return;busy=true;openImport();$('closeImport').disabled=true;$('finishImport').hidden=true;$('importResults').replaceChildren();progressUpdate({current:'Dateien werden lokal geprüft …'});
 try{
  let result;
  if(typeof Worker==='undefined')result=await importFiles(files,db,progressUpdate);
  else result=await new Promise((resolve,reject)=>{let w;try{w=new Worker(new URL('./import-worker.js',import.meta.url),{type:'module'});}catch{importFiles(files,db,progressUpdate).then(resolve,reject);return;}w.onmessage=e=>{if(e.data.type==='progress')progressUpdate(e.data.progress);else if(e.data.type==='done'){w.terminate();resolve(e.data.result);}else{w.terminate();reject(new Error(e.data.message));}};w.onerror=()=>{w.terminate();reject(new Error('Der lokale Import-Worker konnte nicht gestartet werden. Prüfe, ob alle App-Dateien hochgeladen wurden.'));};w.postMessage({files,databaseName:demo?BASE_NAME+':demo':BASE_NAME});});
  $('importResults').innerHTML=`<div class="import-summary"><strong>${result.processed} Dateien verarbeitet</strong><p>${result.imported} erfolgreich ergänzt · ${result.duplicate} vollständig vorhanden · ${result.invalid} ungültig${result.ignored?' · '+result.ignored+' ignoriert':''}</p><p>${result.eventsAdded} neue Ereignisse · ${result.eventsIgnoredAsDuplicates} doppelte Ereignisse ignoriert</p></div>${result.results.some(r=>r.status==='invalid')?`<details open><summary>Ungültige Dateien ansehen</summary><ul class="import-errors">${result.results.filter(r=>r.status==='invalid').map(r=>`<li><strong>${esc(r.fileName)}</strong><br>${esc(r.error)}</li>`).join('')}</ul></details>`:''}`;
  $('importProgress').textContent='Import abgeschlossen. Die Dateien wurden nicht hochgeladen.';$('finishImport').hidden=false;await refresh();
 }catch(e){$('importProgress').textContent='Import nicht vollständig abgeschlossen: '+e.message;toast(e.message);await refresh();}
 finally{busy=false;$('closeImport').disabled=false;}
}
$('finishImport').onclick=()=>{$('importDialog').close();navigate('overview');};
async function openDemo(){
 demo=true;worker?.terminate();worker=null;db=new TeacherDB(BASE_NAME+':demo');$('demoBanner').hidden=false;className='';$('dateFrom').value='';$('dateTo').value='';range=dateRange('','');
 content.innerHTML='<div class="loading-card">Die getrennte Demoklasse wird vorbereitet …</div>';
 try{if(!(await db.all('students')).length)for(let i=0;i<12;i++){await db.merge(makeDemoSave(i),'Synthetische Demo '+(i+1));await db.setClass('demo-student-'+i,'Demo 6a');}navigate('overview');}catch(e){failure(e);}
}
$('leaveDemo').onclick=()=>{demo=false;worker?.terminate();worker=null;db=new TeacherDB(BASE_NAME);$('demoBanner').hidden=true;className='';navigate('overview');};
function applyRange(){const from=$('dateFrom').value,to=$('dateTo').value;if(from&&to&&from>to){toast('Der Beginn muss vor dem Ende des Zeitraums liegen.');return;}range=dateRange(from,to);eventPage=taskPage=0;refresh();}
$('applyRange').onclick=applyRange;$('classFilter').onchange=e=>{className=e.target.value;refresh();};
$('rangePreset').onchange=async e=>{if(e.target.value==='custom')return;if(e.target.value==='all'){$('dateFrom').value=$('dateTo').value='';applyRange();return;}const students=await db.all('students'),last=students.map(s=>s.latestExportAt).sort().at(-1)||new Date().toISOString(),end=localDay(last),start=new Date(end+'T12:00:00');if(e.target.value==='week')start.setDate(start.getDate()-6);$('dateFrom').value=localDay(start.toISOString());$('dateTo').value=end;applyRange();};
for(const id of ['dateFrom','dateTo'])$(id).onchange=()=>$('rangePreset').value='custom';
// Ask, do not assert, persistence. Storage remains revocable by the device owner.
refresh();

// Optional local offline cache. Failing installation does not prevent online/local analysis.
if('serviceWorker' in navigator&&(location.protocol==='https:'||['localhost','127.0.0.1'].includes(location.hostname))){
 navigator.serviceWorker.register(new URL('../sw.js',import.meta.url),{scope:new URL('../',import.meta.url).pathname}).catch(error=>console.info('Offline-Dateien der Lehrkräfte-App nicht installiert:',error.message));
}
