import {difficultyView,FIT_LABELS} from '../shared/difficulty.js';
import {LEARNING_GOALS} from '../shared/learning7-content.js';
import {CATALOG} from '../shared/catalog.js';
import {esc,dateTime,duration} from './view-helpers.js';
const title=id=>CATALOG.quests.find(q=>q.questId===id)?.title||id;
const frequency=q=>q.counts.filter(x=>x.attempted).map(x=>'Niveau '+x.level+': '+x.attempted+' Bearbeitung'+(x.attempted===1?'':'en')).join(' · ')||'Noch keine Bearbeitung mit dokumentiertem Niveau';
function decisionText(e){const d=e.data;
 if(e.type==='v71_level_selected')return `Niveau ${d.fromLevel} → ${d.level} ${d.source==='recommendation'?'nach angenommener Empfehlung':'selbst gewählt'}`;
 if(e.type==='v71_level_offered')return `Niveau ${d.targetLevel} empfohlen: ${d.text}`;
 if(e.type==='v71_level_response')return `Empfehlung für Niveau ${d.targetLevel} ${d.decision==='accepted'?'angenommen':d.decision==='declined'?'abgelehnt':'nicht übernommen'}`;
 return `Niveau ${d.level}: ${FIT_LABELS[d.fit]||'ohne Angabe'} (Selbstauskunft)`;
}
export function compactDifficulty(events,range={}){const v=difficultyView(events,range);return {quests:v.quests.map(q=>({questId:q.questId,selected:q.selected,selectedAt:q.selectedAt,counts:q.counts,unknown:q.unknown,conversation:q.conversation,changes:q.history.filter(e=>e.type==='v71_level_selected'&&e.data.fromLevel!==e.data.level).length,accepted:q.history.filter(e=>e.type==='v71_level_response'&&e.data.decision==='accepted').length,declined:q.history.filter(e=>e.type==='v71_level_response'&&e.data.decision==='declined').length}))};}
export function difficultyClassView(rows){
 const records=rows.filter(r=>r.learning7?.difficulty?.quests.some(q=>q.selected||q.counts.some(x=>x.shown)));
 return `<section class="card difficulty-teacher"><h2>Niveauwahl – eine Lernentscheidung</h2><p>Das Niveau beschreibt die Aufgabe, nicht die Person. Es gibt keine Rangliste und keine Bewertung der Wahl. Gezeigt werden Bearbeitungen, die im Zeitraum aktiv waren, mit ihrem vollständigen Verlauf bis zum Stichtag. Entscheidungen sind zeitlich gefiltert. Die letzte dokumentierte Wahl gilt bis zum Stichtag.</p><details><summary>Niveau-Lernspuren der Klasse anzeigen</summary>${records.length?records.map(r=>`<div class="difficulty-person"><button class="student-link" data-student="${esc(r.student.studentId)}">${esc(r.student.studentName)}</button>${r.learning7.difficulty.quests.filter(q=>q.selected||q.counts.some(c=>c.shown)).map(q=>`<p><strong>${esc(title(q.questId))}</strong><br>${esc(frequency(q))}. ${q.selected?'Zuletzt gewählt: Niveau '+q.selected+'.':'Keine ausdrückliche Wahl dokumentiert.'} ${q.changes} freiwillige Wechsel; ${q.accepted} Empfehlungen angenommen, ${q.declined} abgelehnt.${q.conversation?'<br><em>Gesprächsanlass: mehrfach Niveau 3 mit mehreren Hilfeöffnungen. „Woran entscheidest du, welches Niveau gerade passt?“</em>':''}</p>`).join('')}</div>`).join(''):'<p class="muted">Noch keine Niveau-Lernspuren. Alte Version-7-Leistungen werden nicht rückwirkend mit einem Niveau beschriftet.</p>'}</details></section>`;
}
export function difficultyDetailView(d,range={}){
 const v=difficultyView(d.events,range);
 return `<section class="card difficulty-teacher" id="difficultyEvidence"><h2>Niveauwahl und Bearbeitung</h2><p>Selbst gewählte Anforderungssituationen, keine Fähigkeitswerte. Hilfen sind auf jedem Niveau erlaubt. Angezeigte Bearbeitungen verschiedener Niveaus sind keine gleich schweren Testaufgaben. Für im Zeitraum aktive Bearbeitungen wird der gesamte Verlauf bis zum Stichtag gezeigt, nicht nur der letzte Versuch.</p>${v.quests.length?v.quests.map(q=>`<details class="difficulty-quest"><summary><strong>${esc(title(q.questId))}</strong><span>${q.selected?'Letzte dokumentierte Wahl: Niveau '+q.selected:'Keine ausdrückliche Wahl dokumentiert'}</span></summary><p>${esc(LEARNING_GOALS[q.questId]?.text||'')}</p><p>${esc(frequency(q))}${q.unknown?`. ${q.unknown} ältere Bearbeitungen ohne Niveauinformation.`:''}</p><div class="table-scroll"><table><thead><tr><th>Aufgabenvariante</th><th>Begonnen</th><th>Mit Versuch</th><th>Direkt richtig</th><th>Bewusste Hilfen</th></tr></thead><tbody>${q.counts.map(c=>`<tr><th>Niveau ${c.level}</th><td>${c.shown}</td><td>${c.attempted}</td><td>${c.firstTry}</td><td>${c.helps}</td></tr>`).join('')}</tbody></table></div>${q.conversation?'<aside class="calm-note"><strong>Gesprächsanlass, keine Diagnose:</strong> Bei mindestens drei Niveau-3-Bearbeitungen wurden mehrere Hilfen geöffnet. „Woran entscheidest du, welches Niveau gerade gut passt? Welche Hilfe war nützlich?“ Hilfe allein belegt keine Überforderung.</aside>':''}<details><summary>Entscheidungen im Verlauf</summary><ol class="compact-history">${q.history.slice().reverse().map(e=>`<li><time>${dateTime(e.timestamp)}</time> · ${esc(decisionText(e))}</li>`).join('')||'<li>Keine Entscheidung im gewählten Zeitraum.</li>'}</ol></details><details><summary>Tatsächliche Aufgabenvarianten und Hilfen</summary>${q.runs.map(r=>`<article class="difficulty-run"><strong>${esc(r.slotId)} · ${r.level?'Niveau '+r.level:'Niveau nicht dokumentiert'}</strong><p>${esc(r.title)}</p><p>${dateTime(r.startedAt)} · ${r.attempts.length} Versuche, ${r.errors} Fehlversuche · ${r.helps} Hilfeöffnungen · ${duration(r.duration)} aktive Zeit</p><small>${r.helpTypes.length?'Hilfen: '+esc(r.helpTypes.map(x=>({hint:'Tipp',example:'Beispiel',knowledge:'Wissen',otherHelp:'Wissen/andere Hilfe',solutionStep:'Lösungsschritt'}[x]||x)).join(', ')):'Keine bewusste Hilfeöffnung aufgezeichnet.'}</small></article>`).join('')}</details></details>`).join(''):'<p class="muted">Keine beobachtete Kernbearbeitung oder Niveauentscheidung in diesem Zeitraum. Ein migrierter Spielstand erhält keine erfundenen historischen Niveauentscheidungen.</p>'}<p class="muted small">„Direkt richtig“ bedeutet: eine richtige Antwort im ersten beobachteten Versuch. Es ist keine Aussage über eine Person. Aktive Zeit wird nur als Kontext gezeigt; sie löst keine Niveauempfehlung aus.</p></section>`;
}
