import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {freshState,restoreState,correctClaims,steps,warmupSteps,witnessSteps,allTasks,checkAnswer,taskCount,quests} from '../js/quest-data.js';
import {cast} from '../js/people.js';
import {cell,canMove} from '../js/movement.js';
test('Five short quests each have only their assigned new core and varied formats',()=>{assert.equal(taskCount,30);assert.deepEqual(quests.map(q=>q.newCore),[null,'endigkeit','i-formen','funktion','adverb']);for(const q of quests){const tasks=allTasks.filter(t=>t.chapter===q.id&&t.type!=='lesson');assert.ok(tasks.length>=5&&tasks.length<=7);assert.ok(new Set(tasks.map(t=>t.type)).size>=2);}assert.ok(allTasks.filter(t=>t.type==='input').every(t=>t.hints.length===3));assert.ok(steps.filter(t=>t.chapter==='q2').every(t=>t.type!=='input'));});
test('Latin input tolerates macrons but not wrong endings',()=>{const t=steps.find(t=>t.id==='a3f');assert.ok(checkAnswer(t,'  FELICĪ. '));for(const x of ['felice','felix','felicem',''])assert.equal(checkAnswer(t,x),false);});
test('Known KNG can be clarified without claiming an independent correct answer',()=>{const s=freshState();s.stage='warmup';s.answers['first-question']='Wer hat etwas gesehen?';s.solved['first-question']=true;s.answers['start-noun']='tabulam';s.attempts['start-noun']=1;s.clarified['start-noun']=true;s.solved['start-noun']=true;const r=restoreState(s);assert.equal(r.warmupIndex,2);assert.equal(checkAnswer(warmupSteps.find(t=>t.id==='start-noun'),r.answers['start-noun']),false);});
test('New material and its memories are introduced in separate quests before use',()=>{assert.ok(steps.findIndex(t=>t.id==='q3-start')<steps.findIndex(t=>t.id==='a3e'));assert.ok(steps.findIndex(t=>t.id==='functions')>steps.findIndex(t=>t.id==='q3-end'));assert.ok(witnessSteps.find(t=>t.id==='new-er'));assert.ok(!steps.filter(t=>t.chapter==='q2').some(t=>t.cards?.includes('i-formen')));assert.ok(!steps.find(t=>t.id==='new-abl').word.includes('Ablativ'));});
test('Partial answers and memory survive; restart clears both',()=>{const s=freshState();s.stage='warmup';s.answers['start-noun']='novam';s.memory=['auftrag'];const r=restoreState(s);assert.equal(r.answers['start-noun'],'novam');assert.deepEqual(r.memory,['auftrag']);assert.deepEqual(freshState().memory,[]);});
test('Completion requires all stages, evidence and self-review',()=>{const s=freshState();s.stage='done';assert.equal(restoreState(s).stage,'warmup');for(const t of [...warmupSteps,...steps,...witnessSteps]){s.solved[t.id]=true;if(['input','choice','mark','multi','group'].includes(t.type))s.answers[t.id]=t.answer;if(t.type==='reflection')s.answers[t.id]='Eigene Frage';if(t.type==='writing'){s.answers[t.id]='Eigene Begründung';s.revealed[t.id]=true;s.review[t.id]=t.criteria.map(()=>true);}}assert.equal(restoreState(s).stage,'evidence');s.claims=['Belegt','Nicht belegt','Nein'];assert.equal(restoreState(s).stage,'report');s.answers.report='Eigener Bericht';s.revealed.report=true;s.review.report=[true,true];s.solved.report=true;assert.equal(restoreState(s).stage,'done');assert.equal(correctClaims(['Belegt','Nicht belegt','Ja']),false);});
test('Sextus start and all characters lie on connected navigation',async()=>{const nav=JSON.parse(await readFile(new URL('../assets/navigation.json',import.meta.url),'utf8'));const start=cell(nav,22.4,10.05);assert.ok(start);const seen=new Set([start.index]),queue=[start];for(let i=0;i<queue.length;i++){const a=queue[i],x=nav.x0+a.ix*nav.step,z=nav.z0+a.iz*nav.step;for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx*nav.step,zz=z+dz*nav.step,b=cell(nav,xx,zz);if(b&&!seen.has(b.index)&&canMove(nav,x,z,xx,zz)){seen.add(b.index);queue.push(b);}}}for(const p of cast)assert.ok(seen.has(cell(nav,p.x,p.z)?.index),p.name);});

