// Scope: Q1–Q5 of the progression addendum dated 11 September 2026.
export const quests=[
 {id:'q1',title:'Der Auftrag',topic:'KNG · bekanntes Wissen wieder aufnehmen',newCore:null,result:'Auftrag und erste Frage notiert. Die Spur führt zu Livia.'},
 {id:'q2',title:'Livias Warenliste',topic:'Ein-, zwei- und dreiendige Adjektive',newCore:'endigkeit',result:'Die Wörter sind entschlüsselt und die vorgesehene Lieferung ist identifiziert.'},
 {id:'q3',title:'Der Fehler im Verzeichnis',topic:'i-Adjektive · Stamm und −i / −ia / −ium',newCore:'i-formen',result:'Die beschädigten Einträge sind wieder lesbar. Über Marcus’ Verhalten sagen sie noch nichts aus.'},
 {id:'q4',title:'Was wird über Marcus gesagt?',topic:'Adjektive · Attribut, Prädikatsnomen, Substantivierung',newCore:'funktion',result:'Beschreibung und Selbstbeschreibung sind getrennt. Jetzt fehlt Flavias Beobachtung.'},
 {id:'q5',title:'Flavias Beobachtung',topic:'Adjektiv und Adverb · Eigenschaften und Handlungen',newCore:'adverb',result:'Ankunft belegt; Annahme durch Marcus offen. Der Zwischenbericht ist bei Sextus.'}
];
const lesson=(id,chapter,title,context,text,cards=[],extra={})=>({id,chapter,type:'lesson',title,context,text,cards,...extra});
const choice=(id,chapter,title,context,source,prompt,options,answer,explain,extra={})=>({id,chapter,type:'choice',title,context,source,prompt,options,answer,explain,...extra});
const input=(id,chapter,title,context,source,word,answer,hints,explain,extra={})=>({id,chapter,type:'input',title,context,source,prompt:'Vervollständige deinen Eintrag.',word,answer,hints,explain,wrong:{},...extra});
export const openingTasks=[
 {id:'first-question',chapter:'q1',type:'reflection',title:'Deine erste Frage',context:'Sextus braucht einen verlässlichen Bericht. Noch ist die Nachricht über Marcus nur ein Gerücht.',source:'Marcus dona accipit.',translation:'Marcus nimmt Geschenke an.',sourceLabel:'Gerücht · noch nicht belegt',prompt:'Was möchtest du zuerst herausfinden? Notiere eine Frage oder eine vorläufige Vermutung. Sie wird nicht als richtig oder falsch bewertet.'},
 choice('start-noun','q1','Eine Tafel für den Auftrag','Sextus bittet dich, eine neue Schreibtafel mitzunehmen. Auf dem Zettel steht, welche gemeint ist.','tabulam novam','Welches Wort beschreibt die Tafel?',['tabulam','novam'],'novam','novam beschreibt tabulam. Das Adjektiv richtet sich nach seinem Bezugswort.',{translation:'eine neue Tafel',diagnostic:true}),
 input('start-form','q1','Die Ausgabe festhalten','Sextus bringt die neue Tafel. Du ergänzt den Eintrag zur Ausgabe.','Sextus tabulam ___ portat.','novus, -a, -um = neu · tabulam: Akkusativ Singular Femininum · portat = trägt','novam',['Suche das Wort für die Tafel.','tabulam ist Akkusativ Singular Femininum.','Vergleich: amphoram parvam – eine kleine Amphore.'],'tabulam novam: Akkusativ Singular Femininum.',{diagnostic:true}),
 choice('known-kng','q1','Was soll auf die Tafel?','Sextus nennt die Art der Ware. Du erinnerst dich an die bekannte a-/o-Deklination.','dona parva','Welche Merkmale teilen die Wörter in dieser Wortgruppe im Nominativ?',['Nominativ Singular Femininum','Nominativ Plural Neutrum','Akkusativ Singular Maskulinum'],'Nominativ Plural Neutrum','dona parva: kleine Geschenke, Nominativ Plural Neutrum. Das ist bekanntes KNG-Wissen.',{diagnostic:true,translation:'kleine Geschenke'}),
 choice('first-way','q1','Die erste Spur','Sextus: „Livia führt das Warenverzeichnis. Flavia war beim Abladen dabei. Beginne mit der Liste: Welche Lieferung ist überhaupt gemeint?“',null,'Wen suchst du für das Warenverzeichnis auf?',['Flavia','Livia','Marcus'],'Livia','Livia führt die Liste. Ihre Angaben und Flavias Beobachtung werden später zusammengeführt.'),
 lesson('start-end','q1','Der Auftrag steht','Sextus: „Nimm deine Tafel. Finde zuerst heraus, welche Waren für Marcus bestimmt sind.“','Meine Frage bleibt im Journal. Bei Livia beginne ich mit den Beschreibungen der Waren.',['basis'],{end:true})
];
export const listTasks=[
 choice('discover','q2','Die Wörter auf den Schildern','Livia: „Hilf mir, diese Wörter zu entschlüsseln. Manche sehen bei Personen und Waren gleich aus, andere wechseln.“','vir gravis · femina gravis · vas grave','Welche Geschlechter teilen sich die Form gravis?',['Maskulinum und Neutrum','Maskulinum und Femininum','Femininum und Neutrum'],'Maskulinum und Femininum','gravis gilt im Nominativ Singular für m. und f.; grave für n. Zwei Formen: zweiendig.',{translation:'ein ernsthafter Mann · eine ernsthafte Frau · ein schweres Gefäß'}),
 lesson('words','q2','Drei Arten von Einträgen','Auf Livias Worttafel stehen die Formen, die du zum Lesen ihrer Beschreibungen brauchst.','Ich zähle nur die Nominativformen für m., f. und n. Ein Genitiv in Klammern zählt nicht als zweite Nominativform.',['endungen']),
 {id:'sort-types',chapter:'q2',type:'group',title:'Die Worttafel ordnen',context:'Livia möchte gleichartige Wörter beisammenhaben, damit die Schilder schneller lesbar werden.',prompt:'Ordne die vollständigen Wörterbucheinträge nach ihren Nominativformen.',items:[['celer','celer, celeris, celere = schnell'],['felix','felix (Gen. felicis) = glücklich'],['gravis','gravis, grave = schwer']],slots:['einendig','zweiendig','dreiendig'],answer:{celer:'2',felix:'0',gravis:'1'},explain:'felix: eine Nominativform; gravis/grave: zwei; celer/celeris/celere: drei.',hints:['Gezählt werden die Formen für m., f. und n.','Der Genitiv ist eine Stammhilfe, keine weitere Nominativform.','felix bleibt im Nominativ für alle drei Genera gleich.']},
 {id:'nom-only',chapter:'q2',type:'mark',title:'Was zählt wirklich?',context:'Ein Randvermerk könnte dich beim Zählen in die Irre führen.',source:'felix · Genitiv: felicis',tokens:['felix','felicis'],prompt:'Markiere nur die Nominativform, die für die Einendigkeit zählt.',answer:['0'],explain:'felicis ist ein Genitiv. Im Nominativ heißt es für alle drei Genera felix.'},
 choice('meaning-one','q2','Eine missverständliche Notiz','Neben felix hat jemand „unveränderlich“ notiert. Du korrigierst die Erklärung.','felix (Genitiv felicis)','Welche Begründung gehört in deine Notiz?',['Einendig heißt: Im Nominativ Singular gibt es eine Form für alle drei Genera.','Einendig heißt: Das Wort hat in allen Kasus dieselbe Form.'],'Einendig heißt: Im Nominativ Singular gibt es eine Form für alle drei Genera.','Einendig beschreibt die Nominativformen, nicht das gesamte Paradigma.'),
 choice('transfer-audax','q2','Ein neues Wort am Rand','Für eine Personenbeschreibung findest du einen weiteren vollständigen Wörterbucheintrag.','audax (für m., f., n.; Genitiv audacis) = kühn','Zu welcher Gruppe gehört das Wort?',['zweiendig','dreiendig','einendig'],'einendig','audax gilt im Nominativ für alle drei Genera. audacis ist wieder nur die Genitivangabe.'),
 choice('identify-load','q2','Die vorgesehene Lieferung','Livia zeigt dir die Liste für Marcus. Jetzt kannst du die Warenbezeichnung lesen.','Marcus · unum vas grande; duo vasa parva','Welche Waren sind hier vorgesehen?',['Ein großes Gefäß und zwei kleine Gefäße.','Drei große Gefäße.','Ein kleines Gefäß und zwei große Gefäße.'],'Ein großes Gefäß und zwei kleine Gefäße.','Die Liste nennt ein großes und zwei kleine Gefäße. grandis/grande ist zweiendig; parvus gehört zur bekannten a-/o-Deklination.',{word:'unum = ein · duo = zwei · vas = Gefäß · grandis, grande = groß · parvus, -a, -um = klein'}),
 lesson('q2-end','q2','Livias Warenliste ist entschlüsselt','Livia: „Genau diese Waren sind für Marcus vorgesehen. Einige Einträge sind beschädigt. Hilfst du mir danach beim Ergänzen?“','Die Lieferung ist identifiziert. Ob Marcus sie angenommen hat, ist damit noch nicht geklärt.',['waren'],{end:true}),
 lesson('q3-start','q3','Die beschädigten Zeilen','Livia: „Die Wortgruppen stehen fest, aber einzelne Endungen fehlen. Lass uns das Verzeichnis wieder lesbar machen.“','Bekanntes KNG hilft: Das Adjektiv übernimmt die Merkmale des Nomens. Neu sind der Stamm und die Formen der i-Adjektive.',['kng','i-formen']),
 input('find-stem','q3','Den Stamm retten','Der Genitiv auf einer Randnotiz ist noch lesbar. Damit rekonstruierst du den Stamm.','felix · Genitiv felicis → Stamm: ___','felix = glücklich · Der Genitiv endet auf -is.','felic',['Schau auf felicis.','Entferne beim Genitiv die Endung -is.','gravis → grav-; der Stamm wird ohne die Genitivendung notiert.'],'felicis ohne -is ergibt felic-.',{accepted:['felic','felic-']}),
 input('a3e','q3','Mehrere große Geschenke','In deiner Abschrift des Gerüchts fehlt die Beschreibung. Die Aussage bleibt ausdrücklich ungeprüft.','Marcus dona ___ accipit.','grandis, grande = groß · dona: Akkusativ Plural Neutrum · accipit = nimmt an','grandia',['Beachte Plural und Neutrum.','Hier braucht das i-Adjektiv -ia.','Vergleich: vasa gravia – schwere Gefäße.'],'dona grandia: Akkusativ Plural Neutrum.'),
 input('a3f','q3','Mit einem Freund','Ein Begleiter soll in der Abschrift als glücklich beschrieben bleiben.','cum amico ___','felix (Gen. felicis) = glücklich · amico: Ablativ Singular Maskulinum','felici',['cum verlangt den Ablativ.','Verbinde felic- mit -i.','Vergleich: cum viro gravi – mit einem ernsthaften Mann.'],'cum amico felici: gleicher Kasus, Numerus und gleiches Genus, verschiedene Endungen.'),
 input('a4b','q3','Die Zählzeile','Livia: „Von den großen Gefäßen ist eines in dieser Lieferung. Ergänze die Beschriftung der Anzahl.“','Numerus vasorum ___: I.','grandis, grande = groß · numerus = Zahl · vasorum = der Gefäße · I = 1','grandium',['„Der Gefäße“ ist Genitiv Plural.','i-Adjektive brauchen hier -ium.','Vergleich: donorum felicium – der glückbringenden Geschenke.'],'vasorum grandium: Genitiv Plural Neutrum.'),
 {id:'reverse-grandia',chapter:'q3',type:'multi',title:'Eine Form, zwei Möglichkeiten',context:'Auf einem losen Streifen ist nur die Adjektivform erhalten. Du trägst nicht mehr ein, als du erkennen kannst.',source:'grandia',prompt:'Welche beiden Deutungen bleiben ohne Satzkontext möglich?',options:['Ablativ Singular Maskulinum','Nominativ Plural Neutrum','Genitiv Plural Neutrum','Akkusativ Plural Neutrum'],answer:['Nominativ Plural Neutrum','Akkusativ Plural Neutrum'],explain:'Bei Neutra stimmen Nominativ und Akkusativ überein. Erst der Satz klärt die Funktion.'},
 input('new-abl','q3','Eine andere Beschreibung','In einer neuen Gesprächsnotiz beschreibst du den Händler als klug.','Livia cum mercatore ___ loquitur.','prudens (Gen. prudentis) = klug · mercator = Händler · loquitur = spricht','prudenti',['Welche Form verlangt cum?','prudentis zeigt den Stamm prudent-. Der Ablativ Singular endet auf -i.','Vergleich: cum amico felici – mit einem glücklichen Freund.'],'cum mercatore prudenti: Ablativ Singular Maskulinum. Das neue Wort folgt demselben Verfahren.'),
 lesson('q3-end','q3','Das Verzeichnis ist lesbar','Livia: „Die beschädigten Zeilen sind ergänzt. Doch Warenbeschreibungen sind noch kein Urteil über Marcus.“','Als Nächstes trenne ich, wie Menschen beschrieben werden und was tatsächlich über sie ausgesagt wird.',[],{end:true}),
 lesson('functions','q4','Von der Ware zur Person','Livia: „Marcus nennt sich einen guten Mann. Lies seine Worte selbst, bevor du ein Urteil über ihn aufschreibst.“','Neu ist, wie ein Adjektiv im Satz verwendet wird: beim Nomen, als Aussage mit est oder als Bezeichnung für Personen und Dinge.',['funktion'],{travel:true}),
 {id:'attribute',chapter:'q4',person:'marcus',type:'mark',title:'Eine Person beschreiben',context:'Vor Marcus liegt ein kurzer Vermerk über einen ankommenden Mann.',source:'Vir clarus venit.',translation:'Ein berühmter Mann kommt.',tokens:['Vir','clarus','venit.'],prompt:'Markiere das Adjektiv, das direkt zum Nomen vir gehört.',answer:['1'],explain:'clarus ist Attribut zu vir. Es beschreibt den Mann innerhalb der Wortgruppe.'},
 choice('predicate','q4','Marcus’ Selbstbeschreibung','Marcus: „So wird über mich gesprochen.“ Du liest, was die Zeile behauptet.','Marcus bonus est.','Welche Aufgabe hat bonus in diesem Satz?',['Attribut zu einem ausdrücklich genannten Nomen in einer Wortgruppe','Prädikatsnomen mit est','Substantiviertes Adjektiv'],'Prädikatsnomen mit est','bonus bildet mit est die Aussage: Marcus ist gut.',{person:'marcus',translation:'Marcus ist gut.'}),
 choice('substantive','q4','Wer ist mit den Guten gemeint?','Auf einer weiteren Tafel werden Menschen nur mit einer Eigenschaft bezeichnet.','Boni adsunt.','Welche Wiedergabe löst das substantivierte Adjektiv passend auf?',['Die Guten sind da.','Die guten Geschenke sind da.','Sie sind auf gute Weise da.'],'Die Guten sind da.','boni steht hier selbst für gute Menschen; ein Nomen ist nicht ausgedrückt.',{person:'marcus',word:'boni: Nominativ Plural Maskulinum · adsunt = sind da'}),
 {id:'sort-functions',chapter:'q4',person:'marcus',type:'group',title:'Die Vermerke auseinanderhalten',context:'Du ordnest drei Formulierungen, damit ihre sprachliche Funktion im Bericht klar bleibt.',prompt:'Ordne die Verwendung des hervorgehobenen Adjektivs zu.',items:[['s','BONI adsunt. – Die Guten sind da.'],['a','Vir CLARUS venit. – Ein berühmter Mann kommt.'],['p','Marcus BONUS est. – Marcus ist gut.']],slots:['Attribut','Prädikatsnomen','substantiviert'],answer:{s:'2',a:'0',p:'1'},explain:'clarus gehört zu vir; bonus bildet mit est die Aussage; boni bezeichnet hier selbst Menschen.'},
 {id:'functions-writing',chapter:'q4',person:'marcus',type:'writing',title:'Deine knappe Zusammenfassung',context:'Du hältst den Unterschied für deinen Bericht fest.',source:'Vir bonus venit. Vir bonus est. Boni adsunt.',prompt:'Übersetze die drei Sätze und notiere jeweils die Verwendung von bonus/boni.',word:'vir = Mann · venit = kommt · est = ist · adsunt = sind da',model:'Ein guter Mann kommt: Attribut. Der Mann ist gut: Prädikatsnomen. Die Guten sind da: substantiviertes Adjektiv.',criteria:['Die drei Aussagen sinngemäß wiedergegeben.','Attribut, Prädikatsnomen und substantivierten Gebrauch passend zugeordnet.']},
 choice('claim-limit','q4','Eine Aussage ist noch kein Verhalten','Marcus’ Tafel bleibt eine Selbstbeschreibung. Du willst sie nicht als Beobachtung ausgeben.','Marcus bonus est.','Was darf in deinen Bericht?',['Marcus hat deshalb sicher kein Geschenk angenommen.','Marcus beschreibt sich als gut; seine Handlung ist damit nicht belegt.'],'Marcus beschreibt sich als gut; seine Handlung ist damit nicht belegt.','Die sprachliche Aussage ist verständlich. Ob sie Marcus’ Verhalten trifft, muss an Belegen geprüft werden.',{person:'marcus'}),
 lesson('q4-end','q4','Jetzt zählt die Beobachtung','Marcus: „Flavia war beim Abladen am Stand. Frage sie, was sie gesehen hat.“','Ich habe Beschreibung und Behauptung getrennt. Nun brauche ich eine Aussage über die Handlung.',[],{person:'marcus',end:true})
];
export const witnessTasks=[
 choice('adverb-discover','q5','Flavia erinnert sich','Flavia: „Dama kam schnell mit den Kisten. Halte genau fest, was ich gesehen habe.“','Dama celer est. Dama celeriter venit.','Was beschreibt celeriter im zweiten Satz?',['Welche Eigenschaft die Person hat','Wie Dama kommt'],'Wie Dama kommt','celer ist ein Adjektiv; celeriter beschreibt hier die Art der Handlung.',{translation:'Dama ist schnell. Dama kommt schnell.'}),
 lesson('adverb-rule','q5','Eigenschaft oder Handlung?','Du ordnest Flavias Worte, bevor du ihre Aussage aufschreibst.','Ein Adjektiv beschreibt hier die Person; ein Adverb die Art der Handlung. Neu sind die Bildung auf -e, -iter und bei prudens auf -er.',['adverb']),
 input('new-e','q5','Der Ton ihrer Erzählung','Flavia erzählt zunächst fröhlich von der Ankunft. Du hältst fest, wie sie erzählt.','Flavia ___ narrat.','laetus, -a, -um = fröhlich · narrat = erzählt','laete',['Gesucht ist die Art des Erzählens.','Bei laetus wird -us durch -e ersetzt.','Vergleich: clarus → clare.'],'laete beschreibt das Erzählen, nicht das Genus von Flavia.'),
 input('new-iter','q5','Trotz des einflussreichen Namens','Flavia zögert kurz, sagt dann aber aus. Du beschreibst ihr Handeln als tapfer.','Flavia ___ agit.','fortis, forte = tapfer · agit = handelt','fortiter',['Gesucht ist die Art des Handelns.','Verbinde fort- mit -iter.','Vergleich: gravis → graviter.'],'fortiter: tapfer handeln. Das Adverb wird nicht nach KNG angeglichen.'),
 input('new-er','q5','Besonnen erzählen','Flavia trennt sorgfältig Gesehenes von Vermutungen. Deine Notiz beschreibt, wie sie erzählt.','Flavia ___ narrat.','prudens (Gen. prudentis) = klug, besonnen','prudenter',['Schau auf den Stamm prudent-.','Bei prudens bildet prudent- + -er das Adverb.','Das Muster steht im Gedächtnis unter „Eigenschaft oder Handlung?“.'],'prudent- + -er → prudenter. Hier darfst du nicht einfach -iter anhängen.'),
 {id:'sort-adverbs',chapter:'q5',type:'group',title:'Person und Handlung trennen',context:'Du legst die Beschreibungen in zwei Fächer deiner Mitschrift.',prompt:'Ordne jeweils das hervorgehobene Wort zu.',items:[['a','Dama CELER est.'],['b','Dama CELERITER venit.'],['c','Flavia PRUDENTER narrat.'],['d','Flavia LAETA est.']],slots:['Adjektiv · Eigenschaft','Adverb · Art der Handlung'],answer:{a:'0',b:'1',c:'1',d:'0'},explain:'celer und laeta beschreiben Personen; celeriter und prudenter die Art einer Handlung.'},
 lesson('testimony','q5','Die Grenze ihrer Beobachtung','Flavia: „Schreib auch auf, dass ich danach fortging. Was später geschah, weiß ich nicht.“','Ich verbinde jetzt das Verzeichnis mit ihrer Aussage. Eine unbeobachtete Übergabe ist nicht dasselbe wie eine ausgeschlossene Übergabe.',['liste','zeugin','beleg'])
];
export const closingTask={id:'report',chapter:'q5',person:'sextus',type:'writing',title:'Der Zwischenbericht an Sextus',context:'Sextus: „Was hast du über die Lieferung herausgefunden? Die weiteren Nachrichten werden wir später untersuchen.“',prompt:'Schreibe zwei Sätze: Was ist belegt, welche Quellen tragen es und was bleibt offen?',model:'Lieferung L kam bei Livia an: Das zeigen ihr Verzeichnis und Flavias Beobachtung. Eine Annahme durch Marcus ist nicht belegt; eine spätere Übergabe kann Flavia nicht ausschließen.',criteria:['Verzeichnis und Flavia als Quellen genannt.','Ankunft bestätigt; Annahme durch Marcus offen gelassen.']};
for(const t of [...openingTasks,...listTasks,...witnessTasks,closingTask]){t.sourceLabel??='Auf der Tafel';t.person??=t.chapter==='q1'?'sextus':t.chapter==='q5'?'flavia':'livia';}
