export const messageQuests=[
 {id:'q6',title:'Damas erste Nachricht',topic:'Relativsatz und relativer Satzanschluss',newCore:'rsa',result:'Zwei Fassungen sind lesbar. Die zweite Nachricht muss noch zugeordnet werden.'},
 {id:'q7',title:'Damas zweite Nachricht',topic:'Relativer Satzanschluss · Bezug, Kasus und Aussageabsicht',newCore:'rsa-kasus',result:'Der Händler erwartet Hilfe. Ein Versprechen von Marcus ist nicht belegt.'}
];
export const messageMemory={
 rsa:{title:'Relativsatz oder Satzanschluss?',text:'Ein gewöhnlicher Relativsatz erläutert ein Bezugswort innerhalb eines Satzgefüges: Dama, qui epistulam portat, venit – Dama, der einen Brief trägt, kommt. Ein relativer Satzanschluss führt die Aussage des vorigen Satzes weiter: Dama venit. Qui epistulam portat – Dama kommt. Dieser trägt einen Brief. Entscheidend ist der Zusammenhang, nicht allein ein Punkt oder die erste Wortposition.',example:'Im Anschluss wird qui/quae/quod mit einem passenden Demonstrativpronomen wiedergegeben. Und, aber oder also nur ergänzen, wenn der Zusammenhang es verlangt.'},
 'rsa-kasus':{title:'Bezug und eigene Satzfunktion',text:'Genus und Numerus kommen vom Bezugswort. Der Kasus ergibt sich aus der Aufgabe des Pronomens in seinem eigenen Satz. Marcus adest. Quem Dama salutat: Marcus ist da. Diesen begrüßt Dama. Marcus ist Nominativ, quem Akkusativobjekt. Dama ist das Subjekt des zweiten Satzes.',example:'Maskulinum Singular: qui (Nom.), quem (Akk.), cui (Dat.). Femininum Singular: quae (Nom.), quam (Akk.), cui (Dat.). Neutrum Plural: quae (Nom./Akk.). Der Satz entscheidet bei mehrdeutigen Formen.'},
 nachrichten:{title:'Damas Nachrichten',source:'Mercator dona mittit. Qui auxilium exspectat. Marcus adest. Cui mercator epistulam mittit.',text:'Der Händler schickt Geschenke und erwartet Hilfe. Er schickt Marcus einen Brief. Diese Formulierungen belegen die Erwartung des Händlers, aber weder ein Versprechen von Marcus noch dessen Annahme der Geschenke.'}
};
const lesson=(id,chapter,title,context,cards)=>({id,chapter,type:'lesson',title,context,prompt:'Ich halte das für die Abschrift fest.',cards});
const writing=(id,chapter,title,context,source,prompt,word,model,criteria)=>({id,chapter,type:'writing',title,context,source,prompt,word,model,criteria});
export const messageTasks=[
 lesson('dama-start','q6','Zwei Fassungen eines Briefes','Dama: „Sextus schickt dich? Auf meinen Tafeln stehen zwei Fassungen. Hilf mir, eine verständliche Abschrift anzufertigen, ohne die Aussage zu verändern.“',['rsa']),
 {id:'rsa-mark','chapter':'q6',type:'mark',title:'Die eingeschobenen Angaben',context:'Du grenzt in der ersten Fassung die näheren Angaben ab, damit Dama beim Abschreiben keinen Teil verliert.',source:'Dama, qui epistulam portat, venit. Livia, quae merces numerat, eum videt.',tokens:['Dama,','qui','epistulam','portat,','venit.','Livia,','quae','merces','numerat,','eum','videt.'],prompt:'Markiere sämtliche Wörter der beiden eingebetteten Relativsätze, einschließlich ihrer Pronomen.',answer:['1','2','3','6','7','8'],word:'epistula = Brief · portat = trägt · merces = Waren · numerat = zählt · eum videt = sieht ihn',explain:'qui epistulam portat erläutert Dama; quae merces numerat erläutert Livia. venit und videt gehören zu den übergeordneten Aussagen.'},
 {id:'rsa-sort',chapter:'q6',type:'group',title:'Die Fassungen sortieren',context:'Dama legt vier Textstreifen vor dich. Zwei erläutern eine Person innerhalb eines Satzgefüges, zwei erzählen mit einem Anschluss weiter.',prompt:'Ordne nach der Funktion des Relativpronomens im ganzen Zusammenhang.',slots:['Relativsatz · nähere Angabe','Satzanschluss · neue Aussage'],items:[['a','Dama, qui epistulam portat, venit.'],['b','Livia adest. Quae merces numerat.'],['c','Quae merces numerat, ea Livia est.'],['d','Dama venit. Qui epistulam portat.']],answer:{a:'0',b:'1',c:'0',d:'1'},word:'adest = ist da · ea = diese · c: Diejenige, die die Waren zählt, ist Livia.',explain:'Auch ein Relativsatz kann vorne stehen: In c gehört quae merces numerat zu ea. In b und d führt das Pronomen einen abgeschlossenen Satz weiter.'},
 writing('rsa-copy','q6','Die neue Abschrift','Dama braucht die zweite Fassung als verständliche deutsche Notiz für Sextus.','Dama venit. Qui epistulam portat. Livia adest. Quae merces numerat.','Übersetze den Text. Mache die beiden Anschlüsse durch passende Demonstrativpronomen deutlich.','venit = kommt · epistulam portat = trägt einen Brief · adest = ist da · merces numerat = zählt Waren','Dama kommt. Dieser trägt einen Brief. Livia ist da. Diese zählt die Waren. Ein verbindendes „und“ ist möglich; ein Gegensatz wird nicht behauptet.',['Alle vier Aussagen mit den richtigen handelnden Personen wiedergegeben.','Qui und quae als Anschlüsse mit dieser/diese oder sinngemäß aufgelöst.','Keinen unbelegten Gegensatz durch „aber“ hinzugefügt.']),
 {id:'rsa-reasons',chapter:'q6',type:'multi',title:'Eine falsche Randregel',context:'Am Rand steht: „Ein Relativpronomen am Satzanfang heißt immer aber dieser.“ Du hältst fest, warum Dama diese Regel streichen sollte.',prompt:'Markiere alle fachlich tragfähigen Einwände.',options:['Ein gewöhnlicher Relativsatz kann vor dem übergeordneten Satz stehen.','Jeder Anschluss drückt einen Gegensatz aus.','Die Verbindung muss zum inhaltlichen Zusammenhang passen.','Ein Punkt allein ersetzt keine Analyse des Satzgefüges.','Am Satzanfang ist ein Relativpronomen immer Nominativ.'],answer:['Ein gewöhnlicher Relativsatz kann vor dem übergeordneten Satz stehen.','Die Verbindung muss zum inhaltlichen Zusammenhang passen.','Ein Punkt allein ersetzt keine Analyse des Satzgefüges.'],explain:'Wortposition und Zeichensetzung geben Hinweise, entscheiden aber nicht allein. „Aber“ setzt einen Gegensatz voraus; der Kasus folgt der Satzfunktion.'},
 writing('rsa-transfer','q6','Eine weitere Zeile retten','Ein neuer Streifen liegt unter der ersten Tafel. Dama braucht eine vollständige Abschrift.','Mercator, qui dona mittit, auxilium exspectat. Dama adest. Qui epistulam portat.','Übersetze den Text und begründe, weshalb das erste qui anders eingebunden ist als das zweite.','mercator = Händler · dona mittit = schickt Geschenke · auxilium exspectat = erwartet Hilfe','Der Händler, der Geschenke schickt, erwartet Hilfe. Dama ist da. Dieser trägt einen Brief. Das erste qui leitet die nähere Angabe zu mercator ein; das zweite führt die Aussage über Dama weiter.',['Die Erwartung dem Händler zugeschrieben.','Den eingebetteten Relativsatz und den Anschluss unterschieden und am Satzgefüge begründet.']),
 {...lesson('dama-first-end','q6','Die erste Abschrift steht','Dama: „Danke. Auf der nächsten Tafel geht es darum, wem der Händler schreibt. Lies genau: Wer erwartet hier eigentlich Hilfe?“',[]),end:true},
 lesson('dama-second-start','q7','Wer ist gemeint?','Dama: „Auf der zweiten Tafel sind Endungen beschädigt. Ich weiß noch, wer handelt. Hilf mir, die Bezüge wiederherzustellen.“',['rsa-kasus']),
 {id:'rsa-links',chapter:'q7',type:'group',title:'Die Bezüge sichern',context:'Bevor du etwas ergänzt, ordnest du die lesbaren Anschlusspronomen ihren Bezugswörtern zu.',source:'Marcus adest. Quem Dama salutat. Livia venit. Cui Dama epistulam dat. Dona adsunt. Quae Livia numerat.',prompt:'Ordne jedes Pronomen seinem Bezugswort zu.',word:'salutat = begrüßt · dat = gibt · dona adsunt = Geschenke sind da · numerat = zählt',slots:['Marcus','Livia','Dona'],items:[['a','Quem'],['b','Cui'],['c','Quae']],answer:{a:'0',b:'1',c:'2'},explain:'quem bezieht sich auf Marcus; cui hier auf Livia; quae auf dona. Cui allein legt das Genus nicht fest: Der Zusammenhang ist nötig.'},
 {id:'rsa-quem',chapter:'q7',type:'input',title:'Den Begrüßten ergänzen',context:'Dama begrüßt Marcus. Genau das soll deine ergänzte Abschrift ausdrücken.',source:'Marcus adest. ___ Dama salutat.',word:'qui, quem, cui: Formen im Gedächtnis · salutat = begrüßt',answer:'quem',hints:['Wer begrüßt wen?','Dama handelt; Marcus ist der Begrüßte. Gesucht ist das Akkusativobjekt.','Vergleich: Livia adest. Quam Dama salutat. – Diese begrüßt Dama.'],explain:'Quem: Akkusativ Singular Maskulinum. Der Nominativ Marcus im vorigen Satz wird nicht übernommen.'},
 {id:'rsa-cui',chapter:'q7',type:'input',title:'Die Empfängerin ergänzen',context:'Dama gibt Livia den Brief. Du ergänzt die Empfängerin, nicht den Brief.',source:'Livia venit. ___ Dama epistulam dat.',word:'dat = gibt · epistulam = den Brief',answer:'cui',hints:['Wem gibt Dama den Brief?','Die Empfängerin steht im Dativ Singular.','Vergleich: Marcus adest. Cui Livia donum dat. – Diesem gibt Livia ein Geschenk.'],explain:'Cui ist hier Dativ Singular Femininum; es verweist auf Livia. Epistulam ist das Akkusativobjekt.'},
 {id:'rsa-objects',chapter:'q7',type:'mark',title:'Die betroffenen Personen und Dinge',context:'Dama möchte in seiner Abschrift hervorheben, wen er begrüßt, was er gibt und was Livia zählt.',source:'Marcus adest. Quem Dama salutat. Livia venit. Cui Dama epistulam dat. Dona adsunt. Quae Livia numerat.',tokens:['Marcus','adest.','Quem','Dama','salutat.','Livia','venit.','Cui','Dama','epistulam','dat.','Dona','adsunt.','Quae','Livia','numerat.'],prompt:'Markiere alle Akkusativobjekte im Text. Nimm auch das Nomen auf, nicht nur Anschlusspronomen.',answer:['2','9','13'],word:'salutat = begrüßt · dat = gibt · numerat = zählt',explain:'Quem, epistulam und Quae sind Akkusativobjekte. Cui ist Dativobjekt; Dona ist im ersten Satz Subjekt, obwohl dona wie ein Akkusativ aussieht.'},
 writing('rsa-intent','q7','Die Erwartung richtig zuordnen','Unter der Tafel steht eine fremde Zusammenfassung: „Marcus verspricht dem Händler Hilfe.“ Dama bittet dich, sie am Wortlaut zu prüfen.','Mercator dona mittit. Qui auxilium exspectat. Marcus adest. Cui mercator epistulam mittit.','Übersetze den Text. Korrigiere anschließend die fremde Zusammenfassung mit zwei lateinischen Textbelegen.','mittit = schickt · auxilium = Hilfe · exspectat = erwartet · adest = ist da','Der Händler schickt Geschenke. Dieser erwartet Hilfe. Marcus ist da. Diesem schickt der Händler einen Brief. Qui auxilium exspectat benennt die Erwartung des Händlers; cui mercator epistulam mittit macht Marcus zum Empfänger. Ein Versprechen von Marcus steht hier nicht.',['Qui auf mercator bezogen und den Händler als Erwartenden genannt.','Cui auf Marcus bezogen und ihn als Briefempfänger wiedergegeben.','Zwei Textbelege verwendet und Erwartung von einem unbelegten Versprechen getrennt.']),
 writing('rsa-report','q7','Die Nachricht für Sextus','Dama: „Nimm deine Abschrift mit. Sextus soll erfahren, was die Worte belegen – und was wir noch fragen müssen.“','Mercator dona mittit. Qui auxilium exspectat.','Schreibe die Bedeutung und die Grenze der Nachricht für Sextus auf. Ergänze eine lateinische Notiz: „Dama erzählt besonnen.“','narrat = erzählt · prudens (Gen. prudentis) = besonnen','Der Händler schickt Geschenke und erwartet Hilfe. Eine Erwartung ist kein Beleg für ein Versprechen von Marcus; auch seine Annahme bleibt offen. Dama prudenter narrat.',['Die Erwartung dem Händler zugeschrieben.','Kein Versprechen und keine Annahme durch Marcus als bewiesen dargestellt.','Dama prudenter narrat mit dem passenden Adverb ergänzt.']),
 {...lesson('dama-end','q7','Die nächste Frage betrifft das Amt','Sextus: „Jetzt ist klar, wessen Erwartung wir lesen. Als Nächstes müssen wir klären, welches Amt Marcus anstrebt und welche Hilfe überhaupt in dessen Zuständigkeit läge.“',['nachrichten']),person:'sextus',end:true}
];
for(const t of messageTasks){t.person??='dama';t.sourceLabel??='Damas Tafel';}
