export const RUFUS_KEY='forum-rufus-v1';
export const intro={latin:'Salve! Tabulae meae confusae sunt. Adiuva me, quaeso.',translation:'Sei gegrüßt! Meine Tafeln sind durcheinandergeraten. Hilf mir bitte.'};
export const glossary={salve:'sei gegrüßt',tabulae:'Tafeln',meae:'meine',confusae:'durcheinandergeraten',sunt:'sind',adiuva:'hilf',me:'mir / mich',quaeso:'bitte',scribe:'schreibe',elige:'wähle',lege:'lies',ordina:'ordne',corrige:'verbessere',verba:'Wörter',haec:'diese',tabulam:'die Tafel (Akkusativ)',gratias:'Dank',tibi:'dir',ago:'ich sage / erstatte',dama:'Dama',vas:'Gefäß',vasa:'Gefäße',grave:'schwer',gravis:'schwer; ernsthaft',grandia:'große',parva:'kleine',grandium:'der großen',grandis:'groß',cum:'mit (+ Ablativ)',amico:'Freund (hier Ablativ)',felici:'glücklich (hier Ablativ)',felix:'glücklich',portat:'trägt',celeriter:'schnell (Art der Handlung)',celer:'schnell',est:'ist',primum:'zuerst',deinde:'danach',postremo:'zuletzt',venit:'kommt',livia:'Livia',numerat:'zählt',rufus:'Rufus',scribit:'schreibt',mercator:'Händler',narrat:'erzählt',clare:'deutlich',clara:'berühmt',prudenter:'klug / besonnen (Art der Handlung)',parvum:'klein',vasorum:'der Gefäße',amphora:'Amphore',magna:'groß',dona:'Geschenke'};
export const rufusMemory={
 'rufus-form':{title:'Rufus · Formen entschlüsseln',text:'Vom Bezugswort zur Adjektivform: Kasus, Numerus und Genus abgleichen. Rückwärts kann eine Form mehrere Möglichkeiten eröffnen: grandia ist Nominativ oder Akkusativ Plural Neutrum. Der Satz entscheidet.'},
 'rufus-read':{title:'Rufus · Zusammenhänge lesen',text:'Adjektive beschreiben Nomen, Adverbien hier die Art einer Handlung. Signalwörter wie primum, deinde und postremo ordnen Ereignisse. Die lateinische Wortstellung allein legt diese Reihenfolge nicht fest.'}
};
export const rufusTasks=[
 {id:'forward',format:'Form ergänzen',title:'Das Schild am Gefäß',speech:'Scribe, quaeso.',context:'Rufus braucht die Aufschrift „ein schweres Gefäß“. Du vervollständigst das Schild.',type:'input',source:'vas ___',prompt:'Ergänze gravis, grave passend zu vas (Nominativ Singular Neutrum).',answer:'grave',hint:'Für das Neutrum steht bei gravis, grave die Form auf -e.',explain:'vas grave: Beide Wörter stehen im Nominativ Singular Neutrum.',memory:'rufus-form'},
 {id:'reverse',format:'Rückwärts erschließen',title:'Nur eine Endung ist lesbar',speech:'Lege haec verba.',context:'Von einer Tafel ist nur grandia lesbar. Du hältst alle noch möglichen Deutungen fest.',type:'multi',source:'grandia',prompt:'Welche beiden KNG-Deutungen bleiben ohne Satzkontext möglich?',options:['Nominativ Plural Neutrum','Akkusativ Plural Neutrum','Nominativ Singular Femininum','Ablativ Singular Maskulinum'],answer:['Nominativ Plural Neutrum','Akkusativ Plural Neutrum'],hint:'Bei Neutra stimmen Nominativ und Akkusativ überein.',explain:'grandia ist Nominativ oder Akkusativ Plural Neutrum. Ohne Kontext darf ich keine der beiden Möglichkeiten ausschließen.',memory:'rufus-form'},
 {id:'versions',format:'Fassungen vergleichen',title:'Welche Abschrift passt?',speech:'Elige, quaeso.',context:'Drei Abschriften liegen auf Rufus’ Tisch. Gesucht ist „Dama trägt kleine Gefäße“.',type:'choice',prompt:'Welche Fassung hält genau das fest?',options:['Dama vasa grandia portat.','Dama vasa parva portat.','Dama vas parvum portat.'],answer:'Dama vasa parva portat.',hint:'Achte sowohl auf die Anzahl als auch auf die Größe.',explain:'vasa parva bezeichnet mehrere kleine Gefäße. vas parvum wäre nur eines, grandia wären große.'},
 {id:'reason',format:'Begründung wählen',title:'Verschiedene Endungen',speech:'Lege, quaeso.',context:'Rufus vermutet einen Abschreibfehler. Du suchst den Grund, weshalb die Notiz trotzdem stimmt.',type:'reason',source:'cum amico felici',prompt:'Warum passen amico und felici zusammen?',options:['Nach cum müssen beide Wörter auf -o enden.','felici ist ein Adverb und bleibt immer unverändert.','Beide sind Ablativ Singular Maskulinum; cum verlangt den Ablativ.'],answer:'Beide sind Ablativ Singular Maskulinum; cum verlangt den Ablativ.',hint:'Gleiche Merkmale verlangen nicht gleiche Endungen.',explain:'amico und felici stimmen in KNG überein. Ihre Deklinationen liefern unterschiedliche Endungen.',memory:'rufus-form'},
 {id:'order',format:'Ereignisse ordnen',title:'Die verstreuten Streifen',speech:'Ordina haec verba.',context:'Drei Berichtstreifen sind verrutscht. Die Zeitangaben verraten die Reihenfolge.',type:'order',source:'Primum Dama venit. Deinde Livia vasa numerat. Postremo Rufus scribit.',prompt:'Bringe die Ereignisse in ihre zeitliche Reihenfolge.',items:[['write','Rufus schreibt.'],['arrive','Dama kommt.'],['count','Livia zählt die Gefäße.']],slots:['1 · Zuerst','2 · Danach','3 · Zuletzt'],answer:{arrive:'0',count:'1',write:'2'},hint:'primum = zuerst, deinde = danach, postremo = zuletzt.',explain:'Ankunft → Zählen → Schreiben. Die Zeitangaben legen diese Reihenfolge fest.',memory:'rufus-read'},
 {id:'group',format:'Gruppen bilden',title:'Zwei Fächer für die Notizen',speech:'Ordina, quaeso.',context:'Rufus trennt Beschreibungen von Personen und Sachen von Beschreibungen ihrer Handlungen.',type:'group',prompt:'Ziehe jede Notiz in das passende Fach. Entscheide nach dem hervorgehobenen Wort.',items:[['a','Dama CELER est.'],['b','Dama CELERITER venit.'],['c','Livia CLARE narrat.'],['d','Vas GRAVE est.']],slots:['Adjektiv · Person oder Sache','Adverb · Art der Handlung'],answer:{a:'0',b:'1',c:'1',d:'0'},hint:'Frage: Wie ist jemand oder etwas? Oder: Wie geschieht etwas?',explain:'celer und grave beschreiben Dama bzw. das Gefäß. celeriter und clare beschreiben die Handlungen.',memory:'rufus-read'},
 {id:'pairs',format:'Wortgruppen verbinden',title:'Abgerissene Beschreibungen',speech:'Ordina haec verba.',context:'Die Beschreibungen haben sich von den Notizen gelöst. Du setzt die Wortgruppen wieder zusammen.',type:'pairs',prompt:'Ordne jeder Wortgruppe die grammatisch passende Form zu. Jede Karte gehört zu genau einer Notiz.',items:[['heavy','grave'],['big','grandium'],['happy','felici']],slots:['vasorum · Gen. Pl. n.','cum amico · Abl. Sg. m.','vas · Nom. Sg. n.'],answer:{big:'0',happy:'1',heavy:'2'},hint:'Beachte den Kasus: der Gefäße, mit einem Freund, ein Gefäß.',explain:'vasorum grandium · cum amico felici · vas grave. Die KNG-Merkmale entscheiden, nicht gleiche Endungen.',memory:'rufus-form'},
 {id:'mark',format:'Im Text markieren',title:'Was trägt Dama?',speech:'Lege haec verba.',context:'Rufus möchte die gesamte Warenbezeichnung aus diesem Vermerk übernehmen.',type:'mark',source:'Dama vas grave portat.',tokens:['Dama','vas','grave','portat.'],prompt:'Markiere Nomen und zugehöriges Adjektiv, die zusammen das getragene Gefäß bezeichnen.',answer:['1','2'],hint:'Die gesuchte Wortgruppe antwortet auf „wen oder was trägt Dama?“.',explain:'vas grave ist die zusammengehörige Wortgruppe: ein schweres Gefäß.',memory:'rufus-read'},
 {id:'repair',format:'Fehler berichtigen',title:'Eine verrutschte Endung',speech:'Corrige tabulam, quaeso.',context:'Ein Kopist hat eine Endung verwechselt. Dama trägt mehrere kleine Gefäße.',type:'repair',source:'Dama vasa parvum portat.',tokens:['Dama','vasa','parvum','portat.'],prompt:'Markiere das fehlerhafte Wort und schreibe seine richtige Form.',answer:'parva',wrongIndex:'2',hint:'vasa ist Plural Neutrum. Die Beschreibung muss dazu passen.',explain:'Dama vasa parva portat. parvum ist Singular; zu vasa gehört hier parva.',memory:'rufus-form'},
 {id:'translate',format:'Mit Worthilfen übersetzen',title:'Die Nachricht für Rufus',speech:'Lege, quaeso.',context:'Eine letzte Nachricht ist angekommen. Halte ihre Bedeutung auf Deutsch fest.',type:'translation',source:'Mercator cum amico felici venit. Dama vasa grandia portat.',translation:'Der Händler kommt mit einem glücklichen Freund. Dama trägt große Gefäße.',prompt:'Übersetze beide Sätze. Für dein Selbstständig-Ziel kannst du höchstens zwei verschiedene Wörter nachschlagen. Mehr Hilfe bleibt möglich.',budget:2,criteria:['Der Händler kommt mit einem glücklichen Freund.','Dama trägt mehrere große Gefäße.'],hint:'Kläre zuerst, wer etwas tut. cum verbindet den Händler mit seinem Begleiter.',explain:'Vergleiche den Sinn, nicht den genauen Wortlaut. Die Übersetzung wird von dir selbst anhand der beiden Aussagen geprüft.',memory:'rufus-read'}
];
const prerequisites={forward:'q3',reverse:'q3',versions:'q3',reason:'q3',group:'q5',pairs:'q3',mark:'q2',repair:'q1',translate:'q3'};
for(const t of rufusTasks){t.requiredQuest=prerequisites[t.id]||null;t.topic=({q1:'KNG · Wiederholung',q2:'Adjektive · Wortgruppen lesen',q3:'i-Adjektive · Formen und KNG',q5:'Adjektiv und Adverb'})[t.requiredQuest]||'Textverständnis · Zeitangaben';}
export const wordKey=s=>s.toLowerCase().replace(/[^a-z]/g,'');
const normalize=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[.!?]+$/,'');
export function initialAnswer(t){return ['multi','mark'].includes(t.type)?[]:['order','group','pairs','repair'].includes(t.type)?{}:'';}
export function correctRufus(t,a){
 if(['multi','mark'].includes(t.type))return Array.isArray(a)&&new Set(a).size===t.answer.length&&t.answer.every(v=>a.includes(v));
 if(['order','group','pairs'].includes(t.type))return t.items.every(([id])=>a?.[id]===t.answer[id]);
 if(t.type==='repair')return a?.index===t.wrongIndex&&normalize(a?.text)===t.answer;
 if(t.type==='translation')return false; // Free translation requires explicit self-review.
 return normalize(a)===normalize(t.answer);
}
export function placeCard(t,answer,id,slot){
 const a={...answer};if(!t.items.some(([key])=>key===id)||!t.slots[Number(slot)])return a;
 if(t.type!=='group'){const occupant=t.items.find(([key])=>key!==id&&a[key]===slot)?.[0];if(occupant){if(a[id]!==undefined)a[occupant]=a[id];else delete a[occupant];}}
 a[id]=slot;return a;
}
export function assisted(t,p){return !!p.full||!!p.hint||!!p.revisedAfterExample||(t.budget!==undefined&&p.words.length>t.budget)||p.attempts>1;}
export function freshRufus(){return {selected:null,tasks:{}};}
export function progressFor(s,t){return s.tasks[t.id]??=( {answer:initialAnswer(t),words:[],full:false,hint:false,example:false,review:[],attempts:0,done:false} );}
export function restoreRufus(raw){
 const s=freshRufus();if(!raw)return s;s.selected=rufusTasks.some(t=>t.id===raw.selected)?raw.selected:null;
 for(const t of rufusTasks){const r=raw.tasks?.[t.id];if(!r)continue;const p=progressFor(s,t);
  if(typeof r.answer===typeof p.answer&&r.answer!==null&&Array.isArray(r.answer)===Array.isArray(p.answer))p.answer=r.answer;
  p.words=Array.isArray(r.words)?[...new Set(r.words.filter(k=>(t.source||'').split(/\s+/).map(wordKey).includes(k)&&Object.hasOwn(glossary,k)))]:[];
  for(const k of ['full','hint','example','revisedAfterExample'])p[k]=r[k]===true;p.attempts=Math.max(0,Number(r.attempts)||0);p.review=t.criteria?.map((_,i)=>r.review?.[i]===true)||[];
  p.done=r.done===true&&(t.type==='translation'?typeof p.answer==='string'&&!!p.answer.trim()&&p.example&&p.review.every(Boolean)&&p.review.length===t.criteria.length:correctRufus(t,p.answer));
 }return s;
}


