/** Shared, deterministic SRL policy. No storage, UI, diagnoses or answer contents.
 * These are configurable product heuristics, NOT validated psychometric thresholds.
 * Existing immutable learning events are the single source of evidence.
 */
export const SRL_VERSION=2;
export const SRL_RULES=Object.freeze({maxUnplanned:2,cooldownMs:5*60*1000,rollingWindowMs:30*60*1000,errorWindowMs:8*60*1000,questErrors:5,questAttemptWindow:7,skillErrors:4,skillTasks:2,skillErrorRate:.6,examFailedRounds:2,errorStreak:3,challengeErrorStreak:5,skipCount:3,skipWindowMs:15*60*1000,rapidExits:3,rapidExitMs:45000,orientationWindowMs:10*60*1000,strategyOutcomeMs:15*60*1000,
 fade:{3:{runs:6,quests:2,firstTry:.75,success:.85,independent:1},2:{runs:10,quests:3,firstTry:.8,success:.9,independent:2},1:{runs:12,quests:3,firstTry:.85,success:.9,independent:3}}});
export const SUPPORT_DEFAULTS=Object.freeze({navigation:3,planning:2,strategy:2,content:0,challenge:1});
export const SUPPORT_LABELS={navigation:'Auswahl des nächsten Schritts',planning:'Planung',strategy:'Strategieimpulse',content:'Fachliche Hilfen',challenge:'Herausforderung'};
export const GOALS={topic:'Ein Thema üben',open:'Offene Quests bearbeiten',explore:'Einen neuen Bereich erkunden',challenge:'Eine Herausforderung versuchen',self:'Selbst entscheiden'};
export const NEXT_GOALS={continue:'Hier weiterüben',challenge:'Die Herausforderung noch einmal probieren',open:'Offene Quests bearbeiten',explore:'Ein neues Gebiet entdecken',later:'Beim nächsten Mal entscheiden'};
export const STRATEGIES={knowledge:'Passendes Wissen nachlesen',check:'Eigenen Rechenweg prüfen',reread:'Genau lesen',hint:'Einen kleinen Hinweis nutzen',example:'Ein ähnliches Beispiel ansehen',steps:'In kleine Schritte zerlegen',person:'Hilfe bei einer Person holen',later:'Später weiterarbeiten',drawing:'Eine Skizze oder Darstellung nutzen',try:'Selbst ausprobieren'};
export const SKIP_REASONS={known:'Ich glaube, ich kann das schon',difficult:'Die Aufgaben sind gerade zu schwierig',change:'Ich brauche einen Themenwechsel',return:'Ich komme später zurück',explore:'Ich möchte weiter erkunden',unspecified:'Keine Angabe'};
export const SRL_EVENTS={srl_strategy_review:'Bisheriges Vorgehen eingeschätzt',srl_plan_set:'Lernplan gewählt',srl_prompt_shown:'Regulationsimpuls angeboten',srl_prompt_answered:'Regulationsimpuls beantwortet',srl_strategy_selected:'Lernstrategie gewählt',srl_strategy_outcome:'Nach Strategie weitergearbeitet',srl_support_changed:'Unterstützung angepasst',srl_navigation_choice:'Nächsten Lernschritt gewählt',srl_reflection:'Sitzung reflektiert',srl_challenge_decision:'Über Vertiefung entschieden',srl_area_decision:'Über Gebietswechsel entschieden'};
const last=(a,f)=>{for(let i=a.length-1;i>=0;i--)if(f(a[i]))return a[i];return null;};
const time=e=>Date.parse(e.timestamp);
export function supportLevels(events,asOf=Infinity){const levels={...SUPPORT_DEFAULTS};for(const e of events)if(e.type==='srl_support_changed'&&time(e)<=asOf&&Object.hasOwn(levels,e.data.dimension)&&Number.isInteger(e.data.level)&&e.data.level>=0&&e.data.level<=3)levels[e.data.dimension]=e.data.level;return levels;}
export function latestPlan(events,sessionId){return last(events,e=>e.sessionId===sessionId&&e.type==='srl_plan_set');}
/** The latest reflection is authoritative: a deliberate 'decide later' clears an older intention. */
export function previousIntention(events,sessionId){const e=last(events,e=>e.sessionId!==sessionId&&e.type==='srl_reflection');return e?.data.nextGoal&&e.data.nextGoal!=='later'?e:null;}
export function promptBudget(events,sessionId,now=Date.now(),rules=SRL_RULES){
 const prompts=events.filter(e=>e.type==='srl_prompt_shown'&&e.data.unsolicited===true),current=prompts.filter(e=>e.sessionId===sessionId),recent=prompts.filter(e=>now-time(e)<rules.rollingWindowMs),latest=prompts.at(-1);
 return {allowed:current.length<rules.maxUnplanned&&recent.length<rules.maxUnplanned&&(!latest||now-time(latest)>=rules.cooldownMs),used:current.length,rollingUsed:recent.length,nextAt:latest?time(latest)+rules.cooldownMs:null};
}
export function repeatedErrors(events,taskRunId,kind='regular',rules=SRL_RULES){if(!taskRunId||!['regular','challenge'].includes(kind))return false;let streak=0;for(let i=events.length-1;i>=0;i--){const e=events[i];if(e.taskRunId!==taskRunId||e.type!=='task_attempt')continue;if(e.data.correct)break;streak++;}return streak>=(kind==='challenge'?rules.challengeErrorStreak:rules.errorStreak);}
export function multipleSkips(events,sessionId,now=Date.now(),rules=SRL_RULES){const lastPrompt=last(events,e=>e.sessionId===sessionId&&e.type==='srl_prompt_shown'&&e.data.reason==='skips');const cutoff=Math.max(now-rules.skipWindowMs,lastPrompt?time(lastPrompt):0);return [...new Set(events.filter(e=>e.sessionId===sessionId&&e.kind==='regular'&&e.type==='quest_skipped'&&time(e)>cutoff).map(e=>e.questId))];}
export function rapidExits(events,sessionId,now=Date.now(),rules=SRL_RULES){const recent=events.filter(e=>e.sessionId===sessionId&&time(e)>=now-rules.orientationWindowMs),found=new Set();for(const e of recent.filter(e=>e.type==='quest_paused'&&e.kind==='regular')){const start=last(recent,x=>x.runId===e.runId&&['quest_started','quest_resumed'].includes(x.type)&&x.timestamp<=e.timestamp);if(start&&time(e)-time(start)<rules.rapidExitMs&&!recent.some(x=>x.runId===e.runId&&x.timestamp>=start.timestamp&&x.timestamp<=e.timestamp&&['task_attempt','otherHelp_opened','example_opened','hint_opened','knowledge_opened'].includes(x.type)))found.add(e.questId);}return [...found];}
/** One record per attempted task run; repeated reviews are not additional tasks. */
export function performanceEvidence(events,{kind='regular',after='',topicId=null}={}){const runs=new Map();for(const e of events){if(e.timestamp<after||e.kind!==kind||topicId&&e.topicId!==topicId||e.type!=='task_attempt')continue;let r=runs.get(e.taskRunId);if(!r){r={taskRunId:e.taskRunId,questId:e.questId,topicId:e.topicId,attempts:0,errors:0,firstCorrect:e.data.correct,firstAttemptAt:e.timestamp,correct:false};runs.set(e.taskRunId,r);}r.attempts++;if(e.data.correct)r.correct=true;else r.errors++;}const a=[...runs.values()],n=a.length;const solutions=new Map();for(const e of events)if(e.type==='solutionStep_opened'&&!solutions.has(e.taskRunId))solutions.set(e.taskRunId,e.timestamp);for(const r of a)r.firstAssisted=!!solutions.get(r.taskRunId)&&solutions.get(r.taskRunId)<r.firstAttemptAt;return {runs:n,quests:new Set(a.map(r=>r.questId)).size,attempts:a.reduce((n,r)=>n+r.attempts,0),errors:a.reduce((n,r)=>n+r.errors,0),solved:a.filter(r=>r.correct).length,firstTry:n?a.filter(r=>r.firstCorrect).length/n:null,success:n?a.filter(r=>r.correct).length/n:null,items:a};}
export function fadeDecision(events,levels=supportLevels(events),rules=SRL_RULES){const level=levels.navigation,rule=rules.fade[level];if(!rule)return null;const change=last(events,e=>e.type==='srl_support_changed'&&e.data.dimension==='navigation'),after=[change?.timestamp||'',last(events,e=>e.type==='curriculum_changed')?.timestamp||''].sort().at(-1);const m=performanceEvidence(events,{after});const unaidedFirstTry=m.runs?m.items.filter(r=>r.firstCorrect&&!r.firstAssisted).length/m.runs:0;const completedAt=new Map();for(const e of events)if(e.timestamp>after&&e.type==='quest_completed'&&e.kind==='regular')completedAt.set(e.questId,e.timestamp);const independent=new Set(events.filter(e=>e.timestamp>after&&e.type==='srl_navigation_choice'&&['map','self','repeat','new','continue','challenge'].includes(e.data.source)&&e.data.questId&&(completedAt.get(e.data.questId)||'')>e.timestamp).map(e=>e.data.questId)).size;
 if(m.runs<rule.runs||m.quests<rule.quests||unaidedFirstTry<rule.firstTry||m.success<rule.success||independent<rule.independent)return null;
 return {dimension:'navigation',level:level-1,reason:'stable_regular_work_and_choices',evidence:{runs:m.runs,quests:m.quests,firstTry:m.firstTry,unaidedFirstTry,success:m.success,independent,challengeCompleted:events.some(e=>e.timestamp>after&&e.type==='challenge_completed')}};
}
export function successfulStrategies(events,sessionId){const current=events.filter(e=>e.sessionId===sessionId),outcomes=current.filter(e=>e.type==='srl_strategy_outcome'&&e.data.solved===true);return outcomes.map(e=>({strategy:e.data.strategy,taskId:e.taskId,kind:e.kind,assisted:e.data.assisted===true,selectionEventId:e.data.selectionEventId}));}
export function sessionReview(events,sessionId,catalog){const es=events.filter(e=>e.sessionId===sessionId),reg=performanceEvidence(es),challenge=performanceEvidence(es,{kind:'challenge'}),plan=latestPlan(events,sessionId)?.data||null;const uniq=type=>new Set(es.filter(e=>e.type===type).map(e=>e.questId)).size;const topics=(catalog?.topics||[]).map(t=>({...t,...performanceEvidence(es,{topicId:t.topicId})}));return {sessionId,plan,worked:new Set(es.filter(e=>['quest_started','quest_resumed','challenge_started'].includes(e.type)&&['regular','challenge'].includes(e.kind)).map(e=>e.questId)).size,completed:new Set(es.filter(e=>e.type==='quest_completed'&&e.kind==='regular').map(e=>e.questId)).size,challengesCompleted:uniq('challenge_completed'),skipped:uniq('quest_skipped'),regular:reg,challenge,unlocked:uniq('challenge_unlocked'),challengeStarted:uniq('challenge_started'),hints:es.filter(e=>e.type==='hint_opened'&&!e.data.resumed).length,examples:es.filter(e=>e.type==='example_opened'&&!e.data.resumed).length,strategies:successfulStrategies(events,sessionId),topics,unplanned:es.filter(e=>e.type==='srl_prompt_shown'&&e.data.unsolicited).length,duration:es.filter(e=>e.type==='activity_slice').reduce((n,e)=>n+e.data.duration,0)};}
export function calibrationText(review,endConfidence){const m=review.regular,c=review.challenge,topic=review.plan?.topicId,focus=topic?review.topics.find(t=>t.topicId===topic):null;if(topic&&(!focus||focus.runs<3))return 'Zum gewählten Thema gibt es heute noch zu wenige Antworten für einen Vergleich. Deine Einschätzung darf sich trotzdem verändern.';if(m.runs<3)return 'Heute gibt es noch wenige Antworten. Daraus lässt sich keine sichere Einschätzung ableiten.';if(m.firstTry>=.8&&c.runs>=2&&c.firstTry<.6)return 'Bei den normalen Aufgaben warst du oft gleich richtig. Die Herausforderungsaufgaben waren deutlich anspruchsvoller.';const f=focus||m;if(endConfidence>=4&&f.firstTry>=.8)return 'Deine Einschätzung und die heute bearbeiteten Aufgaben passen gut zusammen. Das ist kein Nachweis für alle Aufgaben des Themas.';if(endConfidence<=2&&f.firstTry>=.8)return 'Du fühlst dich noch unsicher. Bei den heute bearbeiteten Aufgaben waren viele erste Antworten richtig. Beides darf nebeneinanderstehen.';if(endConfidence>=4&&f.firstTry<.6)return 'Du fühlst dich sicher. Bei einigen heutigen Aufgaben brauchtest du mehrere Anläufe. Suche dir beim nächsten Mal einen solchen Gedanken zum Vertiefen aus.';return 'Du hast Aufgaben bearbeitet und Erfahrungen gesammelt. Nutze deine Einschätzung für deinen nächsten Lernschritt.';}
/** Raw evidence only; no global self-regulation score or challenge avoidance diagnosis. */
export function regulationSummary(events,{from='',to='9999-12-31T23:59:59.999Z'}={}){const past=events.filter(e=>e.timestamp<=to),es=past.filter(e=>e.timestamp>=from),firstSkip=new Map();for(const e of past)if(e.type==='quest_skipped'&&!firstSkip.has(e.questId))firstSkip.set(e.questId,e.timestamp);const plans=es.filter(e=>e.type==='srl_plan_set'),reflections=es.filter(e=>e.type==='srl_reflection'),prompts=es.filter(e=>e.type==='srl_prompt_shown'&&e.data.unsolicited),strategies=es.filter(e=>e.type==='srl_strategy_selected'),outcomes=es.filter(e=>e.type==='srl_strategy_outcome');return {levels:supportLevels(past),plans,reflections,prompts,strategies,outcomes,navigation:es.filter(e=>e.type==='srl_navigation_choice'),changes:es.filter(e=>e.type==='srl_support_changed'),challenges:es.filter(e=>e.type==='srl_challenge_decision'),areaDecisions:es.filter(e=>e.type==='srl_area_decision'),skips:es.filter(e=>e.type==='srl_prompt_answered'&&e.data.reason==='skips'),returned:new Set(es.filter(e=>['quest_started','quest_resumed'].includes(e.type)&&firstSkip.has(e.questId)&&firstSkip.get(e.questId)<e.timestamp).map(e=>e.questId)).size};}

/** One evidence window; challenge errors never become a regular-competence trigger.
 * Counts describe observed attempts, not a diagnosis of a misconception.
 */
export const REVIEW_ACTIONS={reread:'Die Aufgabe noch einmal genau gelesen',knowledge:'Das Wissen nachgelesen',hint:'Einen Tipp benutzt',example:'Ein Beispiel angesehen',check:'Meinen Rechenweg überprüft',other:'Etwas anderes ausprobiert',guess:'Bisher nur noch einmal geraten oder probiert'};
export function errorEvidence(events,context,now=Date.now(),rules=SRL_RULES){
 if(!context?.taskRunId||!['regular','challenge'].includes(context.kind))return null;
 const recent=events.filter(e=>e.type==='task_attempt'&&e.kind===context.kind&&now-time(e)<=rules.errorWindowMs);
 if(!recent.length||recent.at(-1).data.correct)return null;
 if(repeatedErrors(recent,context.taskRunId,context.kind,rules))return {pattern:'same_task',count:recent.filter(e=>e.taskRunId===context.taskRunId&&!e.data.correct).length};
 if(context.kind==='challenge')return null; // Transfer struggle does not escalate broad basic support.
 const quest=recent.filter(e=>e.questId===context.questId).slice(-rules.questAttemptWindow),wrong=quest.filter(e=>!e.data.correct);
 if(wrong.length>=rules.questErrors&&new Set(wrong.map(e=>e.taskRunId)).size>=2)return {pattern:'quest_window',count:wrong.length};
 const skill=recent.filter(e=>context.skillId&&e.skillId===context.skillId),errors=skill.filter(e=>!e.data.correct);
 if(errors.length>=rules.skillErrors&&new Set(errors.map(e=>e.taskRunId)).size>=rules.skillTasks&&errors.length/skill.length>=rules.skillErrorRate)return {pattern:'skill_window',count:errors.length};
 return null;
}
export function helpEvidence(events,context){
 const es=events.filter(e=>e.taskRunId===context?.taskRunId&&!e.data?.automatic&&!e.data?.resumed);
 return {hint:es.filter(e=>e.type==='hint_opened').length,example:es.filter(e=>e.type==='example_opened').length,knowledge:es.filter(e=>e.type==='otherHelp_opened'&&e.data.screen==='lesson').length};
}
